### ISSUE TITLE
Convert dates to py datetime

### ISSUE THREAD

**Issue by reevery** [tableau/server-client-python#102]
Is there any reason why this module doesn't convert dates to python datetime objects? Things like last logged in / last updated etc.

**Comment by RussTheAerialist** [comment]
I think this falls into the bucket of "things we haven't done yet".  Definitely something we want to implement sooner rather than later.

**Comment by RussTheAerialist** [comment]
This morning, I checked in support for this into development, which will be included in the next release (yay!) and thanks for pointing this out!
