### ISSUE TITLE
When we publish workbooks or datasources and use debug mode, user and password are displayed in plain text

### ISSUE THREAD

**Issue by DieKry** [tableau/server-client-python#1024]
[extract_from_log_publishing_using_debug_mode.txt](https://github.com/tableau/server-client-python/files/8472988/extract_from_log_publishing_using_debug_mode.txt)
Our environment:
Tableau ServerVersion: 2021.4.2 (20214.21.1217.2252) 64-bit LINUX
TableauServerClient: 0.17.0
Python: 3.8

The excerpts from the log show this fact. It is not relevant whether we publish workbooks with embedded datasources or with published datasouces. Can the output of user and password in the LOG be suppressed or encrypted when we use debug mode? We actually expect this to be the case.
In the excerpts user, password, database server and port were replaced. 
I added the excerpts from the log in the attached file.

@jacalata. Sorry for the delay, but I had a few days vacation. In the meantime I was able to install version 0.19.0 in a test environment and verify that no sensitive data is visible in plain text. Thanks a lot, works as expected.

**Comment by jacalata** [comment]
@DieKry this fix is now available in the latest release, 0.19.0. Please let us know if you continue to see any sensitive values logged after updating!
