### ISSUE TITLE
In Operator not working in the filter and sort option

### ISSUE THREAD

**Issue by pavan-eyewa** [tableau/server-client-python#1027]
When I use the In Operator, the list is empty but it works when Equals is used.

all_workbooks = server.workbooks.filter(project_name__in=["Project A", "Project B"])

**Versions**
 - Tableau Server version (2021.4.2)
 - Python version(3.8.9)
 - TSC library version(latest)

**Comment by bcmyguest1** [comment]
You need to provide request option to a `server.workbooks.get(request_options=<options>)` (see here: https://tableau.github.io/server-client-python/docs/filter-sort and https://tableau.github.io/server-client-python/docs/api-ref#workbooks)

**Comment by pavan-eyewa** [comment]
It worked. Thanks

**Comment by jorwoods** [comment]
@pavan-eyewa What specific version of TSC are you using? I just tested that code on my server and it worked.
