### ISSUE TITLE
Refreshing get() lists

### ISSUE THREAD

**Issue by reevery** [tableau/server-client-python#104]
I couldn't find this in the docs so apologies for raising here.

Let's say I've queried the list of projects from my server, then added a new project. Then I want to refresh the list, but re-running get() doesn't update the list.

How do I make this work?

`    with server.auth.sign_in(tableau_auth):
        ## get the list of projects from Tableau
        projects, pagination_info = server.projects.get()

        # Find local projects which do not exist on Tableau
        for p in (x for x in local_projects if x not in (p.name for p in projects)):
                # Add Project
                new_project = TSC.ProjectItem(name=p)
                try:
                    project_id = server.projects.create(new_project).id
                except TSC.ServerResponseError as e:
                    #TODO
                    pass
    
        projects, pagination_info = server.projects.get()
        for p in projects:
            print(p.name, p.id)`

This last iteration is returning the original list of projects, not the new one.

**Comment by RussTheAerialist** [comment]
Thanks for contacting us about this.  This is one of those "you need to understand the REST api and how it works" things that aren't quite documented well yet.

Our data model in the server is "eventually consistent".  The get() call always makes calls in the REST api but there is a delay between when you create something and when it's available via the query endpoints.  The eventually consistent does not impact your ability to use the project immediately, it's only a delay between the main database, and the service that we use for querying.

Can you give me a little more detail about your use case so I can make suggestions on usage patterns?  If you are just trying to verify that the create happened properly, you can put a sleep in between the create and when you query again, but if you are trying to use the project, just keep the id/created project around like you are doing in the first for-loop, and use that immediately.

**Comment by reevery** [comment]
Thanks for this.

My specific use case is as above, except the bit below the project iteration is trying to upload workbooks to a project. 

1. I've queried the query.get() first, so I can work out which projects exist, and which don't. I know at this point I could drop the call and just handle the errors for the projects which exist, but I wanted it to be clean.

2. Then I [re]query the projects list, to get the IDs for the projects I want to upload workbooks to

3. Then I iterate through the workbooks and upload them.

Does that make sense? That's roughly what the code I attached does.

**Comment by RussTheAerialist** [comment]
yup that completely makes sense.  Assuming you don't have thousands and thousands of projects, it might be more consistent to not requery, but to build up the list of the project objects the first time around, and if you create one, add it to the list, then use that cached list for the second go around.

There are some issues with the approach I just suggested in that it doesn't account for deleted projects, so depending on how your server is used, this may or may not be an issue.

Rough code would look something like this:
```python
# Note that get generally returns only the first page of results, so if you really need all of them, use the pager
projects = list(TSC.Pager(server.projects))
project_names = [p.name for p in projects]
projects_to_create = (p for p in local_projects  if p.name not in project_names)
for project in projects_to_create:
   project_item = TSC.ProjectItem(name=project)
   new_project = server.projects.create(project_item)
   projects.append(new_project)
```

Now projects contains the list of all project items that existed before or that you created.

That would avoid you needing to requery, but again, with the caveat that if projects get deleted, there might be an issue.

**Comment by reevery** [comment]
Fair enough, that works.
