### ISSUE TITLE
Update permissions Fails

### ISSUE THREAD

**Issue by jaybythebay** [tableau/server-client-python#1042]
**Describe the bug**
Updating the project permissions fails.  `projects.update_permission` says that it should ["Add or update project permissions." ](https://tableau.github.io/server-client-python/docs/api-ref#projects). However, this appears to use the `add permission` API and fails on update.

I'm trying to update permissions and either the docs are wrong or the code sample is wrong.  

**Versions**
Details of your environment, including:
 - Tableau Online
 - Python version 3.10
 - TSC library version 0.18

**To Reproduce**
Create a project permission for a group in Tableau Online.  Try to change the permission with this code via the API.  

1st I map a permission set to a group. Here are the permissions sets:
```
project_deny_all = {"Read": "Deny",
				   "Write": "Deny",
					}

project_read = {"Read": "Allow",
			   "Write": "Deny",
				}

project_write = {"Read": "Allow",
			   "Write": "Deny",
				 }
```

Then I run through my groups and my permission mappings.
```
		projects = list(TSC.Pager(self.server.projects))
		groups = list(TSC.Pager(self.server.groups))

		for each_project, each_group_setting in permission_set.items():
			print(each_project)
			project = list(filter(lambda x: x.name == each_project, projects))[0]

			for each_group, each_setting in each_group_setting.items():
				print(each_project, each_group, each_setting)
				group = list(filter(lambda x: x._id == each_group, groups))[0]

				if each_setting is not None:
					updated_project = self.server.projects.update_datasource_default_permissions(project, [TSC.PermissionsRule(
						grantee=group,
						capabilities=each_setting
					)])
```

**Results**
if I am trying to change a permission I get a message such as this:

```
 409008: Resource Conflict
                Project 'abc123-1234-1234-asdf-asdf1234asdf' cannot have the capability 'Read' set for group '1234456-asdf-asdf-870c-asdf0876' to both 'Allow' and 'Deny'.

```

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
Thanks for logging - I believe in this case the docs are wrong for tsc, and the method only adds permissions. It could be worth adding a real "update" method in the library that handles this error and deletes any conflicting permissions - would you use that? If so, would you expect it to delete *all* existing permissions, or just the ones you change?

**Comment by jaybythebay** [comment]
Thanks for responding to this.  I would definitely use an update.  I am currently deleting and then re-creating permissions.  I wrote a script that does this:

1. Keeps a dictionary of permissions mappings for different profiles:
```
workbook_read = {"Read": "Allow",
					 "Filter": "Allow",
					 "ViewComments": "Allow",
					 "AddComment": "Allow",
					 "ExportImage": "Allow",
					 "ExportData": "Allow",
					 "RunExplainData": "Allow",
					 "ShareView": "Allow",
					 "ViewUnderlyingData": "Allow",
					 "WebAuthoring": "Deny",
					 "ExportXml": "Deny",
					 "Write": "Deny",
					 "CreateRefreshMetrics": "Deny",
					 "ChangeHierarchy": "Deny",
					 "Delete": "Deny",
					 "ChangePermissions": "Deny",
					 }
 ```
 2. I map the permission sets to different groups:
 ```
project_group_permissions = {'Project_1': {
								   'Group_1': {'project': project_read, 'workbook': workbook_read, 'datasource': None},
								   'Group_2': {'project': project_read, 'workbook': workbook_read, 'datasource': None},
```
3. I download the existing permissions from Tableau Online
4. I compare the permissions I want in the dictionary config to the permissions on Tableau Online
5.  If the permission does not match and is not none I delete the permissions for the project-group-capability
6. I add the new permissions I want back in

If there was a true update I could skip a lot of code.  

How would you implement this? Does the API allow update? Or are you going to just try to update the permission and then do the deletion/re-creation in error handling?
