### ISSUE TITLE
Save to png with range filter

### ISSUE THREAD

**Issue by gm-gwu** [tableau/server-client-python#1043]
I'm trying to export a tableau view as a png after applying some filters, and I'm able to apply multiple filters as below example. I could not find any example that can be used for range filters (slider), for example, BasicSalary > 1000 and <5000. How can I apply a view filter for this variable, any help appreciated. 

# set the image request option
image_req_option = TSC.ImageRequestOptions(imageresolution=TSC.ImageRequestOptions.Resolution.High, maxage=1)

# (optional) set a view filter
image_req_option.vf('Category', 'Furniture,Appliance')

# retrieve the image for the view
server.views.populate_image(view_item, image_req_option)

**Comment by bcantoni** [comment]
Closing due to age.
