### ISSUE TITLE
Memory Error downloading large extract data sources

### ISSUE THREAD

**Issue by TCMurph** [tableau/server-client-python#105]
Hi,

I am using the module to download data sources, and publish them to another server instance. Most data sources download fine, but larger extracts give the error below. Have you seen this before?
I can provide the code if you need it.
There is no memory spike on either the Tableau Server, or the machine I am running the code.

Thanks.

Traceback (most recent call last):
  File "tableauserver.py", line 44, in <module>
    prod.datasources.download(datasource.id)
  File "C:\Python27\lib\site-packages\tableauserverclient\server\endpoint\dataso
urces_endpoint.py", line 67, in download
    server_response = self.get_request(url)
  File "C:\Python27\lib\site-packages\tableauserverclient\server\endpoint\endpoi
nt.py", line 54, in get_request
    request_object=request_object)
  File "C:\Python27\lib\site-packages\tableauserverclient\server\endpoint\endpoi
nt.py", line 34, in _make_request
    server_response = method(url, **parameters)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 628, in send
    r.content
  File "C:\Python27\lib\site-packages\requests\models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes
()
MemoryError

**Comment by RussTheAerialist** [comment]
Based on the error, the python process is running out of memory because we are trying to hold the extract in memory.

A quick fix for you to try to check to make sure you are running the 64-bit version of python.  The 32-bit version has necessary upper memory limits because of the address space.  64-bit has significantly more address space.

The long term fix will be that we need to provide a way to stream the extract to disk rather than try to hold it all in memory.

**Comment by TCMurph** [comment]
Thanks for such a quick reply Russell.
I was running python 32-bit version (just an oversight on my part), so I downloaded the 64-bit version and tested it out on a 10gb extract, and it ran with no issues!! Thank you very much.

If you feel like the stream to disk is something that would be a good feature enhancement, I look forward to testing that out in the future.

Paul

**Comment by RussTheAerialist** [comment]
I'm going to reopen this one because I think we need to implement this.  I'm currently not at a computer so I can't make it as an enchancement, but it's definitely something I want to implement.

**Comment by TCMurph** [comment]
Russell - I've been testing more since implementing the 64-bit fix. It is doing some weird stuff with larger pubs for sure. Not sure what to make of it. Seems like it has the pub in memory, and creates the 0kb file, but never commits it to disk (or I didn't wait long enough!). When I kill the process, it does show the file with partial size committed to disk e.g. 5GB in memory, 0kb showing in file explorer, kill python process, and the file shows 1.5GB or similar. Perhaps I did't wait long enough, but it had been trying to download that data source for an hour when I killed it.
Just wanted to let you know.

Thanks.

Paul

**Comment by t8y8** [comment]
@RussTheAerialist I think it's just a matter of leveraging the built in `stream` functionality in requests if the download size is too big.

http://docs.python-requests.org/en/master/user/advanced/#body-content-workflow

Something like:
1. For Download calls, set `stream=True`
2. If `content-length` is bigger than something (I dunno, 512MB?) then user `iter_content`
3. Make sure everything is closed properly

**Comment by t8y8** [comment]
@TCMurph there's a potential fix in #111 -- I verified locally but since you originally reported the issue could you give it a spin and see if it solves the memory consumption for you?

I'm also curious how long it takes to download and if that length of time feels alright

**Comment by TCMurph** [comment]
@t8y8 No problem. I'll report back in the next 24 hours after I test.

Thanks.

**Comment by t8y8** [comment]
@TCMurph quick ping -- I actually merged this into development but would still love a confirmation!

**Comment by t8y8** [comment]
@TCMurph I'm going to close this issue (and assume no news is good news).

If the issue persists, let me know and we can reopen!
