### ISSUE TITLE
View Filter values with spaces are not recognized in server.views.populate_image

### ISSUE THREAD

**Issue by Smoothbore45** [tableau/server-client-python#1052]
When running server.views.populate_image(viewid, req_options), filter values with spaces don't function correctly. 

Example:
req_options.vf('Salesperson Location', '1200-Mitchell County')

**Versions**
 - Tableau Server version (or note if using Tableau Online) 2020.4.5 Linux
 - Python version 3.9 (running windows)
 - TSC library version 0.18 

**To Reproduce**
Use a filter value containing a space.

**Results**
-The tableau dashboard retrieved is blank with no data.  I know the filter field name 'Salesperson Location' appears to be working, because if I code it with a default value, it gets overwritten and provides me no results.
-Also, if I send the filter name "SalespersonLocation" the view is unaffected at all.  
-I suspect the error is a result of the filter view value not being parsed correctly for the space.  This is similar to another bug posted and fixed #763 
-I have tried using %20 or + in place of the space without success.

**Comment by jacalata** [comment]
This should work now if you pass in a regular string with spaces - the string will be url-encoded to add to the request. You can also see it working if you use tabcmd 2.x, which calls tsc underneath https://github.com/tableau/tabcmd/commit/c261d76e26cef78769df1166db0018d0fa37ba62
