### ISSUE TITLE
does populate_connections work for 2.2 version of the REST API?

### ISSUE THREAD

**Issue by TCMurph** [tableau/server-client-python#106]
I'm having trouble getting the connection information for a data source. I'm using Tableau Server 9.3, and specifying the 2.2 version of the REST API when working with the python module.

I'm getting the following error when trying to use populate_connections, and reading the 2.2 REST API documentation, it seems like you can update a data sources connection, but only query a workbooks connection details. Can you confirm this is correct?

404003: Resource Not Found

What i'm trying to achieve is a migration of data sources from server A to server B, but I need to query the data source's connection information in order for me to set the correct connection information before re-publishing to the destination server.

Thanks.

Paul

**Comment by t8y8** [comment]
Query Connections wasn't added for Data Sources until 10.0, which is API version 2.3 or greater.

**Comment by TCMurph** [comment]
Thanks Tyler. Just wanted to double check. Looks like i'll be implementing a workaround until we upgrade to 10 :)
