### ISSUE TITLE
Feature : Add permission control for Data Roles, Ask Data Lenses, and Metrics

### ISSUE THREAD

**Issue by RumblingHacked** [tableau/server-client-python#1063]
## Summary
Need to add support for modifying permissions for Data Roles, Ask Data Lenses, and Metrics.

## Request Type
If you know, say which of these types your request is in the title, and follow the suggestions for that type when writing your description.

****Type 1: support a REST API:**** 
If it is functionality that already exists in the [REST API](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm), example API calls are the clearest way to explain your request.
Need the following calls supported in TSC and the permission list updated.

Data roles:
DELETE /api/api-version/sites/site-luid/projects/project-luid/default-permissions/dataroles/groups/group-luid/capability-name/capability-mode

Lenses:
DELETE /api/api-version/sites/site-luid/projects/project-luid/default-permissions/lenses/groups/group-luid/capability-name/capability-mode

Metrics:
DELETE /api/api-version/sites/site-luid/projects/project-luid/default-permissions/metrics/groups/group-luid/capability-name/capability-mode

Data roles:
PUT /api/api-version/sites/site-luid/projects/project-luid/default-permissions/dataroles

Lenses:
PUT /api/api-version/sites/site-luid/projects/project-luid/default-permissions/lenses

Metrics:
PUT /api/api-version/sites/site-luid/projects/project-luid/default-permissions/metrics

****Type 2: add a REST API and support it in tsc.****
If it is functionality that can be achieved somehow on Tableau Server but not through the REST API, describe the current way to do it. (e.g: functionality that is available in the Web UI, or by using the Hyper API). For UI, screenshots can be helpful.

****Type 3: new functionality****
Requests for totally new functionality will generally be passed to the relevant dev team, but we probably can't give any useful estimate of how or when it might be implemented. If it is a feature that is 'about' the API or programmable access, here might be the best place to suggest it, but generally feature requests will be more visible in the [Tableau Community Ideas](https://community.tableau.com/s/ideas) forum and should go there instead.

## Description
A clear and concise description of what the feature request is. If you think that the value of this feature might not be obvious, include information like how often it is needed, amount of work saved, etc. If your feature request is related to a file or server in a specific state, describe the starting state when the feature can be used, and the end state after using it. If it involves modifying files, an example file may be helpful. 

This feature is needed to automate permission assignments for everything that is available in Tableau.

![](https://img.shields.io/badge/warning-Be%20careful%20not%20to%20post%20user%20names%2C%20passwords%2C%20auth%20tokens%20or%20any%20other%20private%20or%20sensitive%20information-red)

**Comment by TrimPeachu** [comment]
Hi,
any progress on this issue? I would find this really useful.

**Comment by jacalata** [comment]
With 0.24 this is partially complete, but Ask Data Lenses still needs to be added.

**Comment by jacalata** [comment]
Turns out Lenses got added last year already - https://github.com/tableau/server-client-python/pull/1049
