### ISSUE TITLE
Unable to publish hyper files > 64MB

### ISSUE THREAD

**Issue by rahulyerva789** [tableau/server-client-python#1065]
**Describe the bug**
Hi,

I am working on a script which uses Tableau Server Client python library to publish hyper files into the tableau server as a datasource. I am able to publish hyper files with size < 64Mb successfully, but when I tried publishing files greater than that(>64Mb), I am seeing this error in the logs. Looking for some help to resolve this issue. Am I missing anything

Permissions: Admin permissions

**Error:**
`INFO 2022-06-29 21:54:03,563 --- Uploading a chunk to session (ID: <session id>)
INFO 2022-06-29 21:54:03,563 --- 	Published 2663MB
INFO 2022-06-29 21:54:03,565 --- File upload finished (<session id>)
DEBUG 2022-06-29 21:54:03,565 --- request post, url: https://<tableau-server-address>/api/3.11/sites/<site-id>/datasources?datasourceType=hyper&overwrite=true&uploadSessionId=<session id>
DEBUG 2022-06-29 21:54:03,565 --- request content: bytearray(b'--53667aa5892c131e5c56f94e320d3fbf\r\nContent-Disposition: form-data; name="request_payload"; filename=""\r\nContent-Type: text/xml\r\n\r\n<tsRequest><datasource name=<hyper-file-name><project id="<project-id>" /></datasource></tsRequest>\r\n--53667aa5892c131e5c56f94e320d3fbf--\r..[redacted]')
DEBUG 2022-06-29 21:54:03,818 --- https://<tableau-server-address>:443 "POST /api/3.11/sites/<site-id>/datasources?datasourceType=hyper&overwrite=true&uploadSessionId=<session-id>" 403 None
DEBUG 2022-06-29 21:54:03,818 --- request post, url: https://<tableau-server-address>/api/3.11/auth/signout
DEBUG 2022-06-29 21:54:03,844 --- https://<tableau-server-address>:443 "POST /api/3.11/auth/signout HTTP/1.1" 204 0
DEBUG 2022-06-29 21:54:03,844 --- Server response from https://<tableau-server-address>/api/3.11/auth/signout:
	Content type None
INFO 2022-06-29 21:54:03,845 --- Signed out
ERROR 2022-06-29 21:54:03,845 --- failed with an error 

	**500000: Forbidden
		User does not have permission for action.(The server encountered an error and cannot complete your request. Contact your server administrator.)**`

**Below is the code**
from pathlib import Path
import tableauserverclient as TSC
import json
import logging
import time
import os

logpath = <log-path>
dateStr = time.strftime("log_%Y_%m_%d.log")
logFilePath = logpath + "\\" + dateStr
LOG_FORMAT = "%(levelname)s %(asctime)s --- %(message)s"
logging.basicConfig(filename=logFilePath, level=logging.DEBUG, format=LOG_FORMAT)
logger = logging.getLogger()

site_name = <site-name>
project_name = <project-name>
hyper_name = <hyperfile-name>
server_address = <tableau-server-address>
path_to_database = Path(hyper_name)
logger.debug('input received with site: {0}, project: {1}, hyper: {2}'.format(site_name, project_name, args.hyper))

def publish_hyper():
    try:
        tableau_auth = TSC.PersonalAccessTokenAuth(token_name=token_name, personal_access_token=token_value,
                                                   site_id=site_name)
        server = TSC.Server(server_address, use_server_version=True)`

        with server.auth.sign_in(tableau_auth):
            publish_mode = TSC.Server.PublishMode.Overwrite
            logger.debug('sign in successful')
            all_projects, pagination_item = server.projects.get()
            for project in TSC.Pager(server.projects):
                if project.name == project_name:
                    project_id = project.id
            print(project_id)
            datasource = TSC.DatasourceItem(project_id)
            logger.debug('Publishing hyper file {0} to the site {1} and project {2}'.format(hyper_name, site_name, project_name))
            print(f"Publishing {hyper_name} to {project_name}...")
            datasource = server.datasources.publish(datasource, path_to_database, publish_mode )
            logger.debug('Datasource published with Datasource ID {0} to the site {1} and project {2}'.format(datasource.id, site_name, project_name))
            print("Datasource published. Datasource ID: {0}".format(datasource.id))

    except Exception as e:
        logger.error('failed with an error {0}'.format(e))

**Versions**
 - Tableau Server version : **2021.1.5**
 - Python version:  **Python 3.7.9** 
 - TSC library version: **0.19.0**

**Comment by jacalata** [comment]
The maximum size of a file you can publish in one request is 64MB. If your file is that large (or even close to it), you should publish it in parts. See docs at https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_publish.htm

To do this in tsc, you should pass in asJob = True as one of the parameters of your publish call.

**Comment by rahulyerva789** [comment]
@jacalata thanks for the suggestion, I changed the line of code to 
`datasource = server.datasources.publish(datasource, path_to_database, publish_mode, as_job=True )`
Now I am not seeing above error but, it seems like the job is not getting started now. I see this log getting generated.

I am not able to see this job status in the UI

server response from https://server-address/api/3.11/sites/site-id/datasources?datasourceType=hyper&asJob=true&uploadSessionId=15632:8ba7756ca39447eb84920d3b9dc6b000-3:0:
	<ns0:tsResponse xmlns:ns0="http://tableau.com/api" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tableau.com/api http://tableau.com/api/ts-api-3.11.xsd"><ns0:job createdAt="2022-07-06T07:12:36Z" finishCode="1" id="5bda41b4-09a8-4fa4-8e43-599480d66eca" mode="Asynchronous" progress="0" type="PublishDatasource" /></ns0:tsResponse>

**Comment by jorwoods** [comment]
@rahulyerva789 if you use `as_job=True` then the call returns a job item, not a data source item. Then you can use the jobs endpoint to check the status of that job.

**Comment by rahulyerva789** [comment]
@jorwoods okay, I tried getting the job id it triggered and tried to bring the status
jobinfo = server.jobs.get_by_id(myJobId) 
print(jobinfo)

I am getting output as below
# PublishDatasource created_at(2022-07-06 07:12:36+00:00) started_at(None) completed_at(2022-07-06 07:12:36+00:00) progress (100) finish_code(1)>

**Comment by jorwoods** [comment]
@rahulyerva789 So on that job item, there will be a `notes` property. That should have more information.

**Comment by rahulyerva789** [comment]
@jorwoods tried with
publish_job = server.datasources.publish(datasource, path_to_database, publish_mode, as_job=True )
print(publish_job.notes)

Output:
[]

Its returning an empty list, am I missing something?

**Comment by jacalata** [comment]
Hi @rahulyerva789 , I didn't realize this issue wasn't solved for you back in July. It's odd that the job would show finish_code=1 and progress=100. Did you figure out anything more on this?

**Comment by dzucker-tab** [comment]
Not sure if this is relevant, but it just came to my attention that we don't have the TSM `configuration set` option `api.server.update_uploaded_file.max_size_in_mb` documented in the TSM reference. This impacts maximum Hyper upload size for the REST Hyper Update methods.

**Comment by jacalata** [comment]
closing this. If more help is needed, please re-open!
