### ISSUE TITLE
Password Authentication can fail if password contains special characters 

### ISSUE THREAD

**Issue by geordielad** [tableau/server-client-python#1066]
**Describe the bug**
A users password contained “&” this causes an authentication failure. 

**Versions**
Tested with TSC 0.19

**To Reproduce**
Create a user on Tableau Server or Cloud containing with a password containing an XML special character like “&” then authenticate with the username and password (not PAT)

**Results**
What are the results or error messages received?

Auth fails but will succeed if the special characters are encoded appropriately. E.g. &amp or &#38.

**Comment by bcantoni** [comment]
@geordielad do you have more details or an example of where this isn't working correctly?

I just did a quick test with:
* Tableau Server 2022.1.3
* TSC 0.19
* password: `this&that`

````
import tableauserverclient as TSC

tableau_auth = TSC.TableauAuth("USERNAME", "this&that")
server = TSC.Server("HOST", use_server_version=True)
server.add_http_options({"verify": False})

with server.auth.sign_in(tableau_auth):
    s_info = server.server_info.get()
    print("Logged in to server:")
    print("\tProduct version: {0}".format(s_info.product_version))
    print("\tREST API version: {0}".format(s_info.rest_api_version))
    print("\tBuild number: {0}".format(s_info.build_number))
````

Result: the login worked just fine. In this case it looks like TSC is doing the proper handling of encoding the password before sending over the wire. However there might be other cases where it's not. Any examples of that would be helpful.

**Comment by jacalata** [comment]
Stephen Price's example password that failed was z0^EF91Mxp&uhEzV
He tested adding &amp; to replace the "&" in the password and it worked as expected "200 OK"
,  &#38; also worked

**Comment by bcantoni** [comment]
Ah yes, now I'm caught back up on the original internal Slack thread.

So I've tested with that more complex password as well and it works in my simple TSC login example above, and also works when I use the sample login.py script:

````
python login.py --server "HOST" --username "zztest" --password "z0^EF91Mxp&uhEzV"

Signing in...
Server: HOST
Site: None
Username: zztest
Logged in successfully
ServerInfoItem: [product version: 2022.1.3, build no.:20221.22.0616.1738, REST API version:3.15]
````

Maybe the difference is the Tableau Server version or on-prem vs cloud or something.

**Comment by jacalata** [comment]
These passwords should work successfully, we did do some testing for tabcmd for OS-special characters and added this documentation: https://github.com/tableau/tabcmd/pull/228

I don't think you should need to do anything specific when working with tsc, just enter the password in plain text. If there are any examples where the user needs to do something more than that, we should document it.
