### ISSUE TITLE
Unable to install - `tableauserverclient` library with python 3.10 version.

### ISSUE THREAD

**Issue by srajulapati** [tableau/server-client-python#1069]
Hi Team,

We were working on a  linux machine. Earlier, it was **python 3.9** and recently it was updated to **python 3.10**.

My python script is working fine on the 3.9 version but we are facing the below issue in the updated 3.10 version.

- I have imported `tableauserverclien` python library in my python script as below.

   - import tableauserverclient as TSC

if i try to execute the script as python3 script.py i am getting the below error and attached the screen short for your reference.
Error :

- import tableauserverclient as TSC ModuleNotFoundError: No module named 'tableauserverclient'

To install the tableauserverclient module, i have used the below command.

- pip install tableauserverclient, 

here i am getting the errors and attached the error screen short for your references.

**Error Screen Shots** :
![Error 1](https://user-images.githubusercontent.com/109216117/178753246-bce11810-7ae7-4b42-bb8f-bfd5c5d44497.png)
![Error 2](https://user-images.githubusercontent.com/109216117/178753237-4c8c287d-d56c-4f47-a019-8cf9b16a55ff.png)
![Error 3](https://user-images.githubusercontent.com/109216117/178753231-30e2a3f3-3692-471d-8b17-e3f44e789694.png)

**Comment by jorwoods** [comment]
@srajulapati Are you certain that `pip` is installing in your python3 environment and not a python 2 environment? What does `pip -V` return?

Can we try a fresh virtual environment and see what happens?


```bash
python3 -m venv .venv
source .venv/scripts/activate
where python3
python3 -m pip install --upgrade pip wheel
python3 -m pip install tableauserverclient
```

**Comment by jorwoods** [comment]
In your screenshots, you did not create or activate the virtual environment.

**Comment by jorwoods** [comment]
Tried it in a fresh 3.10 container and it installs just fine in my environment.

![image](https://user-images.githubusercontent.com/13803242/179337202-1dc97c37-7b69-457f-a010-561e48c4fece.png)

**Comment by srajulapati** [comment]
Hi @jorwoods,

I have followed your suggestion, and it's sucessfully installed tableauserverclient library.
Thanks for your support.
