### ISSUE TITLE
Fetch and print datasources from a project is not working

### ISSUE THREAD

**Issue by bheem123** [tableau/server-client-python#1071]
I am trying to print (download eventually) thousands of datasources from a project, but it is not fetching. However, the code is working for workbooks.

Environment:
 - Tableau Server version : 2021.4.3
 - Python version: 3.10
 - TSC library version: latest

Here is my code:

````
with server.auth.sign_in(tableau_auth): 
        all_projects = TSC.Pager(server.projects)
        request_option = TSC.RequestOptions(pagesize=1000)
        request_option.filter.add(TSC.Filter(TSC.RequestOptions.Field.ProjectName, TSC.RequestOptions.Operator.Equals, args.project))
        all_datasources, pagination_item = server.datasources.get(request_option)
        all_workbooks, pagination_item = server.workbooks.get(request_option)

       #following block is not working
        for datasource in all_datasources:
            print(datasource.id)
            #download DS
            print("\nDownloaded the file to {0}.".format(file_path))

       #following block is working
        for workbook in all_workbooks:
            print(workbook.id)
            #download WB
            print("\nDownloaded the file to {0}.".format(file_path))
````

Errors:
None

**Comment by jorwoods** [comment]
Project name is not a valid filter for datasources. https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_filtering_and_sorting.htm

**Comment by bheem123** [comment]
How is it working for workbooks then? I don't see the project name as a filter for workbooks either in the link you shared. Prior to 2021 version of Tableau, my scripts used to work.

**Comment by jorwoods** [comment]
I guess then that the workbooks documentation is wrong in missing the project filter.

While passing the filter down to the Server would be the ideal way to get your filtered results, you can always filter manually.

(Additionally, the code that you used in your example would not necessarily fetch ALL results, just the first 1000)

Something like this:

```python
project = server.projects.filter(name="My Project")
# Use a generator expression to be able to loop over datasources
all_datasources = (ds for ds in server.datasources.all() if ds.project_id == project.id)

for datasource in all_datasources:
    print(datasource.id)
```

**Comment by bheem123** [comment]
Hmm.. that did not work either.

all_datasources = (ds for ds in server.datasources.all() if ds.project_id == project.id)
AttributeError: 'QuerySet' object has no attribute 'id'

**Comment by jorwoods** [comment]
Oops. It should be

```python
project = server.projects.filter(name=“My project”)[0]
```

**Comment by bheem123** [comment]
That worked. Thanks jorwoods.
