### ISSUE TITLE
Not able to use the "ParentProjectId" in filter request option from TSC python module

### ISSUE THREAD

**Issue by sumanta92** [tableau/server-client-python#1089]
I am trying to filter the project folder content based on the "ParentProjectId" but I am getting error as "400065: Bad Request The filter query contains a key which is not recognized for this api version".
I am using Tableau Server version 2021.4.8

**Comment by jacalata** [comment]
It's not quite clear to me what you're trying to do here - the parent project id only applies to projects, if you are trying to find e.g workbooks that are in a specific folder, you would need to query workbooks using the filter key "project.id". 
For more info on which filters can be used for each method, see https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_fields.htm
