### ISSUE TITLE
Error establishing connection to datasource, multiple connections

### ISSUE THREAD

**Issue by Rohit2101991TU** [tableau/server-client-python#1095]
**Describe the bug**
I am trying to publish a workbook connected to a Published Datasource which has multiple connections(specifically 3 set of credentials) . But its giving an error saying that it cannot establish a connection to datasource .Do I repeat the workbook connectionItem object associated to the Published datasource thrice , one per each set of creds , before passing it to publish_workbook function ? Any help will be really appreciated 

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online)
 - Python version
 - TSC library version

**To Reproduce**
Steps to reproduce the behavior. Please include a code snippet where possible.

**Results**
What are the results or error messages received?

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by bcantoni** [comment]
@Rohit2101991TU I simplified your issue title a bit and moved that text description into the issue description.

Could you also include the other items requested in the template, for example Tableau/TSC versions and sample code snippet? Those would help people who may be able to help you investigate this one.

**Comment by jacalata** [comment]
@Rohit2101991TU  - can you confirm that publishing the workbook succeeds if you upload it through the website, or publish it some other way? I want to rule out any problems with the connection credentials, etc.

**Comment by jacalata** [comment]
I assume you are blocked on the Method Not Allowed error here, but the general answer is that yes, you need to publish with info for all three connections.

**Comment by Rohit2101991TU** [comment]
No , I am not blocked on 405 method not allowed error . And I am getting "failed to establish connection to your datasource" while publishing the workbook  because the datasource attached to the workbook has multiple database connections within it
