### ISSUE TITLE
Update_connection method fails with 405 error 

### ISSUE THREAD

**Issue by Rohit2101991TU** [tableau/server-client-python#1096]
**Describe the bug**
We are trying to update connections of a workbook using update_connection method but it fails 

Command ---> server.workbooks.update_connection(workbook_item=workbook,connection_item=m_list[0])

where m_list = workbook.connections   ,  and the workbook just has one embedded datasource with a single connection

Below is the code snippet

workbook = server.workbooks.get_by_id('31193efb-6b65-435a-956d-f07adb74125c')

server.workbooks.populate_connections(workbook)

Below is connectionItem object returned by populate_connections method

>>> pprint(vars(workbook.connections[0]))
{'_connection_type': 'genericodbc',
 '_datasource_id': 'f6f5efc0-6a8c-4ab2-920e-37ad157eca70',
 '_datasource_name': 'DS_NAME',
 '_id': '6ffe8054-d0be-4bb9-b694-30119e675de8',
 'connection_credentials': None,
 'embed_password': True,
 'password': None,
 'server_address': '',
 'server_port': None,
 'username': 'username'}

m_list=[]

m_list=workbook.connections

m_list[0].username ="new_username"
m_list[0].password = "new_password"
m_list[0].connectioncredentials=("new_username", "new_password" , True)

server.workbooks.update_connection(workbook_item=workbook,connection_item=m_list[0])

It gives following error

tableauserverclient.server.endpoint.exceptions.NonXMLResponseError: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>405 Method Not Allowed</title>\n</head><body>\n<h1>Method Not Allowed</h1>\n<p>The requested method PUT is not allowed for this URL.</p>\n</body></html>\n'
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

NOTE : 1) The username with which we are logging into tableau server here is has site role as "Server Administer Explorer".
Does that matter?

**Versions**
Details of your environment, including:
 - Tableau Server version - 2021.4
 - Python version - 3.6
 - TSC library version - 3.14

**To Reproduce**
Pasted code above

**Results**
tableauserverclient.server.endpoint.exceptions.NonXMLResponseError: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>405 Method Not Allowed</title>\n</head><body>\n<h1>Method Not Allowed</h1>\n<p>The requested method PUT is not allowed for this URL.</p>\n</body></html>\n'

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by Rohit2101991TU** [comment]
Just to add I am getting same  error "tableauserverclient.server.endpoint.exceptions.NonXMLResponseError: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>405 Method Not Allowed</title>\n</head><body>\n<h1>Method Not Allowed</h1>\n<p>The requested method PUT is not allowed for this URL.</p>\n</body></html>\n'
"       when trying to execute update_workbook(updated_workbook_item)

**Comment by Rohit2101991TU** [comment]
Hi , Does anyone have suggestions for above error? Any help will be greatly appreciated . Is there any way "PUT" Api calls can be enabled to update datasources/workbooks/connections?

**Comment by jacalata** [comment]
Hi Rohit, the PUT call should work - I haven't had time to look at this deeply, but nothing jumps out at me. 

Are you able to try running the workbook sample code we have, and let me know if that works for you? https://github.com/tableau/server-client-python/blob/master/samples/explore_workbook.py

**Comment by Rohit2101991TU** [comment]
Hi jacalata , None of the update functions( API calls which have PUT in them) are working and they throw "method not allowed error" . I tried to just update a description for a workbook and even it gave me the same error. Are we supposed to do some setting at Tableau server level to allow PUT requests .

Note : POST and GET requets are working fine

**Comment by Rohit2101991TU** [comment]
Also, I tried  https://github.com/tableau/server-client-python/blob/master/samples/explore_workbook.py 
with just one change in it .  I added  a line of code --->server.add_http_options({'verify': False})   . It gave me the same error for update_workbook which we have been since the start
. @jacalata  Do you think adding server.add_http_options({'verify': False})  affects the code?

tableauserverclient.server.endpoint.exceptions.NonXMLResponseError: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>405 Method Not Allowed</title>\n</head><body>\n<h1>Method Not Allowed</h1>\n<p>The requested method PUT is not allowed for this URL.</p>\n</body></html>\n'

**Comment by Rohit2101991TU** [comment]
hi , does anyone have any insight in above issue . Any help will be appreciated

**Comment by jacalata** [comment]
Hi Rohit, sorry I forgot about this issue.

server.add_http_options({'verify': False}) will only change whether you need a valid SSL certificate. If you are using that, then it sounds like you are using a server that expects a https URL. One possible cause for this Method Not Allowed error is if you are using a http URL, and the server redirects you to https. This will cause your request to be changed to a GET instead of PUT, which will cause the Method Not Allowed error you are seeing. 

Does that sound like it might be what's happening here?

**Comment by Rohit2101991TU** [comment]
Sorry I didnt get you @jacalata  . Can you please suggest any solution which could work? I get ab error if I remove line server.add_http_options({'verify': False}) from the code

**Comment by Rohit2101991TU** [comment]
Hi , Does anyone have any idea how to solve above method not allowed error? Do i need to add anything in the code or need to change Tableau server configuration

**Comment by jacalata** [comment]
Are you attempting to connect to a server using an address like "http://myserver.com" or just "myserver.com"? Have you tried an address that starts with **https** instead?

**Comment by Rohit2101991TU** [comment]
Hi @jacalata I am using "https://myserver.com/" and it still gives same error

**Comment by Rohit2101991TU** [comment]
Hi , @jacalata  Do you think there is someone incorrect/ needs to be changed in Tableau server config settings to allow PUT method?

**Comment by Rohit2101991TU** [comment]
Hi , @jacalata Do you think there is someone incorrect/ needs to be changed in Tableau server config settings to allow PUT method?

**Comment by jacalata** [comment]
I don't think there's any way Tableau Server could be configured to do this. I think you need to look at your network setup, like any proxies, firewalls etc between you and the Tableau Server. If you can use Postman (https://www.postman.com/) to send the requests, then there might be more information in the response headers or something like that.
