### ISSUE TITLE
question - info on ViewItem.populate_csv generator dialect/format

### ISSUE THREAD

**Issue by John-Miller12** [tableau/server-client-python#1110]
I am seeking more detail on what is being yielded by the generator in `view.csv` attribute, and understand why 
```python
with tempfile.TemporaryFile() as file:
    for chunk in view.csv:
        file.write(chunk)
    file.seek(0)
    df = pd.read_csv(file)
```
works, while
```python
pd.DataFrame(view.csv)
```
mangles the data, reading a chunk per row.

I cannot find documentation online for this data type/dialect, and there is no detail on it in either TSC nor tableau REST API documentation. 

Can you please link documentation on this convention or explain? It may also be valuable to include this in the TSC documentation on the method.

**Comment by jorwoods** [comment]
If passing an iterable directly into a `pd.DataFrame()` call, it expects each iteration to produce a row. The generator for the view does not return one row per loop, but instead returns 1024 `bytes`. If you want to read it directly into a DataFrame without using a temp file, you would still have to use something like a `BytesIO` buffer.

**Comment by John-Miller12** [comment]
Thanks, that is enough direction to get started. I'll look into it.

**Comment by jorwoods** [comment]
Come to think of it, you wouldn't even necessarily need to use `BytesIO`. Could probably just pass this in:

```python
df = pd.read_csv(b"".join(chunk for chunk in view.csv))
```

**Comment by John-Miller12** [comment]
`read_csv` takes a filepath or buffer, so the b string join alone didn't work, but `BytesIO(b"".join(x for x in view.csv))` did work.

this is my first time working with bytes data, so your responses have been very useful to me.
