### ISSUE TITLE
AttributeError: module 'tableauserverclient' has no attribute 'ExcelRequestOptions'

### ISSUE THREAD

**Issue by jtsai01-bsc** [tableau/server-client-python#1122]
**Describe the bug**
AttributeError: module 'tableauserverclient' has no attribute 'ExcelRequestOptions'

**Versions**
Details of your environment, including:
 - Tableau Server version 2022.1.6
 - Python version v.3.9
 - TSC library version 0.20

**To Reproduce**
python C:\Users\jxxxx01\Downloads\Tableau\Tidal\server-client-python-master\samples\export.v.1.0.py -s http://tabxxxx.mybsc.com --site "" -u svcUser --xlsx -f “C:\Users\jxxxx01\Downloads\Tableau\Installation_and_Billing\LEP-python.xlsx” 8834ac6b-xxxx-xxxx-xxxx-xxxx

**Results**
Signing in...
Server: http://tabxxxx.mybsc.com
Site:
Username: svcUser
Connected
Item found: Group Calpers LEP Dashboard
Traceback (most recent call last):
  File "C:\Users\jxxxx01\Downloads\Tableau\Tidal\server-client-python-master\samples\export.v.1.0.py", line 127, in <module>
    main()
  File "C:\Users\jxxxx01\Downloads\Tableau\Tidal\server-client-python-master\samples\export.v.1.0.py", line 105, in main
    option_factory = getattr(TSC, option_factory_name)
AttributeError: module 'tableauserverclient' has no attribute 'ExcelRequestOptions'

**Comment by bcantoni** [comment]
@jtsai01-bsc could you show the code in your export.v.1.0.py script that's failing? The library version of [export.py](https://github.com/tableau/server-client-python/blob/master/samples/export.py) doesn't include an Excel option, so I'm assuming you've added that.

**Comment by bcantoni** [comment]
Did a little more digging here. Support for `populate_excel` for views was added in #968. It looks like it's not fully functional because `ExcelRequestOptions` isn't included in the proper init places:

````py
$ python
Python 3.9.7 (default, Aug 31 2021, 14:25:50)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tableauserverclient as TSC
>>> TSC.CSVRequestOptions
<class 'tableauserverclient.server.request_options.CSVRequestOptions'>
>>> TSC.ExcelRequestOptions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tableauserverclient' has no attribute 'ExcelRequestOptions'
````

@jorwoods would you mind taking a look at this? I notice the test you added also had a [copy/paste error](https://github.com/tableau/server-client-python/blob/master/test/test_view.py#L297) where it was still referencing the CSV request options, so that's probably why this was missed.

**Comment by jtsai01-bsc** [comment]
> Did a little more digging here. Support for `populate_excel` for views was added in #968. It looks like it's not fully functional because `ExcelRequestOptions` isn't included in the proper init places:
> 
> ```python
> $ python
> Python 3.9.7 (default, Aug 31 2021, 14:25:50)
> [Clang 12.0.0 (clang-1200.0.32.21)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import tableauserverclient as TSC
> >>> TSC.CSVRequestOptions
> <class 'tableauserverclient.server.request_options.CSVRequestOptions'>
> >>> TSC.ExcelRequestOptions
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'tableauserverclient' has no attribute 'ExcelRequestOptions'
> ```
> 
> @jorwoods would you mind taking a look at this? I notice the test you added also had a [copy/paste error](https://github.com/tableau/server-client-python/blob/master/test/test_view.py#L297) where it was still referencing the CSV request options, so that's probably why this was missed.

Thank you, Brian and Jorwoods!

Please let me know when i can download the new version of TSC library and try the ExcelRequestOptions.

**Comment by jorwoods** [comment]
@jtsai01-bsc Technically, you can use it now if you import it directly, manually.

```python
from tableauserverclient.server.request_options import ExcelRequestOptions
```

**Comment by jtsai01-bsc** [comment]
> ```python
> TSC.ExcelRequestOptions
> ```

Sorry, Jorwoods.  Can you please add more detail and step.
I add this to export.py; however i am getting the same error.
####
# This script demonstrates how to export a view using the Tableau
# Server Client.
#
# To run the script, you must have installed Python 3.7 or later.
####

import argparse
import logging

import tableauserverclient as TSC
from tableauserverclient.server.request_options import ExcelRequestOptions

**Comment by jorwoods** [comment]
Nevermind. I forgot it was an internal reference error and not that you were trying to access it, but couldn't.

**Comment by jorwoods** [comment]
0.23 was released that contains the fix.

**Comment by jtsai01-bsc** [comment]
Awesome.  Thank you so much!  I will wait for v.0.23.
