### ISSUE TITLE
How to check user's activity and the CPU and Memory usage of each activity on Tableau Server

### ISSUE THREAD

**Issue by wilfred303030** [tableau/server-client-python#1131]
How to use Python to check user's activity and the CPU and Memory usage of each activity on Tableau Server? 
I have searched many pages and have no idea how to do this.

**Comment by jacalata** [comment]
I'm afraid this library is for managing the content within Tableau Server, not the machine running it. I don't know about python, but there are a number of tools mentioned here to help with hardware monitoring - https://help.tableau.com/current/blueprint/en-us/bp_hardware_monitoring.htm.

**Comment by wilfred303030** [comment]
Oh. thanks for your reply about this library. I will think about other methods. Appreciate!
