### ISSUE TITLE
[Type1] [QueryTagging for Connections]

### ISSUE THREAD

**Issue by AndreasTer** [tableau/server-client-python#1138]
## Summary
Enable querytagging for datasource connections.

## Description
ConnectionItem class is missing the querytaggingenabled attribute. Rest API already has the functionality to update it. https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_data_sources.htm#update_data_source_connection

**Comment by jacalata** [comment]
This has been added - https://github.com/tableau/server-client-python/blob/e4fbe41560fbd2314c9c7b8b8a169164dd15185f/tableauserverclient/models/connection_item.py#L41
