### ISSUE TITLE
Unable to fetch the frequency (weekday - interval) details of schedules 

### ISSUE THREAD

**Issue by JayavarshiniJJ** [tableau/server-client-python#1140]
1. For a schedule with **Daily/Hourly frequency** --unable to get the details - 
     a) on which weekdays it is scheduled to run

2. For a schedule with **Monthly frequency** --unable to get the details of- 
     a) what days of the month will it run - (_if more than 1 day is chosen_-while creating)
     b) last day details 
     - if last day of month (_if day is chosen and last is selected_ -while creating) 
     - last (any) weekday of the month (_if last is chosen and a weekday is selected_ -while creating) 

**Versions**
 - Tableau Server version - 3.15 
 - Python version - 3.9.12 

I've added the documentation containing the exact issues in detail for reference.
Any help would be appreciated.
[problem querying frequency details of schedules.docx](https://github.com/tableau/server-client-python/files/9931648/problem.querying.frequency.details.of.schedules.docx)

**Comment by useready-andyv** [comment]
hi Jayavarshini,  I see the same issue on the REST API
POST Request:   https://{{server}}/api/{{api}}/schedules/{{scheduleId}}

The response I get for a daily schedule is as follows: 

```
<?xml version='1.0' encoding='UTF-8'?>
<tsResponse xmlns="http://tableau.com/api" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tableau.com/api https://help.tableau.com/samples/en-us/rest_api/ts-api_3_15.xsd">
    <schedule id="4dd3b3a3-8f42-4d19-a411-c82b254ab25a" name="Run Flow - Every night - 11:00PM" state="Active" priority="50" createdAt="2022-10-13T10:02:21Z" updatedAt="2022-11-03T18:05:04Z" type="Flow" frequency="Daily" nextRunAt="2022-11-03T23:00:00Z" executionOrder="Parallel">
        <frequencyDetails start="23:00:00"/>
    </schedule>
</tsResponse>
```
This specific daily flow is not enabled to run Fri and Sat (as this runs at 11 PM)
Don't see a way to get the details via GrapQL either. 

API Team, are we doing something wrong here?

**Comment by jacalata** [comment]
I think this is a gap in the info returned from the server, and will require internal fixes.
