### ISSUE TITLE
version 0.23.1 not available

### ISSUE THREAD

**Issue by TrimPeachu** [tableau/server-client-python#1141]
**Describe the bug**
Despite its release almost a month ago, I am unable to pip install the 0.23.1 version.

**To Reproduce**
[PyPI](https://pypi.org/project/tableauserverclient/)

**Comment by jacalata** [comment]
This was an oversight, sorry. I'll get it up by the end of the week.

**Comment by DrMaphuse** [comment]
It seems like v0.23.1 and v0.23.2 are still not available?
```
ERROR: Could not find a version that satisfies the requirement tableauserverclient==v0.23.2 (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.5, 0.5.1, 0.6, 0.6.1, 0.6.3, 0.7, 0.8, 0.8.1, 0.9, 0.9.31.post0.dev1, 0.10, 0.11, 0.12, 0.13, 0.14.0, 0.14.1, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.21.post0.dev4, 0.22, 0.23)
ERROR: No matching distribution found for tableauserverclient==v0.23.2
```

**Comment by thesuperzapper** [comment]
@jacalata do you have an update on when `0.23.1` will be pushed to PyPi, as it currently only has [`0.23`](https://pypi.org/project/tableauserverclient/#history) (which is also missing the final `.X`)?

**Comment by bcantoni** [comment]
@thesuperzapper @DrMaphuse @TrimPeachu thanks for your patience - we had some issues with the publishing flow, but it's fixed now. You should be able to install v0.23.4 from PyPI: https://pypi.org/project/tableauserverclient/
