### ISSUE TITLE
mypy update

### ISSUE THREAD

**Issue by jacalata** [tableau/server-client-python#1143]
**Describe the bug**
a mypy update has changed their defaults and we need to update the code to match

Run mypy --show-error-codes --disable-error-code misc --disable-error-code import tableauserverclient test
##[debug]/usr/bin/bash -e /home/runner/work/_temp/a3351e84-6b1d-47fb-801e-82f612a2819f.sh
tableauserverclient/server/endpoint/exceptions.py:36: error: Incompatible default for argument "request_url" (default has type "None", argument has type "str")  [assignment]
tableauserverclient/server/endpoint/exceptions.py:36: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
tableauserverclient/server/endpoint/exceptions.py:36: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
tableauserverclient/models/revision_item.py:13: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]

**Comment by bcantoni** [comment]
In a recent PR I had to force mypy to use its previous behavior:
https://github.com/tableau/server-client-python/pull/1158/commits/a42515162f16c84b58f99c05f2f0d6eb484f7dfc

We can leave this issue open to cover fixing it the right way if we want.

**Comment by nosnilmot** [comment]
This was addressed in 0bb9dd5d2bdaf4adbca9427deb26c9469e961d9b
