### ISSUE TITLE
Unable to get the Flow subscription output details from server.

### ISSUE THREAD

**Issue by JayavarshiniJJ** [tableau/server-client-python#1149]
While creating a Flow subscription on the cloud, the payload request involves some additional details like
1. includeOutputData
2. outputId
3. includeLinkToOutputData
4. showRowsInEmailBody
5. attachOutputData
6. attachedOutputDataFormat

But I am unable to get these metrics from the server to enter into the payload request.
The response I received from the **getsubscription** on the server doesn't have these specific output details.

**Versions**

Tableau Server version - 3.15
Python version - 3.9.12

I've added the documentation containing the request payload for cloud to create subscription and response payload from server.
Any help would be appreciated.
[Payload(request and response).docx](https://github.com/tableau/server-client-python/files/10162933/Payload.request.and.response.docx)

**Comment by jacalata** [comment]
It looks like you're trying to use an internal Web API, which is not written to be compatible with the public REST APIs.

**Comment by bcantoni** [comment]
Closing as not related to the TSC library and not a publicly supported API.
