### ISSUE TITLE
Schedules.update is missing details and sample code

### ISSUE THREAD

**Issue by shafiq-telus** [tableau/server-client-python#1152]
Hi there, trying to use schedule.update action for "Tableau Server Client (Python)" API but can't find details or sample of using this method - it has the incorrect sample code reference schedule.create() method instead.

[https://tableau.github.io/server-client-python/docs/api-ref#schedulesupdate]

I need to use "state" attribute to programatically suspend or activate an schedule using REST API for DR readiness of our servers.

Looking for help here please
**Describe the bug**

**Versions**
Details of your environment, including:
 - Tableau Server version - Tableau Server 2021.2
 - Python version - 3.11.1
 - TSC library version - latest

**Comment by bcantoni** [comment]
For reference, the missing Schedules docs in general is covered by #755, but in the meantime we can look into the request here.

**Comment by shafiq-telus** [comment]
Looking forward to it.

**Comment by bcantoni** [comment]
@shafiq-telus for you specific question about finding and changing the `state` attribute of a schedule, here's an example snippet that should help. The first case is usable if you already have the schedule ID and the second case can loop through all of them. 

```py
with server.auth.sign_in(tableau_auth):
    # find specific schedule if already have the ID
    sc1 = server.schedules.get_by_id('e998cecc-1f68-43d0-87f7-941dd79509c8')
    print(sc1.name)

    # loop through all schedules to find the target one
    for sch in TSC.Pager(server.schedules):
        print(sch)
        if sch.name == 'Weekly-Schedule':
            if sch.state == 'Active':
                sch.state = 'Suspended'
            else:
                sch.state = 'Active'
            server.schedules.update(sch)
            print("flipped schedule to {}".format(sch.state))
```

I'm also putting together a doc update to fill in some more of the missing pieces here.

**Comment by shafiq-telus** [comment]
you are amazing @bcantoni - this is working like charm :) great job and thanks for quick help.
