### ISSUE TITLE
ExcelRequestOptions doesn't filter

### ISSUE THREAD

**Issue by alessandro-deprato** [tableau/server-client-python#1153]
Hello,

Filtering CSV populated views works fine, example:

```python
query_filter = TSC.CSVRequestOptions()
query_filter.vf("my_key", "my_value")
summary_view_id = "my_id"
summary_view = server.views.get_by_id(summary_view_id)
server.views.populate_csv(summary_view,query_filter)
```

Now if I want to work directly with excel and I'll do the the following:

```python
query_filter = TSC.ExcelRequestOptions()
query_filter.apply_query_params({"my_key": "my_value"})
summary_view_id = "my_id"
summary_view = server.views.get_by_id(summary_view_id)
server.views.populate_excel(summary_view,query_filter)
```

I get the full view without the filtering applied.
I cannot find much around ExcelRequestOptions so I might be doing this in the wrong way.
Appreciate any help!

Thank you,
Alessandro

**Comment by bcantoni** [comment]
For reference, we have an existing issue #1128 to cover getting those Excel options fully documented.

**Comment by alessandro-deprato** [comment]
Just FYI, while looking at PR #1164 and trying any possible way to get that working I eventually ended up here:

https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooks_and_views.htm

and found that the option filter-value is not available for the "/api/api-version/sites/site-id/views/view-id/crosstab/excel".
Looks like there is no way to filter when exporting to Excel :-(
