### ISSUE TITLE
project_item.py needs properties for data role and metric permissions

### ISSUE THREAD

**Issue by will-hopkins-panther** [tableau/server-client-python#1155]
**Describe the bug**
project_item.py has no properties for data role and metric permissions. Attempting to read or set these permissions produces an error that ProjectItem does not have the required attribute.

I have a PR drafted to fix this, and will send it as soon as my company executes the CLA.

**Versions**
- TSC 0.23.2 (built from source)
- Tableau Online

**To Reproduce**
Write a script using the TSC library that attempts to read or set permissions for data role and metric. Unfortunately, I can't share my example script.

**Results**
`AttributeError: 'ProjectItem' object has no attribute 'default_datarole_permissions'. Did you mean: '_default_datarole_permissions'?`

**Comment by bcantoni** [comment]
Thanks @will-hopkins-panther - we have a handful of [permissions-related issues](https://github.com/tableau/server-client-python/issues?q=is%3Aissue+is%3Aopen+permissions+) still open. If you contribute a fix here we can help get it tested and included.

**Comment by jacalata** [comment]
This should be fixed by https://github.com/tableau/server-client-python/pull/1163
