### ISSUE TITLE
Publish the latest version 0.23.1 to PyPI

### ISSUE THREAD

**Issue by tanng1999** [tableau/server-client-python#1157]
Currently, only version 0.23 is published to PyPi.

Can the Tableau team publish Tableau's server-client-python version 0.23.1 to PyPi?  Thanks.

**Comment by bcantoni** [comment]
@tanng1999 we had some issues with the publishing flow, but it's fixed now. You should be able to install v0.23.4 from PyPI now: https://pypi.org/project/tableauserverclient/
