### ISSUE TITLE
Proposal: Register XML Namespace globally

### ISSUE THREAD

**Issue by t8y8** [tableau/server-client-python#116]
Currently, the SCL has a namespace.py file that imports a dictionary that we pass into every single xml query we make.

Python 2.7 and 3.2+ have a function called `register_namespace` that I *think* we can use to register once (at import time?) and then clean up all those calls around the library.

Link: https://docs.python.org/3.6/library/xml.etree.elementtree.html#xml.etree.ElementTree.register_namespace

It also makes it less likely that someone forgets or typos the namespace dictionary.

Note: I have NOT tested this yet, but I will!

**Comment by LGraber** [comment]
Looks like the doc says new in 3.2. It was in 2.7, too?

**Comment by t8y8** [comment]
Yeah, if you look @ 2.7 version of the docs it was added for the 2.x line as well (the docs are branched)

**Comment by t8y8** [comment]
Oh, it looks like this might ONLY be for reading/writing the tree, and not for use in find/findall :( investigating further...

**Comment by t8y8** [comment]
Ok, confirmed, that's only for serialization. Find/findall need the parameter passed in.

Sad.

Source: http://stackoverflow.com/questions/14853243/parsing-xml-with-namespace-in-python-via-elementtree
