### ISSUE TITLE
PaginationItem Usage

### ISSUE THREAD

**Issue by tanng1999** [tableau/server-client-python#1169]
**Describe the bug**
Unable to get a full list of Tableau sites when using the server.sits.get() method.

Using the sample code to get all the Tableau sites:
`    with tableau_server.auth.sign_in(tableau_auth):
        all_sites, pagination_item = tableau_server.sites.get()
        # print all the site names and ids
        for site in all_sites:
            print(f"*********site_name={site.name}, site_id={site.id}, site_url={site.content_url}")
        return all_sites`

Notice that some Tableau sites are not returned using the above API code when compared against the Tableau web app.

**Versions**
 - TSC library version - latest Tableau server-client-python version
 - Python - 3.9.12

The sample code does not use the PaginationItem object.  How is PaginationItem being use in the code?  Thanks.

**Comment by jorwoods** [comment]
The `.get` method by default only returns the first 100 items. The PaginationItem contains information about what page number you are on, the page size, and the total available. However, a better practice would be to used `TSC.Pager` to handle consuming the PaginationItem and progressing to the next page of results automatically.

**Comment by eschranz** [comment]
I'm also seeing issues using the `.get()` method for single specific resources that was working properly until yesterday. Was anything changed on the REST side recently?

**Comment by tanng1999** [comment]
@jorwoods Thanks for the info.  I'm able to use the TSC.Pager() method.

`for site in TSC.Pager(server.sites):
    print(site.id)
`
