### ISSUE TITLE
Unable to publish DataSource due to Coudflare checks

### ISSUE THREAD

**Issue by gianpy15** [tableau/server-client-python#1174]
**Describe the bug**
I'm trying to upload a parquet data source to Tableau Server using the server client python API but I get an error message because the server cannot review the connection's security. 

**Versions**
Details of your environment, including:
 - Tableau Server version: 2021.4.3 (20214.22.0108.1039) 64-bit Linux
 - Python version: 3.10 (also tried 3.8)
 - TSC library version: 0.23.4

**To Reproduce**
Code to reproduce the error:
```python
import pandas as pd
import tableauserverclient as TSC
from pathlib import Path

tableau_auth = TSC.TableauAuth('<USERNAME>', '<PASSWORD>', '')
server = TSC.Server('<SERVER>')

OUTPUT_PATH = Path("./output")
OUTPUT_PARQUET = OUTPUT_PATH / "test_data.parquet"
PROJECT_ID = "<PROJECT_ID>"

data = pd.DataFrame({
    "col1": [0,1,2] * 10,
    "col2": [5] * 30
})

data.to_parquet(OUTPUT_PARQUET)

new_datasource = TSC.DatasourceItem(PROJECT_ID)

with server.auth.sign_in(tableau_auth):
    new_datasource = server.datasources.publish(new_datasource, OUTPUT_PARQUET, 'CreateNew') 
```

**Results**

I get the following error:
![image](https://user-images.githubusercontent.com/26765244/212309197-87ed0df6-e4bf-465a-9eb0-46be4f5cfed8.png)

**Comment by jacalata** [comment]
Cloudflare is a proxy that must have been set up by your server admin/IT department. You will have to talk to them about how you can use automation through it.

**Comment by jacalata** [comment]
Cloudflare is a proxy that must have been set up by your server admin/IT department. You will have to talk to them about how you can use automation through it.

**Comment by jacalata** [comment]
Closing as there isn't really anything we can do to help here.
