### ISSUE TITLE
Some revision properties not populating

### ISSUE THREAD

**Issue by jharris126** [tableau/server-client-python#1175]
**Describe the bug**
Key revision properties (`current` and `created_at`) of the `RevisionItem` are not populating or populating with default values.

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online): **Tableau Server 2022.3**
 - Python version: **3.9**
 - TSC library version: **0.23.4**

**To Reproduce**
```python
wb = server.workbooks.get_by_id('90c3056a-eee6-4120-b1cd-194d8ba7dcb2')

server.workbooks.populate_revisions(wb)
wb_last_revision_tsc = wb.revisions[0]
print(
    wb_last_revision_tsc.revision_number,
    wb_last_revision_tsc.current,
    wb_last_revision_tsc.created_at
)

url = f'{server.baseurl}/sites/{server.site_id}/workbooks/{wb.id}/revisions'
revisions = requests.get(url, headers=request_headers).json()['revisions']

wb_last_revision = [rev for rev in revisions['revision'] if rev['current']][0]
print(
    wb_last_revision['revisionNumber'],
    wb_last_revision['current'],
    wb_last_revision['publishedAt']
)
```

**Results**
```
44 False None
44 True 2021-10-28T16:11:34Z
```
`revision_number` and `current` properties of the `RevisionItem` object are populating with default values instead of correct values.

**Comment by jharris126** [comment]
https://github.com/tableau/server-client-python/blob/master/tableauserverclient/models/revision_item.py#L70-L72
It looks like the issue is the XML response using different item names than TSC is expecting.
`isCurrent` = `current`
`isDeleted` = `deleted`
`createdAt` = `publishedAt`

Not sure if this should be fixed in TSC or in the Tableau REST API itself because the expected values appear to match the Tableau REST API naming conventions more closely.

CC @jorwoods  since we are chatting about this is Slack right now

**Comment by jorwoods** [comment]
Thanks @jharris126! The official documentation does not match what is actually returned by the server endpoint. https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_revisions.htm#get_workbook_revisions

**Comment by jharris126** [comment]
https://github.com/tableau/server-client-python/blob/master/tableauserverclient/models/revision_item.py#L73
also need to be changed to `publisher` instead of `user`

**Comment by alexepperly** [comment]
I'm having this same issue.  Got a ton of "Nones" when trying to populate the same fields you're talking about.

**Comment by FritzJay** [comment]
When can we expect the fix for this to be published? I'm running into the same issue.

**Comment by jacalata** [comment]
fix is merged - should be published this week.

**Comment by alexepperly** [comment]
> fix is merged - should be published this week.

Thank you! Looking forward to it!
