### ISSUE TITLE
Suppress "InsecureRequestWarning" messages when disabling cert verification

### ISSUE THREAD

**Issue by Talvalin** [tableau/server-client-python#118]
If cert verification is disabled via use of `add_http_options({'verify': False})`, every REST API call will print a warning of the following form.

> C:\Program Files (x86)\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
>    InsecureRequestWarning)

Since I explicitly disabled cert verification, these warnings are not useful and should be suppressed.

The interwebz tell me that this can be achieved by using the following setting
`requests.packages.urllib3.disable_warnings(InsecureRequestWa‌​rning)`

**Comment by t8y8** [comment]
@Talvalin thanks for reporting this!

This is an interesting case -- the authors of `requests` are highly opinionated about the feature, as seen in discussion here: https://github.com/kennethreitz/requests/issues/2214

On the surface level, I agree that they're probably right from a security perspective. However, I also know that internally we have dozens of test servers using self-signed certificates and this just makes the barrier to experimenting with the SCL that much higher.

I need to ponder more on the best idea for this (and see what the rest of the team says)

**Comment by RussTheAerialist** [comment]
The add_http_options are passed unprocessed to requests.  I'm not sure I'm comfortable with overloading that to add additional behavior, and I'm absolutely in agreement with the requests maintainers on not suppressing the warning by default.

Not validating certificates is a security risk.  Not warning users that they are doing something risky from a security standpoint is not something I would feel comfortable adding to SCL.

Let's start by documenting it and providing some options beyond disabling certificate validation.  It's pretty easy to implement a properly signed certificate through letsencrypt (and it's free) so we should document that as an alternative also

**Comment by t8y8** [comment]
I'm alright with documenting how to disable the warning in your application (and maybe even some links to let's encrypt or something) -- the SCL will take no opinion on it and leave it up to the application code.

@Talvalin would you be up for drafting the docs and submitting a PR?

**Comment by Talvalin** [comment]
So the documentation would be a description of the workaround (`requests.packages.urllib3.disable_warnings(InsecureRequestWa‌​rning`), and a suggestion that customers should use properly signed certs, with a link to letsencrypt to help them out?

**Comment by t8y8** [comment]
I'm a little skeptical of just saying "Go get a certificate on let's encrypt" though. Maybe a listing of several free cert locations is fine, but, for example, I have no power to force a certificate on `qa-server` or `qa-far` and many of our customers will be in a similar boat. I am afraid of sounding patronizing. 

Maybe keep it simple...
```text
blah blah workaround
blah blah best practice is to use good certs
blah blah if you have access or the ability we recommend (letsencrypt, and a few others)
if not you may consider contacting the owner of the server and blah blah
```

:)

**Comment by Talvalin** [comment]
So typically, I saw this after I submitted my pull request. I'll update and resubmit in due course.

**Comment by Talvalin** [comment]
So far on the recommendations front, I've got Let's Encrypt, GlobalSign and SSL.com (based on the average reviews posted on SSL Shopper). Will that be sufficient?

**Comment by Talvalin** [comment]
development branch has been updated with the doc change that I made, so can we close this issue out now? :)
