### ISSUE TITLE
Datasource downloaded without extract cannot be re-published

### ISSUE THREAD

**Issue by arin7al** [tableau/server-client-python#1181]
Hello, I’m downloading an extract datasource with option include_extract=False (to save disk space). 
When re-publishing received file (.tdsx format) to a new location I get error “ServerResponseError:
        400011: Bad Request
               There was a problem publishing the file”

**Versions**
 - Tableau Server version is 2021.3
 - Python version is 3.9
 - TSC library version is 0.19

**To Reproduce**
server.datasources.download(datasource.id, filepath=datasource_path, include_extract=False)
 
server.datasources.publish(datasource, datasource_path, publish_mode, connection_credentials=conn_cred)

**Results**
“ServerResponseError:
        400011: Bad Request
               There was a problem publishing the file”

**Comment by arin7al** [comment]
When publishing it manually I get “Extract not found. What would you like to do?” window and it resolves the issue. 
Also if downloading with include_extract=True re-upload works but the file takes a lot of unnecessary space.

The current feature I’m doing should do backups and re-uploads all automatically and not keep the data snapshot.

Is this a known issue or maybe there is some workaround I can use?

**Comment by felipe-costa-compado** [comment]
Same problem here... I can't use the include_extract=True..it's too big.
I created the .tdsx  file (tds + hyper) and didn't work

**Comment by jacalata** [comment]
I think this is going to require a feature request on the server side. For background, what option do you use when you go through the manual fix?

**Comment by felipe-costa-compado** [comment]
> I think this is going to require a feature request on the server side. For background, what option do you use when you go through the manual fix?

It's only works if we download the .tdsx from tableau desktop..so I needed to create a datasource with few data, download the .tds and then use the tableau_tools to replace the extract in the .tdsx and then republish with all the data. 

If I simply create a .tdsx like tableau said in the documentation changing the .zip to .tdsx doesnt work..

**Comment by PradeepDoddarangaiah** [comment]
I'm facing the same issue while publishing .tdsx without extract. Was there any resolution on this?

**Comment by jacalata** [comment]
There are no current plans to add this feature on the server.
