### ISSUE TITLE
Discrepancy in response of REST API and Graph QL 

### ISSUE THREAD

**Issue by verdan** [tableau/server-client-python#1184]
**Describe the bug**
I have been trying to fetch all workbooks, under all projects via Rest API, and GraphQL both. but the response is different. GraphQL is returning incorrect response

**Versions**
Details of your environment, including:
 - Tableau Online
 - Python version: 3.10
 - TSC library version: 0.23.4

**To Reproduce**
I had a few workbooks under a project, which I moved to another project on Tableau. 
Now, when I try to fetch the workbooks using GraphQL, those workbooks are missing from the response. 
But if I try to get all workbooks from the REST API, those workbooks are available under that response. 

Below is my graph query which I am making using `metadata.paginated_query()`: 
```graphql
        query getAllWorkbooks($first: Int, $afterToken: String) {
            workbooksConnection(first: $first, after: $afterToken) {
                pageInfo{
                    hasNextPage
                    endCursor
                }
                nodes {
                    id
                    luid
                    name
                    projectName
                    projectVizportalUrlId
                    vizportalUrlId
                    createdAt
                    updatedAt
                    description
                    owner {
                        luid
                    }
                    dashboards {
                        id
                        luid
                        name
                        createdAt
                        updatedAt
                        index
                        path
                        sheets {
                            id
                        }
                    }
                    sheets {
                        id
                    }
                }
            }
        }
```

And this is how I am accessing Rest API:
```python
server.workbooks
```

**Results**
What are the results or error messages received?

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
Could you clarify, did this GraphQL query work before you moved the workbooks?

**Comment by verdan** [comment]
@jschneidereit yes, I have `abort_on_error` set as True, but no errors. 
I tried to check the `backfill status`, and seems like that is the issue. There is no error, but the `checkpointCreatedTime` is November last year. So, does that mean that the indexes are not refreshed after that?

**Comment by verdan** [comment]
> Could you clarify, did this GraphQL query work before you moved the workbooks?

@jacalata the query is still working without errors, the data is just not complete in the response.

**Comment by verdan** [comment]
> @jschneidereit yes, I have `abort_on_error` set as True, but no errors. I tried to check the `backfill status`, and seems like that is the issue. There is no error, but the `checkpointCreatedTime` is November last year. So, does that mean that the indexes are not refreshed after that?

and I verified via `eventing status` the `checkpointCreatedTime` for Workbook is today's datetime.

**Comment by jacalata** [comment]
I'm trying to ask if you have ever successfully run this query and got the results you expected? If yes, when did that change?

**Comment by jschneidereit** [comment]
An easy way to test the query would be to go to the graphiql page: `https://yourtableauserverhere.com/metadata/graphiql/` and try and run it by hand to remove the complexity of python and this client. Once you're certain the metadata store is ok then we can determine if this is an issue in the python client.

**Comment by jacalata** [comment]
I haven't been able to reproduce this, so without more info there's not much we can do to help.
