### ISSUE TITLE
Add user to impersonate when signing in with Admin user token

### ISSUE THREAD

**Issue by difemaro** [tableau/server-client-python#1198]
## Summary
In the REST API is documented that you can impersonate a user using token authentication:
![image](https://user-images.githubusercontent.com/24664152/221058529-010197aa-ac32-43ae-be66-f7dad1b11495.png)

## Request Type
New Feature

****Type 1: support a REST API:**** 
Yes, this is a supported feature in REST API:
Signing in with server administrator's [personal access token(Link opens in a new window)](https://help.tableau.com/current/server/en-us/security_personal_access_tokens.htm) (PAT) to impersonate a user (not available for Tableau Cloud): https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_authentication.htm#sign_in

<tsRequest>
  <credentials personalAccessTokenName="personal-access-token-name"
    personalAccessTokenSecret="personal-access-token-secret" >
	  <site contentUrl="content-url" />
	  <user id="user-to-impersonate" />
  </credentials>
</tsRequest>

## Description
Currently, impersonate user is only available for username and password in tableau_auth.py, however it could be needed in other cases where username and password is not available.

**Comment by jorwoods** [comment]
Would be fixed by #1219
