### ISSUE TITLE
server.workbooks.download giving 400 Bad Request error

### ISSUE THREAD

**Issue by Soltis12** [tableau/server-client-python#1205]
**Describe the bug**
server.workbooks.download giving 400 Bad Request error
These parts of the below code work, demonstrating successful connection to our Tableau server:
- Sign into the Tableau Server
- Initiate logging of the script activity
- Sign into the Tableau Server
- Generate a list of the workbooks
- Sign out of the Tableau Server

However this part of the code doesn't work:
- Download the workbooks to a specified folder

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online)
 - Python version
 - TSC library version

**To Reproduce**

```
# Sign into the Tableau Server
import tableauserverclient as TSC
import logging

# Initiate logging of the script activity
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    filename="tsc.log", level="DEBUG")

# Sign into the Tableau Server
tableau_auth = TSC.TableauAuth('user@company.com', 'password', site_id='company')
server = TSC.Server('server_address', use_server_version=True)

# Generate a list of the workbooks
with server.auth.sign_in(tableau_auth):
  all_workbooks_items, pagination_item = server.workbooks.get()  
  print([workbook.name for workbook in all_workbooks_items])

# Download the workbooks to a specified folder
with server.auth.sign_in(tableau_auth):
    for workbook in all_workbooks_items:
        file_path = server.workbooks.download(all_workbooks_items[0], filepath=r"C:\Users\user_name\Desktop\download test")
        print("\nDownloaded the file to {0}.".format(file_path))

# Sign out of the Tableau Server
server.auth.sign_out()
```

**Results**
```
NonXMLResponseError: b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>400 Bad Request</title>\n</head><body>\n<h1>Bad Request</h1>\n<p>Your browser sent a request that this server could not understand.<br />\n</p>\n</body></html>\n'
```
**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
There are two problems in this code. 

1. you are looping over each workbook in the list all_workbooks_items, but then you download the first workbook in the list every time (all_workbooks_items[0])
2. The method server.workbooks.download wants the first argument to be the workbook id, but you have passed it an entire workbook item. 

Try this replacement code:
```
# Download the workbooks to a specified folder
with server.auth.sign_in(tableau_auth):
    workbook = all_workbooks_items[0]
    file_path = server.workbooks.download(workbook.id, filepath=r"C:\Users\user_name\Desktop\download test")
    print("\nDownloaded the file to {0}.".format(file_path))
```

**Comment by Soltis12** [comment]
> Contributor

Yep, my code was wrong; thank you!
