### ISSUE TITLE
Getting error Datasources is not available in API version 2.4. Requires 2.8

### ISSUE THREAD

**Issue by Rahmat711** [tableau/server-client-python#1229]
**Describe the bug**
when i am using refresh method in code it stating i need to upgrade API but i am already using latest tableauserverclient version
and getting error EndpointUnavailableError: Datasources is not available in API version 2.4. Requires 2.8
`
**Versions**
 - Tableau Server version (or note if using Tableau Online) - (Tableau online) ServerInfoItem: [product version: 2022.1.4, build no.:20221.22.0712.0324, REST API version:3.15]
 - Python version - 3.8
 - TSC library version - (0.25)

**To Reproduce**
`# Get the data source by ID
datasource_id = my_datasource.id
print(datasource_id)
refresh_datasource = server.datasources.get_by_id(datasource_id)
print(refresh_datasource)

refreshed_datasource = server.datasources.refresh(refresh_datasource)`

**Results**
EndpointUnavailableError                  Traceback (most recent call last)
Cell In [31], line 16
     13 print(refresh_datasource)
     15 # Refresh the data source
---> 16 refreshed_datasource = server.datasources.refresh()
     17 print(refreshed_datasource)

File ~/Library/Python/3.9/lib/python/site-packages/tableauserverclient/server/endpoint/endpoint.py:204, in api.<locals>._decorator.<locals>.wrapper(self, *args, **kwargs)
    202 @wraps(func)
    203 def wrapper(self, *args, **kwargs):
--> 204     self.parent_srv.assert_at_least_version(version, self.__class__.__name__)
    205     return func(self, *args, **kwargs)

File ~/Library/Python/3.9/lib/python/site-packages/tableauserverclient/server/server.py:197, in Server.assert_at_least_version(self, comparison, reason)
    195 if not self.check_at_least_version(comparison):
    196     error = "{} is not available in API version {}. Requires {}".format(reason, self.version, comparison)
--> 197     raise EndpointUnavailableError(error)

EndpointUnavailableError: Datasources is not available in API version 2.4. Requires 2.8

**Comment by jacalata** [comment]
Yes. You need to specify which version of the API you think you are using - most commonly this is done by setting "use_server_version=True" as demonstrated in our login sample. If you do not give any information about the API version to use, tsc will default to the oldest supported version, 2.4.

https://github.com/tableau/server-client-python/blob/master/samples/login.py

**Comment by Rahmat711** [comment]
Yep it worked after adding and specifying version before auth:

`server.use_server_version()
server.auth.sign_in(tableau_auth)
server_info = server.server_info.get()

    # Print the version information to the console
print('Tableau Server version:', version)`
Thanks!
