### ISSUE TITLE
[Help Wanted] TSC ServerInfo call and SignOut call Hanging/Freezing after TSC Version Upgrade

### ISSUE THREAD

**Issue by caseycourtneycu** [tableau/server-client-python#1230]
**Describe the bug**
After upgrading TSC from 0.19.0 to 0.22  the below lines of code cause a hanging/freezing behavior
(after experimenting I have determined these are the versions where the behavior changes, I'm actually trying to upgrade from 0.14.1 to 0.24)
I also tested all the way up to 0.25, same issue
I have to upgrade the TSC version due to a seperate issue.

Scenario 1: 
server = TSC.Server(serverUrl, use_server_version = True) --- Freezes here
tableau_auth = TSC.TableauAuth(tableauAcct, tableauPwd)
server.auth.sign_in(tableau_auth)
server.auth.sign_out()

Scenario 2:
server = TSC.Server(serverUrl, use_server_version = False)
server.version = "3.17"
tableau_auth = TSC.TableauAuth(tableauAcct, tableauPwd)
server.auth.sign_in(tableau_auth)
server.auth.sign_out() --- Freezes here

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online) API: 3.17 Server: 2022.3.5
 - Python version : 3.7
 - TSC library version: 0.19.0 is working, 0.22 is not
 - Its running in a python flask app in a docker container: Flask version: 2.2.4
 I can provide my dockerfile or requirements.txt if you think that would be helpful

**To Reproduce**
Steps to reproduce the behavior. Please include a code snippet where possible.
Run Above lines of code after deploying

**Results**
What are the results or error messages received?
Excecution Freezes/Hangs
After about 5 ish minutes I get this error
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
Sorry for the delay - this sounds like there's some kind of firewall or network condition between tsc and the server that is making the request hang. Do you have access to the server logs to see if the request is actually getting to the server?

**Comment by caseycourtneycu** [comment]
I kind of resolved the issue.
Our Tableau instance sits behind Akamai, and Akamai was blocking the traffic as it detected it as bot traffic because all the requests were missing several headers.
I don't know why and was unable to figure out why the version change of TSC caused the headers to disappear but we kind of resolved it by making a rule in Akamai to allow traffic through from the specific IP address of where the requests are coming from.

**Comment by bcantoni** [comment]
Thanks for confirming you've got it working - I'll close this one.
