### ISSUE TITLE
Self-signed SSL

### ISSUE THREAD

**Issue by ugamarkj** [tableau/server-client-python#126]
Does the current package support environments with self-signed SSL certs? I can't figure out what I need to do to pass the "verify=False" argument in requests.post()

**Comment by RussTheAerialist** [comment]
Hey,

We support it at the server object level.  There is an add_http_options method call that allows you to pass arguments to requests.

You can see an example of this in the sample here: https://github.com/tableau/server-client-python/blob/master/samples/set_http_options.py#L36

Line 36 is the interesting bit there.  Let me know if you run into any problems with setting it.

**Comment by t8y8** [comment]
In addition you may get warnings, the workaround is to put this in your script:

```python
import requests
from requests import InsecureRequestWa‌​rning
requests.packages.urllib3.disable_warnings(InsecureRequestWa‌​rning)
```

**Comment by ugamarkj** [comment]
Great! Thanks for the help

**Comment by Talvalin** [comment]
Can we close this issue out, given that I updated the sign-in/sign-out doc to explicitly talk about the workaround for self-signed certificates? https://github.com/tableau/server-client-python/blob/development/docs/docs/sign-in-out.md
