### ISSUE TITLE
Daily Schedule start_time update returns error

### ISSUE THREAD

**Issue by yankiokdemir** [tableau/server-client-python#1269]
**Describe the bug**
Since it is not possible to create an incremental schedule by using "schedules.create" method, I decided to use a workaround by creating incremental refresh schedule manually on server side but control the schedule time with schedules.update method programmatically based on some ETL jobs on our environment. Here the problem is if the schedule on server which I want to update is a daily schedule (which has no end_time, only start-time) then the code below returns an error as stated in result section. Somehow it is expecting like a pair value. But daily schedule has no interval pair. It has only start_time attribute. 

**Versions**
Details of your environment, including:
 - Tableau Server version 2022.3.1
 - Python version 3.9
 - TSC library version 0.25

**To Reproduce**

````py
server.auth.sign_in(tableau_auth)

now = datetime.datetime.utcnow()
next_hour_timestamp = now + datetime.timedelta(hours=1)
next_hour = next_hour_timestamp.hour

def start_time_hour():
    if now.minute >= 45:
        return next_hour
    else:
        return now.hour


def start_time_minute():
    if 14 >= now.minute >= 00:
        return 15
    elif 29 >= now.minute >= 15:
        return 30
    elif 44 >= now.minute >= 30:
        return 45
    else:
        return 00


# Defining variable out of functions for start-time and minute
start_hour = start_time_hour()
start_minute = start_time_minute()


# Retrieve the id of the schedule
def get_schedule():
    all_schedules, pagination_item = server.schedules.get()
    for sch in all_schedules:
        if sch.name == 'trigger_daily':
            return sch.id


target_schedule_id = get_schedule()
schedule = server.schedules.get_by_id(target_schedule_id)

# Function was created to update the schedule
def update_schedule_item(schedule_item):
    new_start_time = datetime.time(start_hour, start_minute)
    schedule_item.interval_item.start_time = new_start_time
    server.schedules.update(schedule_item)

update_schedule_item(schedule)
````

**Results**

````
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.1.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\User\PycharmProjects\TableauRestAPI\update_schedule.py", line 72, in <module>
    update_schedule_item(schedule)
  File "C:\Users\User\PycharmProjects\TableauRestAPI\update_schedule.py", line 70, in update_schedule_item
    server.schedules.update(schedule_item)
  File "C:\Users\User\PycharmProjects\TableauRestAPI\venv\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 205, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\TableauRestAPI\venv\lib\site-packages\tableauserverclient\server\endpoint\schedules_endpoint.py", line 65, in update
    update_req = RequestFactory.Schedule.update_req(schedule_item)
  File "C:\Users\User\PycharmProjects\TableauRestAPI\venv\lib\site-packages\tableauserverclient\server\request_factory.py", line 533, in update_req
    for interval in interval_item._interval_type_pairs():
AttributeError: 'DailyInterval' object has no attribute '_interval_type_pairs'
````

**Comment by yankiokdemir** [comment]
def_update_req must be re-adjusted to have separate interval and _interval_type_pairs sub elements as below.

    def update_req(self, schedule_item):
        xml_request = ET.Element("tsRequest")
        schedule_element = ET.SubElement(xml_request, "schedule")
        if schedule_item.name:
            schedule_element.attrib["name"] = schedule_item.name
        if schedule_item.priority:
            schedule_element.attrib["priority"] = str(schedule_item.priority)
        if schedule_item.execution_order:
            schedule_element.attrib["executionOrder"] = schedule_item.execution_order
        if schedule_item.state:
            schedule_element.attrib["state"] = schedule_item.state

        interval_item = schedule_item.interval_item
        if interval_item is not None:
            if interval_item._frequency:
                schedule_element.attrib["frequency"] = interval_item._frequency
            frequency_element = ET.SubElement(schedule_element, "frequencyDetails")
            frequency_element.attrib["start"] = str(interval_item.start_time)
            if hasattr(interval_item, "end_time") and interval_item.end_time is not None:
                frequency_element.attrib["end"] = str(interval_item.end_time)
            intervals_element = ET.SubElement(frequency_element, "intervals")
            if hasattr(interval_item, "interval"):
                for interval_value in interval_item.interval:
                    single_interval_element = ET.SubElement(intervals_element, "interval")
                    single_interval_element.attrib["expression"] = interval_value
            if hasattr(interval_item, "_interval_type_pairs"):
                for interval in interval_item._interval_type_pairs():
                    (expression, value) = interval
                    single_interval_element = ET.SubElement(intervals_element, "_interval_type_pairs")
                    single_interval_element.attrib[expression] = value
        return ET.tostring(xml_request)

**Comment by yankiokdemir** [comment]
Hello Brian, @bcantoni 
How fast would it be possible to investigate and alter the update_req method in request_factory.py ? Can we somehow help ? Because we have a pending production critical release where this bug basically prevents to move forward. Idea is very simple and it is to update the start time of a daily schedule every day based on a database event (sample code above uses now variable for test purpose). In summary, we stuck with the update method because it is not letting us to update the start time basically and looks for interval type pairs which is not relevant for a daily interval. Or are we missing something? 

My solution was to add the below-mentioned part before the interval_type_paris sub attribute as a new sub attribute. And it could help the code successfully execute. But official library does not have this adjustment of course. Therefore we need Tableau's support here and we are here to contribute. Any suggestions ?

 if hasattr(interval_item, "interval"):
            for interval_value in interval_item.interval:
                single_interval_element = ET.SubElement(intervals_element, "interval")
                single_interval_element.attrib["expression"] = interval_value

**Comment by bcantoni** [comment]
@yankiokdemir thanks for the detailed report and proposed fix. Would you be able to create a pull request with those proposed changes? Then we can do a code review and help move this issue forward for you.

There is more info about the steps for contributing in the docs under [Developer Guide](https://tableau.github.io/server-client-python/docs/dev-guide).

**Comment by jacalata** [comment]
This should be solved by this commit: https://github.com/tableau/server-client-python/commit/f17a75d14cc0d516a01ec2676326d42f29a1866c
