### ISSUE TITLE
Server sign-in returns error: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by alireza18878** [tableau/server-client-python#1278]
**Describe the bug**
I am trying to sign-in to my tableau's server (using the code mentioned below), and I keep getting this error: 'NoneType' object has no attribute 'get'

**Versions**
Details of your environment, including:
 - Tableau Server version: N/A
 - Python version: 3.5
 - TSC library version: 0.15

**To Reproduce**
I used the code below to sign-in to my Tableau's server:

`import os
import tableauserverclient as TSC
from bento import authenticated_corp_fwdproxy

proxy_address='https://_proxy_address:proxy_port_'
os.environ['http_proxy']=proxy_address
os.environ['https_proxy']=proxy_address

tableau_auth = TSC.TableauAuth('username', 'password', 'site_id')
server = TSC.Server('_https://tablea_server_')

with authenticated_corp_fwdproxy():
    server.auth.sign_in(tableau_auth)`

(I am using proxy since it is required here. Without using proxy, it returns Proxy Error).

**Results**
I get this error:

`'NoneType' object has no attribute 'get'`

Can you please let me know why I am getting this error?

**Comment by bcantoni** [comment]
@alireza18878 is this the same issue as you reported over in #1277?

**Comment by alireza18878** [comment]
Hi @bcantoni , no, issue #1277 was about HTTPS Proxy error, this one is about a different error ('NoneType' object has no attribute 'get').

**Comment by jacalata** [comment]
This error means you are not connected to the server (your 'server' object is NoneType), and it's probably because it can't go through the proxy. I'm not sure how the proxy code shown works, but to make tsc use the proxy you need to set it in the http_options like this

```
    my_proxies = {
        'http': 'http://10.10.1.10:3128',
        'https': 'http://10.10.1.10:1080',
    }
    server = TSC.Server(server_url, use_server_version=True, http_options={"verify": use_ssl, "proxies": my_proxies})
```

I will close this issue, so that if you have further proxy connection questions they can go in one conversation.
