### ISSUE TITLE
Refresh and download live tableau datasource

### ISSUE THREAD

**Issue by v6shah** [tableau/server-client-python#1279]
**Describe the bug**
Not a bug, but wanted some help in figuring out if there exists any method to refresh and download a live tableau data source. I know of download option in server.datasources, but it doesn't refresh the connection. And .refresh method is not valid for live connections.

When I publish a data source, it is not refreshed until I create a workbook using it. Now, I want to download a refreshed/updated data source using python. (Also, note that db connections credentials are embedded in the data source when publishing)

**To Reproduce**
1. Publish a live connection data source to server using API. 
2. Update the data connected to data source. (do not create a workbook using this data source. This refreshes the data. This is what I want to do using API)
3. Download the data source. Using Tableau desktop, view it, the data source is not in sync with actual connection. If I click on "Edit Data source", it will update and new fields will appear.

**Comment by harshalreja-gep** [comment]
Hi v6shah,
I have a query regarding steps to reproduce
step 1. How are you establishing a live connection data source to server using API?
