### ISSUE TITLE
server.tasks.get() fails on specific extract refresh schedule

### ISSUE THREAD

**Issue by MrPanchoso** [tableau/server-client-python#1292]
**Describe the bug**
tasks.get fails whenever a specific form of schedule exists in Tableau Online, specifically a schedule which runs on certain days and in a range of time during those days.

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online): Tableau Online
 - Python version: 3.10.9
 - TSC library version: 0.28

**To Reproduce**
When doing something like what [this example](https://tableau.github.io/server-client-python/docs/api-ref#tasksget) in the documentation describes (tasks.get)
If there is an extract task which schedule is of the following way:
`Every Mon, Tue, Wed, Thu, Fri, every hour from 12:00 AM to 12:00 PM (UTC-04:00) America/Santiago`
![image](https://github.com/tableau/server-client-python/assets/7071977/5b5cb5c1-bb9d-45e0-a50c-818ef0469d26)

**Results**
What are the results or error messages received?

```
  File "/Users/panchov/tsc/testing/tbltest.py", line 130, in get_tasks
    for resource in tsc.Pager(server.tasks.get):
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/server/pager.py", line 39, in __iter__
    current_item_list, last_pagination_item = self._endpoint(self._options)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 292, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/server/endpoint/tasks_endpoint.py", line 37, in get
    all_tasks = TaskItem.from_response(server_response.content, self.parent_srv.namespace, task_type)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/models/task_item.py", line 53, in from_response
    return list(all_tasks)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/models/task_item.py", line 51, in <genexpr>
    all_tasks = (TaskItem._parse_element(x, ns) for x in all_tasks_xml)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/models/task_item.py", line 80, in _parse_element
    schedule_item_list = ScheduleItem.from_element(element, ns)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/models/schedule_item.py", line 222, in from_element
    ) = cls._parse_element(schedule_xml, ns)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/models/schedule_item.py", line 297, in _parse_element
    interval_item = ScheduleItem._parse_interval_item(frequency_detail_elem, frequency, ns)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/models/schedule_item.py", line 267, in _parse_interval_item
    return HourlyInterval(start_time, end_time, interval_value)
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/models/interval_item.py", line 32, in __init__
    self.interval = interval_value
  File "/usr/local/lib/python3.10/site-packages/tableauserverclient/models/interval_item.py", line 68, in interval
    if float(interval) not in VALID_INTERVALS:
ValueError: could not convert string to float: 'Friday'
```

**Comment by jwinsch** [comment]
Thanks for posting this. We're getting the same error on Tableau Online. Looking forward to a resolution. Looks like an issue with parsing the XML here:       all_tasks = (TaskItem._parse_element(x, ns) for x in all_tasks_xml) in task_item.py. I'm still debugging but if I get more information I will post here.

**Comment by vizyourdata** [comment]
I am seeing the same error but for 'Saturday' as the string.

Tableau Online
Python:3.9.13
tableauserverclient==0.25

**Comment by jwinsch** [comment]
I contacted Tableau Support about this and they responded "the last time we helped you with this it was an act of courtesy." They referred me to github. Case closed! 

Actually, the act of courtesy was referring me to the solution on github to the schedule_item.py hack by austinpeter (thank you!):

https://github.com/tableau/server-client-python/issues/1237#issuecomment-1581384414

This solved my "name not defined" error the first time around on 0.23.4, but no more. Then "name not defined" started popping up again on 0.23.4, but on later versions you will get "ValueError: could not convert string to float: 'Friday'". (Or some other day of the week like you're seeing.)

I tried debugging the rat's nest for a few hours, but this proved tiresome. I resolved this by removing my TSC reference, and replaced it with a CURL call for extractRefreshes with Python (appears to work), then parsed out the XML manually to get what I needed. We're on Tableau Online:

https://prod-useast-a.online.tableau.com/api/3.14/sites/<site_id>/tasks/extractRefreshes

Hope this helps.

Good luck.

**Comment by vizyourdata** [comment]
This might sound crazy, but I was testing the endpoint you referenced in thunder client before I posted this with no luck. Today it's working. Thanks for posting this or I may not have checked again so soon.

**Comment by jwinsch** [comment]
Good news, glad to hear.

**Comment by jacalata** [comment]
I thought I had responded to this, sorry! Tableau Support should not reject requests for help with our published library and sample code. I don't know if their response was meant to say they didn't have to help with tsc, which is wrong, or if they were saying something about support contracts, which I don't know anything about.
