### ISSUE TITLE
Wrong type annotation in workbook.refresh

### ISSUE THREAD

**Issue by pes-magic** [tableau/server-client-python#1318]
**Describe the bug**
`workbooks.refresh` is implemented to receive `workbook_id` as a string type argument, but it can actually receive `WorkbookItem` as well. The documentation also states that it receives `workbook_item`.

Implementation: https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/endpoint/workbooks_endpoint.py#L91
Documentation: https://tableau.github.io/server-client-python/docs/api-ref#workbooksrefresh

**Versions**
 - TSC 0.28

**To Reproduce**
Nothing to do

**Results**
Static code analysis displays false warnings

**Comment by jorwoods** [comment]
@pes-magic Can you mark this as closed by #1319?

**Comment by pes-magic** [comment]
Sure, thank you for reminding me
