### ISSUE TITLE
Datasource.updated_at - Did it change from 2.2 to 2.4 rest api?

### ISSUE THREAD

**Issue by TCMurph** [tableau/server-client-python#132]
I upgraded to Tableau 10.1, which i believe is rest api 2.4, and also downloaded the latest TableauServerClient module, and it looks like the datasource updated_at previously contained the maximum value between the modified date (versioning of extract) and the update date (when an extract last refreshed) for example.

Is this a known change? I couldn't find any documentation on the rest api that called that out. I was relying on the datasource.updated_at to be the combo to cover events where i knew whether a datasource was re-published or whether a datasource was last refreshed (in the case on an extract).

Any information would be super helpful, and thanks.

Paul

**Comment by TCMurph** [comment]
Strange thing is that I was able to change the api version setting to 2.3, and it still work on Tableau Server 10.1 and also for the modified/updated to be correct. So, everything works fine using the 2.3 rest api version.

**Comment by RussTheAerialist** [comment]
Sorry, I missed this one!  I'll dig into it when I have a moment.

**Comment by TCMurph** [comment]
Thanks Russell!

**Comment by RussTheAerialist** [comment]
weird.  The code path for this one doesn't vary based on rest version, so I have no idea how the behavior you are seeing is possible.  I'm going to try to repro it locally to see what's going on.

If you had a fiddler trace for both requests (2.4 vs. 2.3) where you are seeing the issue, that might speed up my investigation

**Comment by TCMurph** [comment]
Russell,

Let me test this again just to make sure then. I'll respond soon.

Thanks.

Paul

**Comment by irwando** [comment]
Closing 2yo issue.  Please reopen if still an issue.
