### ISSUE TITLE
[TYPE 1] [Set workbook parameter value in REST API call]

### ISSUE THREAD

**Issue by AlfredoPalacios** [tableau/server-client-python#1332]
## Summary
Set the value of view parameters (like vf filtering, but for parameters).

## Description
Be able to set the value of a parameter in a view using a method, like the method vf('filter_name', 'filter_Value') but for parameters. In the REST API, the request would look like this: GET /api/api-version/sites/site-id/views/view-id/data?vf_Parameters.<parametername>=parameter-value

This would allow having only one workbook, but download multiple different view images with different data each one.

**Comment by jorwoods** [comment]
This is already possible by using `ImageRequestOptions`.

```
opts = TSC.ImageRequestOptions()
opts.vf("Parameters.param_name", "parameter_value")
...
```
