### ISSUE TITLE
Refreshing Datasources results in 409093 EXTRACT_OPERATION_ALREADY_QUEUED

### ISSUE THREAD

**Issue by BerndRos** [tableau/server-client-python#1339]
**Describe the bug**
When refreshing Datasource-Extracts the server response is 409093 (even though the extract operation is not already queued)

**Versions**
Details of your environment, including:
 - Tableau Server version: 2023.1.7
 - Python version: 3.10.7
 - TSC library version: 0.29

**To Reproduce**
For any datasource:
server.datasources.refresh(datasource)

**Results**
What are the results or error messages received?
tableauserverclient.server.endpoint.exceptions.ServerResponseError:

409093: Ressourcenkonflikt

(This is German for the Error: EXTRACT_OPERATION_ALREADY_QUEUED)

I can fix this behavior when I set the parameter seconds in 
\tableauserverclient\server\endpoint\endpoint.py
in Line 105 from 0.05 to a higher value, e.g. 0.5

**Comment by bcantoni** [comment]
@BerndRos I believe I can reproduce this as well. Could you try using the prior TSC library 0.28? I think that might be a workaround until this is fixed.

**Comment by BerndRos** [comment]
Hey @bcantoni thanks for your comment. We had to move to version 0.29 due to the fix in Commit f42948a. We will just adjust the value of seconds in the installation of 0.29 and wait for the new version.

**Comment by HendrikZe** [comment]
@bcantoni same issue here. I was able to run my script using `0.28` as a workaround until this is resolved.

**Comment by ConstantinoSchillebeeckx** [comment]
We're running `0.25` and seeing this issue as well.

**Comment by bcantoni** [comment]
@BerndRos @HendrikZe we have a new v0.30 release which I believe should fix this:
https://github.com/tableau/server-client-python/releases/tag/v0.30

**Comment by HendrikZe** [comment]
@bcantoni I can confirm that a first test with v0.30 did not throw the error. Will report back if I see it coming up again somewhere else. Thanks!

**Comment by sky-apoorva-saxena** [comment]
This is reproducible again on 0.34
