### ISSUE TITLE
Add Data Source Description

### ISSUE THREAD

**Issue by ugamarkj** [tableau/server-client-python#135]
Need the ability to add a description to a data source when publishing. Currently it overwrites the existing description with nothing.

**Comment by t8y8** [comment]
Hey Mark!

I just checked, the REST API backend doesn't support this -- we should add it!

/cc @benlower @RussTheAerialist

**Comment by ugamarkj** [comment]
Thanks Tyler. I’ll have to be more conservative with my auto-metadata Python script so I don’t lose my descriptions frequently. =)

**Comment by t8y8** [comment]
It's also definitely a bug if we're overwriting existing descriptions!

**Comment by RussTheAerialist** [comment]
the REST api doesn't support it, but I dug through the server code a bit today and it looks like it should be easy to pipe through.  I'll ask @benlower to put it on our backlog for the server work.

**Comment by benlower** [comment]
thanks for raising this

**Comment by benlower** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/zGOfAVhk/4-test)

**Comment by ugamarkj** [comment]
Curious to know if this is still on anyone's radar. I just checked and it is still a problem in 2019.2.

**Comment by btorgesen** [comment]
Could someone please give an update on this feature. I'm the Tableau architect for a major bank and am working on an automated process to deploy enterprise data sources and workbooks to the all of the sites on our enterprise Tableau server. We need to be able to create projects (with descriptions) automatically for new sites.

**Comment by ImangulovA** [comment]
begging for it as well!

**Comment by JoeyKwok** [comment]
Still unavailable?

**Comment by ugamarkj** [comment]
With every release I'm like "maybe...maybe...dangit". I'm sure there are cross team dynamics at play.

**Comment by TimothyVermeirenBiztory** [comment]
Also still hoping for this capability to be available soon!

**Comment by michelekorell** [comment]
Hello, we have the same issue, but this topic is already 4 years old. There is another place where Tableau server-side improvement are discussed? Thx.

**Comment by chris-day** [comment]
Any updates on where this is?

**Comment by jacalata** [comment]
This was fixed in 2023, I have now added code demonstrating it to the explore_datasource sample.
