### ISSUE TITLE
Getting internal server error 503

### ISSUE THREAD

**Issue by septatrix** [tableau/server-client-python#1361]
**Describe the bug**
Using the API results in 503 errors, i.e. errors not cause by the client but by the server.

**Versions**
Details of your environment, including:
 - Tableau Online
 - Python version: 3.10.12
 - TSC library version: 0.19

**To Reproduce**
This happens spuriously when requesting PDFs. We have a script running which generates several PDFs once a week. Most of the time it runs without problems or maybe one or two fails, but this week we got a whole bunch of server errors at 2024-03-06T20:36:22.641004+0100 and before. Is this the correct place (or if not could you escalate this to the correct people)?

**Results**
`b'<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n\n'`

**Comment by jacalata** [comment]
This got reported internally and appears to be ops-related. Thanks for reporting - if you do continue to see this (or other errors) please open a new bug.
