### ISSUE TITLE
Tasks.create does not work with Tableau Server

### ISSUE THREAD

**Issue by bugcity** [tableau/server-client-python#1376]
The url and create_req generated by Tasks.create seem to be for Tableau Cloud; when run on Tableau Server, no error occurs, but the task is not created.

**Comment by jacalata** [comment]
What kind of task are you trying to create?

**Comment by bcantoni** [comment]
Closing due to age. If you're still experiencing this issue, please reopen with some more specific details of what you've tried and what is happening.
