### ISSUE TITLE
Schedules REST API is encountering an issue with responses: interval details for 'Hourly' and 'Daily' schedules are missing. This information, vital for accurate task execution, is currently unavailable. Are you aware of this issue?

### ISSUE THREAD

**Issue by Hiraltailor1** [tableau/server-client-python#1377]
Missing interval details specifically days of the week to execute schedules in API responses for 'Daily' and 'Hourly' schedules, crucial for task configuration and execution. 'Monthly' and 'Weekly' schedules retrieving necessary details.

 

Requesting assistance in schedule API responses to include the missing interval details, particularly the days of the week for 'Daily' and 'Hourly' schedules. Your insights and suggestions on how best to integrate this information into our API responses would be greatly appreciated.

 

Attached to this message is a PDF containing the current API responses for reference.
[Schedule Frequencies.pdf](https://github.com/tableau/server-client-python/files/15398196/Schedule.Frequencies.pdf)

**Comment by jacalata** [comment]
It looks like you have an on-premise install of Tableau Server. 3.15 is a fairly old version of the API: do you know what version of server you have?

**Comment by Hiraltailor1** [comment]
The server version is 3.15. Does the API provide the correct response for higher server versions can you confirm?

**Comment by jacalata** [comment]
This was fixed in version 2023.3.5, which is API version 21.
