### ISSUE TITLE
REST API Request - Refresh Datasource / extracts

### ISSUE THREAD

**Issue by wildest** [tableau/server-client-python#138]
The ability to refresh extracts via a REST call has been requested for quite some time now. There's a few ideas on the Tableau Community i.e. https://community.tableau.com/ideas/5457

It would be great if we could trigger an extract via the REST API and subsequently monitor the progress of it to check when it's finished.

Right now this is possible via the 'undocumented' API, but it sure would be great to see something official get released.

**Comment by RussTheAerialist** [comment]
Hey! Thanks for the request.  This is one of our most received requests, and I'm actively working on it from the REST api side, but we aren't sure which release it'll be in yet.  TSC will be updated to include the ability to trigger refreshes as soon as we have it in the server.

**Comment by wildest** [comment]
Thanks for the quick update Russ. I'm more interested in the REST API as I'll be making my calls from C#.
I'll keep an eye out for updates!

**Comment by RussTheAerialist** [comment]
v0.4.x contains the TSC code for supporting this.  It's blocked from being used until REST API v2.6 comes out, but there is no remaining work on the "refresh now" portion of TSC.

**Comment by begerbeger** [comment]
Hi @RussTheAerialist 

Any updates on this? Looks like it's in the `refresh-now` branch?

**Comment by begerbeger** [comment]
Hi again @RussTheAerialist . Looks like the `refresh-now` branch is merged to development. Any idea on when it will be merged to master?

**Comment by RussTheAerialist** [comment]
I’m working on a release this week.  I’m hoping to do it today.  I’m just
trying to finish up one more item before cutting the release.

>

**Comment by begerbeger** [comment]
Wonderful! Thanks for replying.
