### ISSUE TITLE
Add support for retrieving, creating/configuring, and executing linked tasks.

### ISSUE THREAD

**Issue by CodingOnWindowsOS** [tableau/server-client-python#1423]
**Current REST API Support**
Get linked tasks: https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_flow.htm#get_flow_run_tasks1
Run linked task: https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_flow.htm#run_flow_now1

**Add REST API Support**
I don't believe the ability to create and configure a linked task is currently supported by the REST API. A linked task can be configured when on the page (https://your_server/#/flows/2490/scheduledTasks) displaying a specific flow by clicking "Scheduled Tasks" and then "New Task." Additionally, server.tasks.get and similar strategies for retrieving task info on the server using TSC currently defaults to only retrieves extract refresh tasks (task_type='extractRefresh').

**Comment by jorwoods** [comment]
WIP

**Comment by jorwoods** [comment]
Adding support for reading linked tasks to TSC is currently a WIP.

**Comment by jorwoods** [comment]
Support for reading and running linked tasks in #1424

**Comment by CodingOnWindowsOS** [comment]
> Support for reading and running linked tasks in #1424

Is there any update that can be provided on making this available?

**Comment by jacalata** [comment]
I'm afraid he can't create releases, but there should be one this week or next.

**Comment by CodingOnWindowsOS** [comment]
> I'm afraid he can't create releases, but there should be one this week or next.

Thanks! I'm rather ignorant on how this process works. I appreciate the comment and update.

**Comment by jacalata** [comment]
This is now released - sorry for the delay!
