### ISSUE TITLE
TSC.SubscriptionItem, Payload is either malformed or incomplete. (0x5CE10192 : Specifying subscription attachments not allowed.)

### ISSUE THREAD

**Issue by gdrau** [tableau/server-client-python#1430]
Hello, I'm trying to create a subscription for a user on a view. I put this piece of code,
 schedule_id = '60c392fc-d902-44b0-92cf-cfa3b512630f'
        user_id = df[0].values[i]
        # Create the new SubscriptionItem object with variables from above.
        new_sub = TSC.SubscriptionItem('EssaiGD', schedule_id, user_id, target)

        # (Optional) Set other fields. Any of these can be added or removed.
        new_sub.attach_image = True
        new_sub.attach_pdf = True
        new_sub.message = "You have an alert!"
        new_sub.page_orientation = TSC.PDFRequestOptions.Orientation.Portrait
        new_sub.page_size_option = TSC.PDFRequestOptions.PageType.A4
        new_sub.send_if_view_empty = True
 
        # Create the new subscription on the site you are logged in.
        new_sub = server.subscriptions.create(new_sub)

 I launch it and when I have the error it gives me 0x5CE10192 : Specifying subscription attachments not allowed. 

THanks

Version : 
Product version: 2024.2.0
REST API version: 3.23
Build number: 20242.24.0711.1807
Python 3.10.6

**Comment by jorwoods** [comment]
From the [REST API documentation](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_subscriptions.htm#tableau-server-request):

> If subscriptions to attachments are disabled in Tableau server or site settings, then making a request that sets attachImage to false will cause an error.

**Comment by gdrau** [comment]
the parameters are true and not false in my script. So when I manually create the subscription or when I use a request it works. So I don't understand why it doesn't work

**Comment by gdrau** [comment]
![image](https://github.com/user-attachments/assets/bf75bcdf-ad6f-4527-b2d7-7cd32f0cda0e)

**Comment by jorwoods** [comment]
What happens if you set image to True, pdf to False, and remove the pdf specific options? Try the simplest case first.

**Comment by gdrau** [comment]
![image](https://github.com/user-attachments/assets/8a42ac67-5a73-428a-9310-5ddd9477b172)
the same

**Comment by gdrau** [comment]
![image](https://github.com/user-attachments/assets/b12a9e74-dbf3-42d5-b4c2-eaa00d0582c5)

**Comment by gdrau** [comment]
![image](https://github.com/user-attachments/assets/c2e1f41a-e9ec-4006-b126-032cdf37e664)

**Comment by gdrau** [comment]
?? Help me :-)

**Comment by jacalata** [comment]
@gdrau what API version are you using in your script? This error message will also be returned if you are specifying an API version below 3.5, when the feature was implemented.

**Comment by jacalata** [comment]
I created a sample for subscriptions and verified that it succeeds with the current server version, and fails using 2.4. https://github.com/tableau/server-client-python/pull/1487
