### ISSUE TITLE
Emojis in Populate Image do not render correctly

### ISSUE THREAD

**Issue by widjaya-hernando** [tableau/server-client-python#1436]
Hello,

I am trying to download image from a view. I was able to get the image from the view without any problem, with the exception of the emojis. From my understanding, this should be an issue with the font used when rendering the image for the view. Does anybody know if it is possible to alter the font before the image is renderd, or other ways to solve this issue?

![Screenshot 2024-08-07 132923](https://github.com/user-attachments/assets/16bd4e39-3d5a-4ee2-870d-9e199d687198)
![Screenshot 2024-08-07 133216](https://github.com/user-attachments/assets/16a2f022-3a1e-46b6-bdb3-2bb345c98b54)

**Comment by jacalata** [comment]
This turns out to be a bug on some of our internal servers that is being worked on, but that means a fix will only come with a server update. I don't know of any way to fix this clientside, sorry.
