### ISSUE TITLE
Getting error while login into Tableau Cloud using tableauserverclient

### ISSUE THREAD

**Issue by suman4apr** [tableau/server-client-python#1459]
**Describe the bug**
I'm trying to login into Tableau Cloud using tableauserverclient but getting below error
`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='90su.online.tableau.com', port=443): Max retries exceeded with url: //api/2.4/auth/signin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f41f2cc08d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Versions**
Details of your environment, including:
 - Tableau Online Version - 2024.2.0
 - Python version - 3.7.16
 - TSC library version - 0.31

**To Reproduce**
Steps to reproduce the behavior. Please include a code snippet where possible.

```py
import tableauserverclient as TSC
 
TOKEN_NAME = 'tokentest'
TOKEN = 'token generated from tableau online'

-- Altered pod name due to compliance issue
SERVER = 'https://90y.online.tableau.com/'
-- tried without s in https also but getting same error
SITE = 'sitename'

tableau_token = TSC.PersonalAccessTokenAuth(TOKEN_NAME,TOKEN,site_id=SITE)

tableau_server = TSC.Server(SERVER, use_server_version= True)

tableau_server.auth.sign_in(tableau_token)
```

**Results**
What are the results or error messages received?
```
**self.parent_srv.http_options, allow_redirects=False
  File "/export/test/sam/.local/lib/python3.7/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/export/test/sam/.local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/export/test/sam/.local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/export/test/sam/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='90y.online.tableau.com', port=443): Max retries exceeded with url: //api/2.4/auth/signin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f41f2cc08d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by jacalata** [comment]
This error says it cannot find the server. Most likely something is wrong with your altered pod name. 

Please confirm that you can ping the server by name, and once you can do that, try running the "getting started" samples in order.

**Comment by jorwoods** [comment]
Also make sure that you use the content url form of the site, not the display name. 

![site url](https://github.com/jorwoods/tableau_articles/blob/main/assets/find_site_id.jpg)

**Comment by suman4apr** [comment]
Thank you for the response but as I mentioned that I added wrong server pod name. Thought it might be compliance issue for my company to share that but realised this is public.
So 
Here is the right one.
https://10y.online.tableau.com/

And could you please make me understand what is content url form of the site?

Please let me know if you need any other info to look into the issue.

Just FYI, same code has been working fine for other Tableau Cloud site but not sure why above error is throwing for me even after passing everything right.


Thank you

**Comment by jorwoods** [comment]
What I mean is that you're using the ID for the site as it exists in the URL. See the red underlined portion in the screenshot I provided previously.

**Comment by suman4apr** [comment]
Yes, I'm using the same one as you highlighted in red in above screen and not the display name.

**Comment by jacalata** [comment]
> https://10y.online.tableau.com/

That url does not exist. Visit the site in your browser, and copy the info in the address bar exactly.

**Comment by bcantoni** [comment]
They are most likely referring to this pod: https://10ay.online.tableau.com
