### ISSUE TITLE
csv_req_option can not filter if it's a boolean filter

### ISSUE THREAD

**Issue by irisx0719** [tableau/server-client-python#1464]
**Describe the bug**
I tried to download the data from tableau and save it in csv format, but when I tried to filter data on a boolean filter, it doesn't work
        
**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online): 2023.1.8
 - Python version: python 3.11.6
 - TSC library version:  0.30

**To Reproduce**
csv_req_option = tsc.CSVRequestOptions(maxage=5)
csv_req_option .vf('filter1', 'abc')
csv_req_option .vf('filter2', 'True')

**Results**

filter1 works good, because filter1 is a normal filter with option in text format, but filter2 doesn't work, because filter2 is a boolean filter. But I don't know how to put the value in req_option if I want to filter the data with boolean filter2 with filter2 =True. and I didn't see any instruction in document saying about this one. 

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by bcantoni** [comment]
@irisx0719 I was recently looking at boolean filters and I think you need to pass them in as lower-case strings, for example "true" or "false". It seems that the Tableau Server/Cloud backend treats those as case sensitive.

Let us know if that works for you and we can turn this into a documentation story to make that more clear.

**Comment by irisx0719** [comment]
> @irisx0719 I was recently looking at boolean filters and I think you need to pass them in as lower-case strings, for example "true" or "false". It seems that the Tableau Server/Cloud backend treats those as case sensitive.
> 
> Let us know if that works for you and we can turn this into a documentation story to make that more clear.

thank you @bcantoni, I tried put to the lower-case string and the problem solved.

**Comment by jacalata** [comment]
Added a note here - https://github.com/tableau/server-client-python/issues/1464
