### ISSUE TITLE
[regex] [CSV_REQ_OPTION]

### ISSUE THREAD

**Issue by irisx0719** [tableau/server-client-python#1474]
## Summary
when I use csv_req_option, it seems that I can only put the true value of parameter or filter in csv_req_option, can we use regex to filter the data? cuz for tableau, it could be possible that for some field there would be some similar value pulled in in the future.

**Comment by bcantoni** [comment]
Unfortunately that's not possible. TSC is a simple wrapper on the Tableau REST APIs and there is no support for regex searching like this, just age and filters: https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#query_view_data

I'll take as a backend enhancement for future reference.

**Comment by irisx0719** [comment]
thank you so much
