### ISSUE TITLE
Workbook.update does not update server_address

### ISSUE THREAD

**Issue by cmtoomey** [tableau/server-client-python#148]
This is the code flow
`item = server.workbooks.get_by_id(book_id[1])
server.workbooks.populate_connections(item)
print item.connections[0].id
item.connections[0].server_address = 'server_address'
server.workbooks.update(item)`

When I re-request the same workbook, and query the connection server addresses, they have not been updated.

This appears to be caused by workbook.update() calling the Update Workbook endpoint, but not able to call Update Workbook Connection endpoint, and there isn't a workbook.update_connections (or equivalent).

**Comment by t8y8** [comment]
@cmtoomey You're spot on, we don't have update to the right thing here (yet) and would need to add the appropriate connections endpoints.

Wanna give it a PR ;)
