### ISSUE TITLE
How to get the full data in tabs that built in dashboard

### ISSUE THREAD

**Issue by irisx0719** [tableau/server-client-python#1489]
**Describe the bug**
I can get the data in the first tab that insert in dashboard, but I am not able to get for the rest of the table. 

**Versions**

**To Reproduce**
I use populate_csv function to get the data in certain view

**Results**
only get the data for partial dashboard, is there any function or anyway to get the data in dashboard with multiple table?

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jorwoods** [comment]
It is currently not possible server-side to get data from sheets other than the first in a dashboard. You would be able to access them if they were published as accessible views. 

I opened #1368 as a feature request to be able to select which sheet is accessed.

**Comment by irisx0719** [comment]
> It is currently not possible server-side to get data from sheets other than the first in a dashboard. You would be able to access them if they were published as accessible views.
> 
> I opened #1368 as a feature request to be able to select which sheet is accessed.

Thank you Jorwoods
