### ISSUE TITLE
views.populate_image returns None

### ISSUE THREAD

**Issue by david5010** [tableau/server-client-python#1521]
**Describe the bug**
After authenticating, identifying the correct workbook and the correct sheet, calling server.views.populate_image(sheet_view, image_req_option) I get None

**Versions**
Details of your environment, including:
 - Tableau Server version (via pip, 0.34)
 - Python version: 3.11

**To Reproduce**
```python
# After authenticating correctly
server.workbooks.populate_views(workbook)
sheet_view = next((v for v in workbook.views if v.name == SHEET_NAME), None)
image_req_option = TSC.ImageRequestOptions(maxage=1)  # Set cache options if needed
image = server.views.populate_image(sheet_view, image_req_option)
```
**Results**
image is None

**Comment by jorwoods** [comment]
Expected behavior. Check the `sheet_view.image` attribute.

**Comment by david5010** [comment]
Oh yes, sorry, I think I misread the documentation, it all worked out!
