### ISSUE TITLE
ENHANCEMENT: Access to /customviews (Search)

### ISSUE THREAD

**Issue by cpare** [tableau/server-client-python#1539]
## Summary
TSC does not appear to have support for /customviews

## Request Type
Enhancement:  Specifically Search for my use case.

****Type 1: support a REST API:**** 
https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#get_custom_view
Example: https://servernaname/api/3.19/sites/{{site_liud}}/customviews

****Type 2: add a REST API and support it in tsc.****
Available in the REST API - Links above.

****Type 3: new functionality****
This is not for new API Functionality.

## Description
The TSC currently does not appear to support /customviews.  In our use case I need to search the site for all custom views and then parse them by name as there does not appear to be a tag option for a custom view.

**Comment by jorwoods** [comment]
TSC does have support already under `server.custom_views`, the documentation just hasn't been updated yet.

**Comment by cpare** [comment]
> TSC does have support already under `server.custom_views`, the documentation just hasn't been updated yet.

 IT WORKS!   Thanks for the quick reply!
