### ISSUE TITLE
Connection Credentials Needs Docs

### ISSUE THREAD

**Issue by benlower** [tableau/server-client-python#155]
Connection Credentials object has a property called "Name". Is this the name of the credential or the user name? I think it's the latter but needs to be doc'd.

If it's user name then let's rename the proper to 'username' :)

**Comment by t8y8** [comment]
Submit a PR :)

**Comment by d45** [comment]
I think we've got this one covered. We tell them that the "name" is the "username" in this case.   
https://tableau.github.io/server-client-python/docs/api-ref#connections 

We fixed the docs a while ago. If we update the name of the property, let me know! 
If people see a problem in the docs, they can click the "Submit and Issue" button at the top of the page. 
That's ok for the one-offs, but it might be nice to keep a master list for the next doc update.

**Comment by irwando** [comment]
Seems to be doc'd.  

Lets hold off on breaking changes here with a field rename. We can revisit when we auto-gen client libraries via TAG.
