### ISSUE TITLE
Can't specify "Default" site

### ISSUE THREAD

**Issue by tagyoureit** [tableau/server-client-python#161]
Using the following code

```
    # parser arguments per sample code
    parser.add_argument('--site', '-si', required=False, default='Default', help='site to use')

    # Step 1: Sign in to server.
    tableau_auth = TSC.TableauAuth(args.username, password)
    tableau_auth.site = args.site
    server = TSC.Server(args.server)
```
and specifying "Default" as a site (which is the default value in many samples (e.g. `python initialize_server.py -s http://localhost -u admin -si Default -wf . -df .`) throws a login error.

```
Traceback (most recent call last):
  File "API_demo.py", line 502, in <module>
    main()
  File "API_demo.py", line 104, in main
    with server_upload.auth.sign_in(tableau_auth):
  File "/Library/Python/2.7/site-packages/tableauserverclient/server/endpoint/auth_endpoint.py", line 29, in sign_in
    Endpoint._check_status(server_response)
  File "/Library/Python/2.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 54, in _check_status
    raise ServerResponseError.from_response(server_response.content)
tableauserverclient.server.endpoint.exceptions.ServerResponseError: 

	401001: Signin Error
		Error signing in to Tableau Server
```

Passing the empty string `''` DOES work to login to the Default site.  (e.g. `python initialize_server.py -s http://localhost -u admin -si '' -wf . -df .`)

**Comment by t8y8** [comment]
That's because you need to pass the "content_url" or "site_id", not the site 'name'.

This is the same behavior as tabcmd, though we acknowledge that it's difficult to discern that from the docs. Do you have any recommendations on how to make it better?

**Comment by tagyoureit** [comment]
The content URL for the Default site is `""` (an empty string).  However, the default is `"Default"` in the samples.  

Ideally, the contentUrl of `Default` would translate to the Default site (and hence, be the same as the name).  But short of that changing the default in the samples to match the contentUrl of the default site should help.

The fact that the contentUrl or ID is not displayed with the Default site (in the UI) doesn't help, but understand it is out of scope for this conversation.

Default site:
![2017-03-28_10-42-39](https://cloud.githubusercontent.com/assets/1646840/24419543/514be334-13a4-11e7-8030-a6d5b499cadd.png)

Any other site:
![2017-03-28_10-44-06](https://cloud.githubusercontent.com/assets/1646840/24419550/56d6e8da-13a4-11e7-91f1-6792ad1bfb92.png)

**Comment by t8y8** [comment]
Yup, that's a bug in the sample then.

**Comment by t8y8** [comment]
@benlower fix your sample :)

**Comment by SpaceRangerWes** [comment]
@t8y8 I'll also add that outside of the sample, the code and documentation makes it seem like the site id is what is required and not the content url.

An example would be 
```python
import tableauserverclient as TSC
tableau_auth = TSC.TableauAuth('username', 'password', site_id='site')
server = TSC.Server('http://servername')

with server.auth.sign_in(tableau_auth):
  all_workbook_items, pagination_item = server.workbooks.get()
  print([workbook.name for workbook in all_workbooks])
```
which is at https://tableau.github.io/server-client-python/docs/api-ref#workbooks

**Comment by t8y8** [comment]
The UI refers to the content_url as the 'site_id'.
Tabcmd also calls that the site id (the -t parameter).

We should unify all references to be the same so that it's clear across the Tableau ecosystem but that's beyond the scope of the api library, more of an internal work item.

**Comment by cobbjb** [comment]
It would be helpful if the sample code included passing the `site_id` parameter in the `tableau_auth` string.   I just spent more time than I'm willing to admit trying to figure out why I could not utilize the sample code properly, because the debug and error messages are not particularly informative.

**Comment by bcantoni** [comment]
Reviewing older issues, I believe we have addressed this one by rewriting the sign in / sign out topic to be more clear: https://tableau.github.io/server-client-python/docs/sign-in-out
