### ISSUE TITLE
Get usage statistics for Views

### ISSUE THREAD

**Issue by d45** [tableau/server-client-python#179]
Currently, there is no way to get usage stats for Views using the TSC library.  Getting usage stats would be helpful if you wanted to monitor how the site was being used.  The stats could identify popular content and content that wasn't viewed that could be removed, etc.  

You can retrieve the usage stats for views in the REST API by including a query in the URL in a GET request for views:  '?includeUsageStatistics=true'  

The TSC library is set up for storing this data, but it isn't implemented.  The ViewItem class has the attribute `total_views` , but there is no way to add the usage data.  To collect the data, you could add a new endpoint, similar to the `populate_views()` endpoint for workbooks, or you could modify the `views.get()` endpoint to return the data by default, or with a parameter.  Whatever works best with your design model. 

Here's one idea using a parameter: 

From `class Views`: 

```
   def get(self, req_options=None, usage=False):
          logger.info('Querying all views on site')
           url = "{0}/views?includeUsageStatistics={1}".format(self.baseurl,usage)
           server_response = self.get_request(url, req_options)
           pagination_item = PaginationItem.from_response(server_response.content)
           all_view_items = ViewItem.from_response(server_response.content)
           return all_view_items, pagination_item
```

This implementation works, but it changes the signature of the get method. It is false by default to mirror the REST API behavior. 

Cheers,
Dave

**Comment by RussTheAerialist** [comment]
implemented by #242
