### ISSUE TITLE
Converting CSV files to TDEs

### ISSUE THREAD

**Issue by seanbird2** [tableau/server-client-python#182]
Is there currently any functionality that allows a Tableau Server administrator to convert a CSV file to a TDE file?

**Comment by LGraber** [comment]
You can use the Extract API which comes as part of the Tableau SDK. There is not currently a REST API which allows you to just push raw data into a TDE.

**Comment by isajediknight** [comment]
Is there a plan to incorporate TDE creation into server-client-python library?  Or will the only way to do it be to use the Tableau SDK?

**Comment by RussTheAerialist** [comment]
TDE creation is outside of the scope of this API.  The Tableau SDK (and the extract API specifically) is the only way to create them, but both APIs do work well together, so you can create the extract and publish if from the same script.
