### ISSUE TITLE
Datasources.get() doesn't return all the datasources

### ISSUE THREAD

**Issue by MouradHRM** [tableau/server-client-python#185]
When I try to list all the datasources of a site, there are some included in a project that are ignored.
Eventhough this specific project is detected with Projects.get(), the datasources it contains are not visible through Datasources.get().

Same results when I used Postman.

The project doesn't have particular configurations.
What can be the cause ?

**Comment by RussTheAerialist** [comment]
That's by design.  We have pagination, so by default we only return the first 100 data sources.

The easiest way to get everything is to use the pager object which is detailed here: https://tableau.github.io/server-client-python/docs/page-through-results

**Comment by manugarri** [comment]
the answer is not right at all. Like @MouradHRM  said, datasources created inside specific projects dont show up when you call the api.
