### ISSUE TITLE
NAMESPACE is incorrect for API 2.0

### ISSUE THREAD

**Issue by Talvalin** [tableau/server-client-python#194]
Although the sign in method has been designated as an API 2.0 endpoint, signing in to a Tableau Server instance that uses an [API version of 2.0 (versions 8.3, 9.0 and 9.1)](https://onlinehelp.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm) will fail with the following error:

`site_id = parsed_response.find('.//t:site', namespaces=NAMESPACE).get('id', None)`   
`AttributeError: 'NoneType' object has no attribute 'get'`

Further examination shows that REST API 2.0 uses the `tableausoftware.com/api` namespace but the the namespace defined in [namespace.py](https://github.com/tableau/server-client-python/blob/master/tableauserverclient/namespace.py) is `tableau.com/api`.

Changing the namespace for REST API 2.0 calls appear to resolve the issue, but in terms of implementing a non-hacktastic fix, I have no idea.

**Comment by Talvalin** [comment]
Total hack workaround that seems to be working:

```
if server.version == 2.0:
    import tableauserverclient.server.endpoint.auth_endpoint as endpoint
    endpoint.NAMESPACE = {'t': 'http://tableausoftware.com/api'}
```

**Comment by t8y8** [comment]
Investigated a bit.

Only models rely on the namespace, requests, endpoints, and servers do not.

But Endpoints and Server objects are the natural place to pass namespace down via, models don't have a 'server version' they just have a document version.

We could:
1) Pass an attribute to models on construction that set the namespace (could just have a base model class that does this) and then set this from the server version attribute we already do.
2) We could do a dirty hack that trips namespaces from documents so it doesn't matter
3) We could not fix this (or implement it such that when the server version changes to 2.0 we perform @Talvalin's hack)

**Comment by RussTheAerialist** [comment]
I just checked in a fix for this.  It'll be in the 0.5 release.
