### ISSUE TITLE
content_url for views returned incorrectly

### ISSUE THREAD

**Issue by tagyoureit** [tableau/server-client-python#209]
This isn't actually documented, and not sure if it is a client library issue, but the content_url for views is returned incorrectly.  The issue is that `views.content_url` incorrectly adds a `/sheets` between the workbook and the sheet name.

```
        print("Your server contains the following workbooks:\n")
        for wb in TSC.Pager(server.workbooks):
            print('\nName {0}.  Project {1}  URL {2}'.format(wb.name, wb.project_name, wb.content_url))
            server.workbooks.populate_views(wb)
            print("\tName of views in {}: ".format(wb.name))
            for view in wb.views:
                print('Name: {0}  URL: {1}'.format(view.name, view.content_url))
```

The output is like...
```
Name Workbooks views and performance.  Project Default  URL Workbooksviewsandperformance
	Name of views in Workbooks views and performance: 
	Name: Publisher Stats  URL: Workbooksviewsandperformance/sheets/PublisherStats
        ....
```

The `/sheets` in the `view.content_url` is not needed, and fails with Tableau Server.  

Good:  `http://server/#/views/Workbooksviewsandperformance/PublisherStats`
Fails: `http://server/#/views/Workbooksviewsandperformance/sheets/PublisherStats`

All of the tests are looking for the `/sheets` as well.  Was this valid in a prior (<10) version of Tableau?

**Comment by t8y8** [comment]
This is by design -- that's the URL as it is stored in the postgres repository (under the hood that's the real url that gets passed to vizqlserver).

We could have the REST API strip it out -- I forget why we didn't originally; but that's a function of Server behavior, not TSC.

**Comment by tagyoureit** [comment]
Ok, well it's documented now... Closing.
