### ISSUE TITLE
How to get around this error? 

### ISSUE THREAD

**Issue by zizzojason** [tableau/server-client-python#211]
Source: move_workbook_projects.py

Code:

        # Step 3: Find destination project
        all_projects, pagination_item = server.projects.get()
        dest_project = next((project for project in all_projects if project.name == args.destination_project), None)

        if dest_project is not None:
            # Step 4: Update workbook with new project id
            if all_workbooks:
                print("Old project: {}".format(all_workbooks[0].project_name))
                all_workbooks[0].project_id = dest_project.id
                target_workbook = server.workbooks.update(all_workbooks[0])
                print("New project: {}".format(target_workbook.project_name))
            else:
                error = "No workbook named {} found.".format(args.workbook_name)
                raise LookupError(error)
        else:
            error = "No project named {} found.".format(args.destination_project)
            raise LookupError(error)

Error: 409013 Resource Conflict 

Cannot move the workbook '8e0aa7de-26e0-490b-9b62-1f4667a3946a' to project 'c38aaeb1-14cf-47aa-bb94-78c481832d9b'. A workbook with the name 'Book1' already exists in that project.

**Comment by RussTheAerialist** [comment]
Either rename the workbook you are moving, or rename the Book1 that exists in the destination project.

**Comment by jbz29** [comment]
This is to push updates from a QA environment to production. Keeping naming convention is important here.

**Comment by RussTheAerialist** [comment]
The error is pretty straightforward here.  You can't have a workbook named the same thing.

If you need to replace a workbook in your production environment with one from the QA environment, then you need to first delete the one in production and then move the one from QA to production.  You can either detect this error and then do the delete and redo the move, or find the production copy by name, and if it exists, delete it before moving.

If it was me, I would do it in 3 steps.  Rename the production workbook to something like [Name]_old, move from QA to production, delete [Name]_old.  This would ensure that if the move failed for some reason, you still have the original copy.

**Comment by JedEyeKnight** [comment]
overwrite-flag | (Optional) true to overwrite a workbook that has the same name, or false to fail if the specified workbook already exists. The default is false. If overwrite-flag is set to true but the workbook doesn't already exist, the operation succeeds.
-- | --


I understand the logic. Was hoping for direction to syntax documentation. Thanks again

**Comment by RussTheAerialist** [comment]
The rest api does not support the idea of overwrite on a workbook update which moving workbooks is an update.  Here is the documentation for the underlying rest call that we use for updating: https://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Update_Workbook

The snippet you provided is from the publish workbook, which you are not doing in your code: https://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Publish_Workbook%3FTocPath%3DAPI%2520Reference%7C_____51

If you wanted to go this route, you'd need to download the workbook and republish.  But keep in mind that if you republish, you need the username and password for the datasource in the workbook in order to be able to republish.

**Comment by LGraber** [comment]
This is an interesting scenario where you try to update the workbook by moving it from one project to another and it exists in the other project. I can see how it would be a bit confusing that we have "overwrite" flag for publish but not update when update can allow you to move it. This is something we could take a look at (there might be some reason other reason that this isn't there but I can't think of it). Why don't you go ahead and reopen an issue for us to indicate that perhaps we should add support for overwrite flag on the update endpoint to handle the case where it is being moved. Thanks and I hope Russell's answer gave you enough info to get it done.

**Comment by ZizzoIsRad** [comment]
I'm actually still having trouble as this is really my first introduction 
to using Python and TSC. 



Here is my Code: 
I have been trying to find where to insert the workbooks.delete to remove 
the overwrite issue. 

---------------------------------------------------------------------------------------------------------------------------------------------------

import tableauserverclient as TSC
import logging
import argparse
import getpass


tableau_auth = TSC.TableauAuth('Username', 'Password')
server = TSC.Server('http://1000.000.000.000/')

# with server.auth.sign_in(tableau_auth):
#     all_datasources, pagination_item = server.datasources.get()
#     print("\nThere are {} datasources on site: 
".format(pagination_item.total_available))
#     print([datasource.name for datasource in all_datasources])

tags = 'Book1'
destination_project = 'Outreach'
workbook_name = 'Book1'
logging_level ='info'

def main():




        with server.auth.sign_in(tableau_auth):



                req_option = TSC.RequestOptions()
 req_option.filter.add(TSC.Filter(TSC.RequestOptions.Field.Tags,
 TSC.RequestOptions.Operator.Equals,
                                        tags))


                matching_workbooks, pagination_item = 
server.workbooks.get(req_option)

                #print(matching_workbooks[1].project_name)

                # Step 3 Find Destination Project 

#Find destination project
                all_projects, pagination_item = server.projects.get()
                dest_project = next((project for project in all_projects 
if project.name == destination_project), None)
                print("Project Destination: {} 
".format(dest_project.name))

                matching_workbooks[0].workbooks.delete = 
server.workbooks.matching_workbooks.delete



                if dest_project is not None:
                        if matching_workbooks:
                                print("Old project: 
{}".format(matching_workbooks[0].project_name))
                                matching_workbooks[0].project_id = 
dest_project.id
                                target_workbook = 
server.workbooks.update(matching_workbooks[0])
                                print("New project: 
{}".format(target_workbook.project_name))
                        else:
                                error = "No workbook named {} 
found.".format(workbook_name)
                                raise LookupError(error)
                else:
                        error = "No project named {} 
found.".format(destination_project)
                        raise LookupError(error)
main()
