### ISSUE TITLE
Design Proposal: Move 'populate methods' to the parent objects from the Endpoints

### ISSUE THREAD

**Issue by t8y8** [tableau/server-client-python#24]
Today there are several properties that are unpopulated (views on workbooks, connections in workbooks) until you call a populate method.

That makes sense, it requires a new API call.

However, the logic is hidden up on the endpoint and not on the object itself. I think it's a little unintuitive.

Example:

```
_, wbs = server.workbooks.get()
wb = wbs.pop()
wb.name
>>> '1234-5678-123456'
wb.views
>>> UnpopulatedPropertyError
```

To get that populated you would call

```
server.workbooks.populate_views(wb)
```

But it feels a bit weird, because the method sort of implies I'm populating on the workbooks endpoint.

More naturally, it could be

```
wb.populate_views()
wb.views
>>> [<view obj>, <view obj>]
```

Or even call that automatically on access of `wb.views` for the first time

**Comment by irwando** [comment]
Old proposal which seems to have been implemented long ago.
