### ISSUE TITLE
Workbook Publishing - Connection reset by peer error

### ISSUE THREAD

**Issue by jethomas84** [tableau/server-client-python#241]
I have a set of workbooks and data-sources that i can publish to one server with no issues. Then when I try to publish to another server one of the workbooks always triggers the following error message:

> Traceback (most recent call last):
>   File "migrate_local_workbooks.py", line 183, in <module>
>     main()
>   File "migrate_local_workbooks.py", line 148, in main
>     new_workbook, wb, mode=TSC.Server.PublishMode.Overwrite,connection_credentials=new_connection)
>   File "/tableau-migration/tableauserverclient/server/endpoint/endpoint.py", line 110, in wrapper
>     return func(self, *args, **kwargs)
>   File "/tableauserverclient/server/endpoint/workbooks_endpoint.py", line 189, in publish
>     server_response = self.post_request(url, xml_request, content_type)
>   File "/tableauserverclient/server/endpoint/endpoint.py", line 80, in post_request
>     content_type=content_type)
>   File "/tableauserverclient/server/endpoint/endpoint.py", line 43, in _make_request
>     server_response = method(url, **parameters)
>   File "/tableau-migration/requests/sessions.py", line 555, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/tableau-migration/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File /tableau-migration/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/tableau-migration/requests/adapters.py", line 493, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

Now, the workbook does eventually show up on the server, but this error will cause my python publishing script to fail. Any help would be appreciated. One of the only differences I can think of is the second server has SSL enabled whereas the first one does not.

Thanks.

**Comment by RussTheAerialist** [comment]
Is there a difference in the network between the machine where you are publishing and the two servers?  Connection Reset by Peer means that the remote server (in this case, it could be the tableau server or it could be a firewall, router, switch, or something else) terminated the connection.

**Comment by jethomas84** [comment]
Yes, good point. The servers are not on the same network or location. What I'm trying to figure out is what is the weird variable that causes the connection termination - or can this be mitigated on the publish script side by some sort of keep-alive or reconnect feature? Or, is there a way to gracefully skip past this error because the files do publish in spite of the connection termination.

**Comment by RussTheAerialist** [comment]
I know we have some changes in flight that will allow us to be more resilient against this type of error, but I'm not sure when those will be ready for the public.  We don't currently have keep-alive or reconnect abilities for this situation.

To handle it as gracefully as possible, you can catch the requests.exceptions.ConnectionError and inspect the error code to see if it's 104, and then if it is, either retry, assume it's finished, or inspect the server to see if you need to retry.

Does it always error out on the workbook for the second server or is it intermittent?  Does the workbook have an extract?  If so, how big is the extract?

**Comment by jethomas84** [comment]
These workbooks all use published data-sources that are just pointing to views in a database. The script first publishes the data-sources, then the workbooks. All of the files are relatively tiny (none larger than 200k). 

It always happens with this one particular workbook but it will intermittently happen with the other workbooks. After retrying, those other ones do not encounter this error usually.

I was thinking the same thing about catching that error, but being new to python, I'm having trouble making that work. Would you happen to be able to point me in the right direction for that type of change?

Thanks.

**Comment by t8y8** [comment]
I would look on the Server logs, there might be a deeper server-side error involved and the client error is a red herring.

**Comment by irwando** [comment]
Closing old issues.
