### ISSUE TITLE
Query connected published datasources for a workbook

### ISSUE THREAD

**Issue by benjaminschalk** [tableau/server-client-python#247]
Hi, 
this is my first issue on Github, so apologies in advance if this doesn't meet the guidelines. 

I have a question for a scenario which is: 
I have a workbook on my Tableau Server that connects to a published datasource. I want to download it and upload it to another Site. On this other site, the published data source is not yet available.  

So I'd like to 
1) download the workbook, then 
2) download the connected published datasource, then 
3) publish that datasource to the second site and finally 
4) publish the workbook to the second site which now connects to the newly published datasource.

I couldn't find a way to query the datasource ID in the workbook, as the datasource ID I can get out of the connections doesn't correspond to the datasource ID of the actual published datasource. 

I also observed that the datasource name I get out of the connections of the workbook are obtained from the caption of the XML which could be renamed locally in the workbook so it can't be used for querying the datasource reliably. 

Please find attached some sample code for my localhost.

Is there any way to connect these two? Any help would be greatly appreciated!

Cheers, 
Ben

[Github issue.txt](https://github.com/tableau/server-client-python/files/1582430/Github.issue.txt)

**Comment by dgoldsb** [comment]
I ran into the same problem. Looking into the XML-structure of a workbook, it seems that the `dbname` attribute under the `connection` tag contains a unique identifier that is included in the datasource in the `id` attribute under the `repository-location` tag. This is not the same as the datasource IDs that are used in the API, but a version of the datasource name without space, and a suffix in the case that the datasource name is not unique on the site.

I am not sure myself either how to relate the datasource ID stored in the `ConnectionItem` and the datasource ID stored in the `DatasourceItem`.

**Comment by irwando** [comment]
Please reopen if this is still an issue.  

Using TSC you can populate_connections on a workbook.  You can iterate through the connections and find any that connect to dataengine which will be a published data source.
