### ISSUE TITLE
all_workbook_items reference

### ISSUE THREAD

**Issue by dlpate2525** [tableau/server-client-python#249]
Example

Fix the reference to all_workbooks_items in the print statement

import tableauserverclient as TSC
tableau_auth = TSC.TableauAuth('username', 'password', site_id='site')
server = TSC.Server('http://servername')

with server.auth.sign_in(tableau_auth):
  all_workbook_items, pagination_item = server.workbooks.get()
  print([workbook.name for workbook in **all_workbooks_items**])

**Comment by RussTheAerialist** [comment]
I believe this is fixed with PR#251.  The docs will be updated once we push a new version which should happen later this week.
