### ISSUE TITLE
Where do you fill in the connection details

### ISSUE THREAD

**Issue by JasonS17n** [tableau/server-client-python#256]
Looking at this example https://github.com/tableau/server-client-python/blob/master/samples/download_view_image.py, i'm not sure exactly where in the code do you fill in the details of the server, username, and password. Can someone provide a sample with filled in information? 

Thanks.

**Comment by RussTheAerialist** [comment]
Line 43 & 44 are where the credentials for the server are filled in from the command line arguments that are being passed in.  On line 43, you are creating an authentication object which takes the username, password, and optionally site, and then line 44 is where you pass in the server url.

This just sets things up, line 48 is the first call to the server where you login and get an authentication token which is used for the rest of the calls.

**Comment by irwando** [comment]
Question was answered. Closing.
