### ISSUE TITLE
Datasource Refresh Fails because of empty_req function (see solution below)

### ISSUE THREAD

**Issue by dieselpwr** [tableau/server-client-python#257]
In tableauserverclient/server/request_factory.py line 404, myself and a colleague found an issue with the empty_req function within the EmptyRequest class. The issue presented itself when attempting to perform a datasource refresh which uses this function. We believe the empty_req function definition should include the "self" argument in addition to "xml_request". This fix worked for us.

request_factory.py line 404 before the fix:
    def empty_req(xml_request):

request_factory.py line 404 after the fix:
    def_empty_req(self, xml_request):

**Comment by RussTheAerialist** [comment]
Oh dang, I thought I caught all of those and fixed it.  Thanks!  I'll get a fix in place and release a bugfix version this week.

**Comment by RussTheAerialist** [comment]
Fixed in v0.6.1
