### ISSUE TITLE
Differentiate a view from a dashboard

### ISSUE THREAD

**Issue by benlower** [tableau/server-client-python#259]
For both 'Query Views for a Site' & 'Query Views for a Workbook' add information to differentiate between a dashboard and a view.

**Comment by shinchris** [comment]
We are working on making view SheetType available for the next release of our REST API, version 2.9. SheetType field would indicate whether a view is a Dashboard, View, or Story.

SheetType would be available for querying for the 'Query Views for Site' endpoint, by using the fields parameter (e.g. ?fields=sheetType or ?fields=_all_).

**Comment by jacalata** [comment]
This attribute has been available since at least API v3.0
