### ISSUE TITLE
Change default limit of 'pagination_item'

### ISSUE THREAD

**Issue by jeevantm** [tableau/server-client-python#261]
Hi,

Can we customize the default limit of 'pagination_item', like set it to 200, 300, all..? If yes please share how it can be done. Thanks!

If this is not the right way/place/page  to ask questions and improvements please move this thread to correct page and share the link for the same.

**Comment by t8y8** [comment]
Hello @jeevantm!

Can you explain why you want to change the default?

In any script you can do:
```
options = TSC.RequestOptions(pagenumber=300)
```

Or better yet, use Pager:
```
for item in TSC.Pager(server.workbooks):
    ...
```

And let pager manage the paging for you.

**Comment by irwando** [comment]
Closing out old issues.  @t8y8 's response seems reasonable.

**Comment by jeevantm** [comment]
Hi,

I am sorry I'm commenting on this after long time, but the TSC.Pager doesn't seem to work properly with RequestOptions.

I have set request_options = TSC.RequestOptions(pagesize=1000) and when I do -
for schedule in TSC.Pager(server.schedules, request_options), although I have less than 1000 schedules but more than 500 schedules (622 to be precise), it doesn't give all schedules in a single page. It returns less than 500 schedules instead of 622.

Could you please check why. Many thanks!

**Comment by t8y8** [comment]
What happens when you set the request options to 1000 and don't use pager?

I'll review the pager code, but it's pretty old and baked, my guess is that schedules might have an issue on the Server side.

**Comment by jeevantm** [comment]
Hi, 

I am using RequestOptions(pagesize=1000) in TSC.Pager(server.schedules, request_options) and I receive the below error - 

400006: Bad Request
                Invalid page number '2'

In my case there are less than 1000 objects to return, why is it even going to page number 2 even if I gave the pagesize to be 1000. 

Thanks for your help!
