### ISSUE TITLE
How to use the API to generate a visual chart ？

### ISSUE THREAD

**Issue by Feeeenng** [tableau/server-client-python#262]
Hi:
I can not find the relevant method !
I can get ID and ID of the workbook, but I do not know how to generate a visual chart based on these two parameters. 
  Are there any simple examples that can help me? thank

**Comment by benlower** [comment]
The [download_view_image](https://github.com/tableau/server-client-python/blob/master/samples/download_view_image.py) sample shows how to get the PNG image for a view. Is that what you were looking for?

**Comment by Feeeenng** [comment]
@benlower thank. the question has been solved
