### ISSUE TITLE
Support for porject hierarchies

### ISSUE THREAD

**Issue by sotnich** [tableau/server-client-python#265]
In Tableau 10.5 there is now a new feature that allows to make nested projects https://www.tableau.com/about/blog/2017/12/get-ready-tableau-105-projects-within-project-78906.
But here in TSC the ProjectItem does not contain any properties that can show where the project is (is it root or is it subproject).
Good idea is to add parent_project attribute to the ProjectItem.
Is this possible and is this requires to change Tableau API because just now I can't find related method in Tableau API.

**Comment by t8y8** [comment]
https://github.com/tableau/server-client-python/commit/0b497d929fbbf971cfa1960ba09f79d65c2e9e25

Added support for 'parent_id' which identifies the parent project for a child project

**Comment by sotnich** [comment]
Thanks, but parent_id alwais None.
I think there are two reasons:
1. TSC uses 2.3 version of API and only in 2.8 there is parentProjectId attribute in response XML.
2. Method _parse element uses not correct name - it uses "parentId" instead of "parentProjectId"

``` python
def _parse_element(project_xml):
  id = project_xml.get('id', None)
  ...
  parent_id = project_xml.get('parentId', None)
```

Is it possible to move to 2.8 version of API?

**Comment by sotnich** [comment]
Make a PR https://github.com/tableau/server-client-python/pull/267

**Comment by irwando** [comment]
PR was merged log ago/ Cleaning up old issue.
