### ISSUE TITLE
Get workbook/data source by content URL?

### ISSUE THREAD

**Issue by jpoehls** [tableau/server-client-python#268]
In the REST API, is there a way to get a single workbook or data source via its content URL? Currently we are using the methods to list all workbooks just to find the ID which is pretty inefficient since we already have a site unique content URL.

Thanks.

**Comment by LGraber** [comment]
How did you get the content URL? There are a set of "filters" you can apply to the get call to indicate which workbooks you want. We don't have a filter on contentUrl but we have filters on name, owner, and some other items. Perhaps you have those? So back to the original question ... how did you get the contentUrl?

**Comment by jpoehls** [comment]
One example would be from the Tableau Server log files which include the site and workbook/data source content URL in certain messages. The use case would include parsing those messages and then querying the REST API for details.

A second example might be when parsing the TWB/TDS file which sometimes includes the `repositoryUrl`. A use case may include parsing that from the file and then querying the REST API for details of the server's copy of that workbook or data source.

**Comment by t8y8** [comment]
Maybe we should log the LUIDs so you just have them available.

contentURLs don't have a good contractual guarantee to stay a good identifier (I know they behave this way today, but there's no promise they will continue)

**Comment by irwando** [comment]
Should be coming in 2019.4

**Comment by mhadi813** [comment]
is there any update on this request? I want to retrieve datasources from the url
Thanks

**Comment by mfarragher** [comment]
Is this implemented yet?

When I access `webpage_url` attribute across datasources none of them has a value.  They all have a `content_url` though, but that's not what I'm after.

What I'd want to access is the `<INTEGER>`  from a datasource URL of this format:

```
https://<WEBSITE>/#/datasources/<INTEGER>
```

This would make data management a lot easier.  It's quite painful having to search by name each time in the server when you want to inspect a datasource. 😣

**Comment by jacalata** [comment]
Get workbook by content url has been available for a while - https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooks_and_views.htm#query_workbook

Querying workbooks or datasources also allows you to filter based on the contentUrl - https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_filtering_and_sorting.htm#datasources

**Comment by maxim-k** [comment]
@jacalata as for `tableauserverclient=0.26` and `tableauhyperapi=0.0.16868` it returns `null` for `datasource.webpage_url`
