### ISSUE TITLE
 Replacing Field Reference

### ISSUE THREAD

**Issue by ismailsimsek** [tableau/server-client-python#270]
Thank you for the great API

is it possible to "Replace Field References" in a workbook with SC-API .
we have data-source which has more than 100 workbook connected to it and we like to automate "Replace Field References" feature whenever we rename a field in the data-source. replacing field references workbook by workbook is too much work and we like to automate it.

How to Replace References When Your Field Names Change : http://www.vizwiz.com/2017/06/replace-references.html

**Comment by t8y8** [comment]
Replacing field references would be more appropriate for https://github.com/tableau/document-api-python

The Server Content API only manages things that 'Server' knows how to deal with, stuff inside the visualization is out of its scope.

It's a great feature request though, you like to repost the idea on the document-api list (I can do it I just want your username to get credit)

**Comment by ismailsimsek** [comment]
Thank you @t8y8 since activity on document api was low i thought it will be good idea to post here.

i opened same request there too https://github.com/tableau/document-api-python/issues/148

**Comment by irwando** [comment]
Closing as this is, as stated, appropriate for Document API.
