### ISSUE TITLE
Update Project removes parent project when none is included in the request body

### ISSUE THREAD

**Issue by NinetiesGuy** [tableau/server-client-python#271]
When calling the Update Project method with no explicit `parentProjectId` value in the body of the request, the parent will be set to null, moving the project up to the top level.

The docs say 

> Any combination of the attributes inside the <project> element is valid. Only those attributes present will result in updates to their values in the project. If no attributes are present, then the update won't have an effect.

So when you do `<tsRequest><project/></tsRequest>` in the body (essentially a fake GET request), I would expect for that to just return the project with the LUID in the URL and not do an actual update.

Another side effect of this issue is that you can't do "fake GETs" on child projects that share the same name as any top-level project, as it will return a failure because that project name already exists.

To sum it all up, the update project method is treating **no** `parentProjectId` as a **null** parent when no value and a null value should be treated differently.

**Comment by t8y8** [comment]
I'm not sure if this is Server behavior, API behavior, or client library behavior.

Thank you for reporting, we will take a look!

@jimbodriven did the client work and the API work, @RussTheAerialist may know as well

**Comment by RussTheAerialist** [comment]
this definitely is a bug in the server.  @NinetiesGuy do you know which version of tableau server you are running?  If not, can you send us the output of `/api/2.4/serverInfo` so we can make sure we fix it in the correct versions

**Comment by NinetiesGuy** [comment]
Server 10.5.0/REST API 2.8. I'm pretty sure it's in the 2018.1 beta as well. I'll double-check and get back to you on that.

**Comment by NinetiesGuy** [comment]
Confirmed on 2018.1 beta (REST 2.8) as well.

**Comment by jimbodriven** [comment]
I have copied this information into the content management team's backlog in tfs  as well (see 750045).

**Comment by irwando** [comment]
Should be fixed against a 2018.2 server.
