### ISSUE TITLE
There is no workbook refresh method

### ISSUE THREAD

**Issue by sotnich** [tableau/server-client-python#272]
In API version 2.8 there is the method http://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Update_Workbook_Now. But in workbooks_endpoint.py there is no such method.

I can implement it.

```python
@api(version="2.8")
def refresh(self, workbook_item):
  url = "{0}/{1}/refresh".format(self.baseurl, workbook_item.id)
  empty_req = RequestFactory.Empty.empty_req()
  server_response = self.post_request(url, empty_req)
  new_job = JobItem.from_response(server_response.content, self.parent_srv.namespace)[0]
  return new_job
```

Also there is a need to fix request_fuctory.py->EmptyRequest because there'is an error - wrapper needs two parameters, not one

```python
class EmptyRequest(object):
    @_tsrequest_wrapped
    def empty_req(self, xml_request):
        pass
```

**Comment by RussTheAerialist** [comment]
@sotnich I thought I fixed the empty_req bug a while ago.  Are you working with the latest development branch?

**Comment by t8y8** [comment]
Specifically, https://github.com/tableau/server-client-python/blob/development/tableauserverclient/server/endpoint/workbooks_endpoint.py#L54

Has the functionality requested -- we just haven't done a release to master yet (though @RussTheAerialist's fix appears to be in master too -> https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/request_factory.py#L404)

**Comment by sotnich** [comment]
Thanks, my mistake. I missed those changes in development branch.
