### ISSUE TITLE
This log line is overly chatty

### ISSUE THREAD

**Issue by grbritz** [tableau/server-client-python#273]
https://github.com/tableau/server-client-python/blob/608aa7694d0560ea3c8c37b10127b11207e56e8d/tableauserverclient/server/endpoint/endpoint.py#L53

When using server client python to download workbooks or data sources and you've got log_level=Debug, this log line ends up blowing up your logs. It outputs the hexadecimal representation of the entire file you're downloading, which is not very helpful and explodes your log size. Can we remove this line, or only log out the response contents when you're not using the endpoint to download a file?

**Comment by t8y8** [comment]
Ideas:
1. We override _check_status for `Workbook` and `DataSource` endpoints that do something to deal with binary responses
2. We check `server_response.headers['content-type']` for `binary` type and truncate or drop it before we log

**Comment by t8y8** [comment]
Fixed in development @ #274
