### ISSUE TITLE
Update a group

### ISSUE THREAD

**Issue by sotnich** [tableau/server-client-python#277]
What about method [Update group](https://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Update_Group%3FTocPath%3DAPI%2520Reference%7C_____95)?
There is no one in groups_endpoind.
I can create a PR if needed.

**Comment by t8y8** [comment]
We'd be happy to take a look at a PR.

I suspect the reason it wasn't added was because it's a little complex with AD vs Local auth Servers.

Could you post your proposed API design (Signatures in both cases, maybe types) here before you spend too much time building out a PR?

**Comment by sotnich** [comment]
I think that I need to add function update to groups_endpoint.py:

```python
def update(self, group_item):
  url = "{0}/{1}".format(self.baseurl, group_item.id)
  update_req = RequestFactory.Group.update_req(group_item)
  server_response = self.put_request(url, update_req)
  logger.info('Updated gropu item (ID: {0})'.format(group_item.id))

```

**Comment by sotnich** [comment]
And define in request_factiory.GroupRequest something like this:

```python
def update_req(self, group_item, default_site_role):
  xml_request = ET.Element('tsRequest')
  group_element = ET.SubElement(xml_request, 'group')
  group_element.attrib['name'] = group_item.name
  if group_item.domain_name != 'local':
    project_element = ET.SubElement(group_element, 'import')
    project_element.attrib['source'] = "ActiveDirectory"
    project_element.attrib['domainName'] = group_item.domain_name
    project_element.attrib['siteRole'] = default_site_role
  return ET.tostring(xml_request)
```

**Comment by sotnich** [comment]
@t8y8, what would you say about my design? 
I'm ready to make a PR)

**Comment by t8y8** [comment]
I'm on vacation so this is just a quick glance but it looks like a reasonable direction!

We want the request to be able to handle the local auth case as well... (I'm a but fuzzy on details for what that case even allows...) Any ideas there?

**Comment by t8y8** [comment]
Ignore that last comment. Your code handles that.

Would you be able to implement the jobId and status tracking code as well (I think it's ok if that's a second PR, but wondering if you'd like to)

**Comment by sotnich** [comment]
@t8y8, ok, sure, no problem, I'll implement jobId and status!

**Comment by t8y8** [comment]
Cool, thanks!

You should implement the "synchronous" case first and submit a PR, then do the jobId stuff in a second PR, I suspect it would require more discussion/iteration so may as well land the other stuff first.

**Comment by sotnich** [comment]
Created https://github.com/tableau/server-client-python/pull/279

**Comment by irwando** [comment]
Closing as the merge was completed.
