### ISSUE TITLE
Overwrite workbook with the Update Workbook Endpoint

### ISSUE THREAD

**Issue by landonconover** [tableau/server-client-python#280]
When moving a workbook from one project to another using the Update Workbook Endpoint, if there is a workbook in a project with the same name I get the following error:
`summary: [ 'Resource Conflict' ]`

What I would like to see is an attribute to overwrite the workbook in the destination project. 
Example:
```
<tsRequest>
    <workbook showTabs="show-tabs-flag" overwrite="true" > 
        <project id="new-project-id" /> 
        <owner id="new-owner-id" /> 
    </workbook>
</tsRequest>
 ```

Note: The reason why this would be really helpful is that workbooks in the destination project (Prod) are all embedded in a public website via the URL via Trusted Ticketing. The Workbook with the same name in the original folder (Dev) has a different URL than in Prod. Deleting the workbook from Prod and then moving the Dev version, results in updating ht HTML on the website due to how Tableau Server handles multiple workbooks with the same name in different projects.

**Comment by landonconover** [comment]
Hey guys? Is there any word on this?

**Comment by irwando** [comment]
Workbook names have always been unique in a project.  Need to consider options here carefully as it could have unintended side effects.

**Comment by jacalata** [comment]
I don't think we will ever implement this, because we aren't sure if it would break things. 

One workaround might be to download and re-publish the new workbook with the same name - there is an overwrite flag for publishing.
