### ISSUE TITLE
problem with connections[0].server_port( server_port is not updating on the tableau server)

### ISSUE THREAD

**Issue by harish2493** [tableau/server-client-python#281]

**Comment by shinchris** [comment]
Thanks for catching this! I've created a pull request to address this issue.

**Comment by harish2493** [comment]
@shinchris : still it is not updating the server port on tableau server. I have refresehed the browser but still I am not able to see updated values on Tableau server. Can u re-verify the code whether it is updating the server port on the tableau server or not ?

**Comment by shinchris** [comment]
Did you use the 'development' branch, instead of 'master'? I made changes to the 'development' branch and locally tested the fix to make sure server port is updated correctly.

**Comment by t8y8** [comment]
This function isn't intended to be called publicly `server.datasources._get_datasource_connections(datasource)` it's possible that might have something to do with it.

**Comment by t8y8** [comment]
```
server.datasources.populate_connections(datasource)
connections = datasource.connections
print(", ".join(str(x) for x in connections)
```

**Comment by irwando** [comment]
Issue should be long fixed. CLosing.
