### ISSUE TITLE
is there any api can Refresh Extracts a datasource ?

### ISSUE THREAD

**Issue by zzqq1** [tableau/server-client-python#287]
is there any api can Refresh Extracts a datasource ?
I hope there is a python api that can Refresh Extracts a datasource and wait for the Refresh finish then return it's status

**Comment by LGraber** [comment]
sure. I took a look at our sample (refresh.py) and realized that while it is "elegant" python, it might not be super easy to understand. Your code would look something like

tableau_auth = TSC.TableauAuth(args.username, password, args.site)
server = TSC.Server(args.server, use_server_version=True)
with server.auth.sign_in(tableau_auth):
    // First you need to get the datasource you want to refresh. There are samples for this
    job = server.datasources.refresh(ds)
    // Then you can put in some type of loop getting an update of the job and checking its 
   // finish_code and completed_at values
    job = server.jobs.get(job.id)

**Comment by happyshows** [comment]
just want to correct the code, it should be:
```
resource = server.datasources.get_by_id(datasource_id)
job = server.datasources.refresh(resource)
server.jobs.get_by_id(job.id)
```

**Comment by jwalin** [comment]
anyone know from where I can get datasource_id in tableau
