### ISSUE TITLE
Problem with downloading datasources. Datasources exist in workbook, but not in project

### ISSUE THREAD

**Issue by mdvjd** [tableau/server-client-python#293]
Hello, my problem is that I have a project on my Tableau Server, which displays that it has no datasources. But the containing workbooks do have some datasources, which are also shared by some of them.

I've tried to download these workbook datasources by querying the connection-ids and then trying to download them by calling 
`datasources.download(connection.id)`

But it doesn't seem to work due to the problem that the download function only searches for datasources in the project-level.

I'ld be thankful if there is anyone who could help me with that!

EDIT: I would generally like to operate on workbook-level than on project-level.

**Comment by omer-farooq1** [comment]
I am having similar issue. I am trying to download a datasource hyper file that is in the project. Code below:

` server.datasources.populate_connections(my_dataset)
  server.datasources.download(my_dataset.connections[0].id)`

It is not working. it says resource not found. But I can clearly see that it's a valid Id when I print it. Did you figure this out?

**Comment by martinsuijs** [comment]
Have the same issue:

            ds = server.datasources.get_by_id('c90daa61-49bf-4a64-bfd4-b6daace6cbf4')
            server.datasources.populate_connections(ds) 
            path = server.datasources.download(ds.id)

tableauserverclient.server.endpoint.exceptions.ServerResponseError: 

        404004: Resource Not Found
                Datasource 'c90daa61-49bf-4a64-bfd4-b6daace6cbf4' could not be found

datasource does exist
Is this a bug?
Please fix. 
It's needed to setup CI/CD

**Comment by m4n1-code** [comment]
Has this been resolved? I'm facing the same exact issue and not sure how to fix this.

**Comment by jonathan-dufault-kr** [comment]
facing the same issue. data source exists and I can't download it using the client

**Comment by SathyanarayanaGowda** [comment]
I am facing the exact issue, datasource does exist. But I am not able to download the datasource using tableauserverclient version 0.29.


server.workbooks.populate_connections(workbook)
for datasource in workbook.connections:
       ds = server.datasources.get_by_id(datasource.datasource_id)
       server.datasources.populate_connections(ds)
       file_path = server.datasources.download(ds.id)

Can someone please fix this ASAP.

If anyone have able to do this successfully, please let me know.

**Comment by jesshitchcock** [comment]
Running into this exact same issue. I guess I will have to use a different method to download data sources.
