### ISSUE TITLE
Getting Task Time Out Error connecting to Tableau Server

### ISSUE THREAD

**Issue by ankesh5** [tableau/server-client-python#295]
Hi,
I am getting below error when i am trying to use Tableau Server Client while connecting from AWS lamda Function, the same code works for me when trying to run on my local PC on Windows.

START RequestId: 99985d83-5da0-11e8-aca9-97b9d5240ab5 Version: $LATEST
END RequestId: 99985d83-5da0-11e8-aca9-97b9d5240ab5
REPORT RequestId: 99985d83-5da0-11e8-aca9-97b9d5240ab5	Duration: 60060.22 ms	Billed Duration: 60000 ms 	Memory Size: 128 MB	Max Memory Used: 33 MB	
2018-05-22T09:15:58.887Z 99985d83-5da0-11e8-aca9-97b9d5240ab5 **# Task timed out after 60.06 seconds**

kindly help .

**Comment by t8y8** [comment]
What is the action the code is performing?

Can you run the script with the TSC logging set to debug and attach that information?

**Comment by irwando** [comment]
No response in over a year. Closing this issue. Please reopen if it is still an issue.
