### ISSUE TITLE
Publishing workbooks does not work for nested projects

### ISSUE THREAD

**Issue by Lamby123** [tableau/server-client-python#301]
When publishing a large twbx file to nested projects (approx 500MB) the publication fails. The error message produced is not very helpful. 

If I publish the same file to a top level project the publication works as expected. 

The strange thing is that I am able to deploy some workbooks to nested projects, it only appears to be affected when I publish large workbooks.  

I am able to publish using the example provided on the Rest API GIT Hub page however ideally I would like to use TSC for everything instead of mixing and matching.

**Comment by RussTheAerialist** [comment]
Does the publishing to a root project work for the large files? (i.e. is it only getting an error on nested projects or also when publishing to a root project)

Even if the error message seems not helpful, could you include it?  It will help direct our debugging efforts.

**Comment by irwando** [comment]
Closing Issue > 1yo with no response. Please open a new issue for this if it sitll applies.
