### ISSUE TITLE
Missing new version declaration in the server.py

### ISSUE THREAD

**Issue by marcomix54** [tableau/server-client-python#304]
The server.py file is still stating the last version ('10.0': '2.3').
Appending the new version of the REST API.

**Comment by irwando** [comment]
After 10 we added the serverInfo call to get version information:

https://onlinehelp.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#server_info

These values are only used for legacy versions before this call was implemented.  As such we had no reason to update them.

Please open a requests with details of why you would want this updated if it is still an issue.
