### ISSUE TITLE
Add an instruction to use the newer API version for new site roles

### ISSUE THREAD

**Issue by marcomix54** [tableau/server-client-python#306]
Hi,

I didn't know I had to use server.use_server_version() to use the new site role names in server.users.add().
Can you please add a note to the documentation.

Thanks,
Marc

#305

**Comment by t8y8** [comment]
Ah! Yes we should document that more clearly. Would you like to submit a PR based on the gh-pages branch? (That's where docs live) @d45 should be able to help with any questions you have on docs :)

**Comment by irwando** [comment]
None of the docs talk about the new server roles or how to use them.  We need to update.  We should include:
- What the new roles are
- Which version and greater (3.0) they can be used

**Comment by bcantoni** [comment]
The new roles were added to the docs via #300. If there are further improvements we could make there, please file a new issue.
