### ISSUE TITLE
Missing parameter in /usr/local/lib/python2.7/dist-packages/tableauserverclient/server/request_factory.py

### ISSUE THREAD

**Issue by dmstubbs** [tableau/server-client-python#309]
Found an error in the above file in

def publish_req_chunked(self, datasource_item, connection_credentials=None):
           xml_request = self._generate_xml(datasource_item, connection_credentials, connections)
           parts = {'request_payload': ('', xml_request, 'text/xml')}
           return _add_multipart(parts)

which is related to uploading larger tde files and I was getting failures when I tried to upload a tde to the server.  Tracing the calling method it is missing "connections"

I modified the method to:

def publish_req_chunked(self, datasource_item, connection_credentials=None, connections=None):
         xml_request = self._generate_xml(datasource_item, connection_credentials, connections)
         parts = {'request_payload': ('', xml_request, 'text/xml')}
         return _add_multipart(parts)

and I was able to use the library to upload my tde file to the server.

**Comment by irwando** [comment]
Should be released. Closing.
