### ISSUE TITLE
Publish only specific views from workbook

### ISSUE THREAD

**Issue by julien10** [tableau/server-client-python#315]
Hi, I've been searching for a way to publish only specific views from a workbook on Tableau Server, but couldn't find a way to do that.

Is it currently feasible ? If yes, how ? If not, it would be nice to see that functionality added !

Thanks a lot !

**Comment by RussTheAerialist** [comment]
It's not currently supported in the Rest API.  The only way to do this, currently, is through desktop.  We are adding that functionality in a future release (2018.3 most likely) and TSC will support it at that point.

**Comment by irwando** [comment]
This was added to the REST API's.  We should plumb it through.

https://onlinehelp.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooksviews.htm#publish_workbook

**Comment by jacalata** [comment]
This was completed in https://github.com/tableau/server-client-python/pull/614
