### ISSUE TITLE
Download data source as .csv directly

### ISSUE THREAD

**Issue by sj-porter-dev** [tableau/server-client-python#318]
**As a** Python and Tableau Server user, **I want** to be able to download the data from a published data source as a .csv file using the Tableau Server Client **so that** I can write machine learning algorithms that use my published data sources.

**Comment by t8y8** [comment]
Thanks for the request, and in a story format to boot. I think this is clear and we will take it back to the team.

/cc @benlower @irwando

**Comment by davidgibsonp** [comment]
Any updated on this?

**Comment by Maker2018** [comment]
Any updates on this?

**Comment by alinacornea** [comment]
Any updates? 
We ending up creating views just so the users are able to extract the data for their purposes

**Comment by jacalata** [comment]
This didn't get traction, so the workaround of creating a view to download will have to do.
