### ISSUE TITLE
Download as .tds

### ISSUE THREAD

**Issue by once-returner** [tableau/server-client-python#323]
In the [Datasource Download](https://tableau.github.io/server-client-python/docs/api-ref#datasourcesdownload) section of the documentation, it shows that you can choose not to include the extract when downloading. However, there is no way to download the file as a .tds instead of a .tdsx. To work around this is a massive pain, there are no converters available that I've found, and without the ability to do this I am unable to automate documentation (I'm intending to parse through the XML to pull out data points for documentation... I have to download .tdsx's and manually convert each one to .tds in order to do this).

**Comment by t8y8** [comment]
Unfortunately the Server determines the download format (and TDSX is the only true portable format it can produce, when you have caches, shape files, TDCs, etc.)

A tdsx is just a zipfile, so you should be able to automate it by using code something like this:
```py
from zipfile import ZipFile

with open(tdsx_filename, 'r') as zip:
    files = zip.namelist()
    tds_file = [f for f in files if f.endswith('tds')].pop()
    output = zip.extract(tds_file)

process_tds(output)
```

Another library that automates some of this is located at https://github.com/tableau/document-api-python and the file of interest that does some of this zipfile manipulation can be seen in: https://github.com/tableau/document-api-python/blob/master/tableaudocumentapi/xfile.py

**Comment by irwando** [comment]
Closing old issue.

The REST API and TSC both now have an option to specify if the extract should be downloaded or not.
