### ISSUE TITLE
Unable to upload files >64 MB.

### ISSUE THREAD

**Issue by whatthestack** [tableau/server-client-python#326]
It would say the following error:
`TypeError: publish_req_chunked() takes at most 3 arguments (4 given)
`
After jumping into the package, I found editing these lines resolved the issue:

server-client-python/tableauserverclient/server/request_factory.py - line 105 and 394, i added either connection_credentials or connections - depending on what was missing:

105 - Previous:     def publish_req_chunked(self, datasource_item, connection_credentials=None):
105 - Fixed:     def publish_req_chunked(self, datasource_item, connection_credentials=None, connections=None):

394 - Previous:    def publish_req_chunked(self, workbook_item, connections=None):
394 - Fixed:    def publish_req_chunked(self, workbook_item, connection_credentials=None, connections=None):

Is there a reason why it was left off?  Looking at the following lines, it makes more sense to have them there.

After I made these changes, I was able to upload a 700+ MB file.

**Comment by t8y8** [comment]
This is fixed in the development branch; can you pull from there and verify your issue is resolved?

**Comment by bskim45** [comment]
I just made another PR to cover latter case.
btw, is there any ETA for next release? @t8y8

**Comment by pmehai** [comment]
Are there any updates on this issue? I'm running into this error when trying to upload an 84MB extract.

**Comment by bskim45** [comment]
The fix is merged but not released yet. You should install the package directly from development branch.

**Comment by t8y8** [comment]
@RussTheAerialist I know an internal team has a PR out that they’d like released shortly, maybe we can try and get those merged and released next week. I’m on vacation but I’ll support code reviews that I’m tagged in!

**Comment by sharono011** [comment]
This is still broken.  When will the fix be released?

**Comment by irwando** [comment]
Released.  Please re-open if you still have issues.

**Comment by samyak53** [comment]
I am getting this error `TypeError: publish_req_chunked() takes from 2 to 3 positional arguments but 4 were given` when I try to publish datasource having size 300MB using this function server.datasources.publish()

**Comment by DuncanTormey** [comment]
> I am getting this error TypeError: publish_req_chunked() takes from 2 to 3 positional arguments but 4 were given when I try to publish datasource having size 300MB using this function server.datasources.publish(). @RussTheAerialist

@samyak53 I am getting this error too. Were you able to resolve?
