### ISSUE TITLE
Unable to fetch interval_item from schedules

### ISSUE THREAD

**Issue by aython** [tableau/server-client-python#327]
Hi Team,

I am trying to query all the schedules available and able to fetch id,name,execution_order, priority etc but interval_item is returning as None.Or is there any other method to get the frequency of schedules.

Please help.

**Comment by irwando** [comment]
This is confusing as Server has frequency but not interval.  Not sure what this is supposed to be.

**Comment by dvvolodin** [comment]
Attribute **interval_item** in **ScheduleItem** is populated based on the presence of **frequencyDetails** in the API XML response, but responses to **GET /api/api-version/schedules** don't seem to provide this field, so any frequency information is lost completely. **GET /api/api-version/schedules/schedule-id**, on the other hand, is documented to provide **frequencyDetails**, but there is no get_by_id() in class **Server**. Please please please fix it.

**Comment by jacalata** [comment]
released in 0.18
