### ISSUE TITLE
Cannot get the list of Tasks to refresh

### ISSUE THREAD

**Issue by pkchuyen** [tableau/server-client-python#328]
Hello,

I would like to get the list of Tasks and refresh it from jenkins instead of timing (Tableau Scheduler)
I am using this TSC sample code  https://github.com/tableau/server-client-python/blob/master/samples/refresh_tasks.py#L70

But I ran into the error 

```
python3 extracts.py --server https://tableau.domain.com -u pkc -p  -l info 
INFO:tableau.endpoint.auth:Signed into https://tableau.domain.com as pkc
INFO:tableau.endpoint.auth:Signed out
Traceback (most recent call last):
  File "extracts.py", line 68, in <module>
    main()
  File "extratcs.py", line 64, in main
    args.func(server, args)
AttributeError: 'Namespace' object has no attribute 'func' 
```

from what i understand the Namespace does not have attribute `func` 

Can you help to check what is wrong and how can i fix it?

Beside, I have 25 Tasks including daily extract and Weekly extract. What is the best way to filter them out to  run extract on only daily extract task?

My Tableau server is 2018.1

Thank you,

**Comment by gaoqiang-zhuo** [comment]
Hi Chuyen,

For you first question, you can try adding which function (list, run, info) you want to run at the end of the command, like `python3 extracts.py --server https://tableau.domain.com -u pkc -l info list`.

For your second question, have you figured out how to filter daily extract refresh task? I also want to know how to filter the extract refresh task for a specific workbook. Could you share if you know the answer?

Thanks,
Gao

**Comment by bcantoni** [comment]
I'll go ahead and close this one due to age, but please reopen (or create a new issue) if needed.
