### ISSUE TITLE
Getting images no longer works

### ISSUE THREAD

**Issue by congcharlieqin** [tableau/server-client-python#330]
https://github.com/tableau/server-client-python/blob/master/samples/download_view_image.py

This example seems to no longer work with the latest version of Tableau online. Generating preview images still works but getting the actual image no longer works. Bug or has this feature been deprecated?

**Comment by t8y8** [comment]
What is inside the file that get's written by the sample?

Does the client/script throw an error?

**Comment by congcharlieqin** [comment]
The code above used to write out a PNG file.

I get an error from the server,

tableauserverclient.server.endpoint.exceptions.ServerResponseError: 

	400074: Bad Request
		There was a problem querying the image for view 'my_view_id_here'.

When testing the REST API itself I get the same error so this may be a server problem. However when contacting support they were not quite as helpful and insisted I open an issue here.

**Comment by cjculver** [comment]
I used the sample and it executed fine both on Tableau Server and Tableau Online as-is. Are you passing all of the correct arguments?

This question may be better suited to the [Developer portal](https://community.tableau.com/community/developers/rest-api) of the Tableau Community if you're writing your own code based off of the sample.

**Comment by congcharlieqin** [comment]
Hi @cjculver 

Yes it looks like everything is being passed in properly. When I turn on debug everything looks correct up until the actual image retrieval. 

Here is the output directly from the script in the repo without any modification. I also verified that the user account I'm using can log in and also has permissions (is owner).

```

INFO:tableau.endpoint.views:Populated image for view (ID: VIEW_ID)

DEBUG:urllib3.connectionpool:https://10ay.online.tableau.com:443 "GET /api/2.5/sites/SITE_ID/views/VIEW_ID/image?resolution=high HTTP/1.1" 400 393

DEBUG:tableau.endpoint:<?xml version='1.0' encoding='UTF-8'?><tsResponse xmlns="http://tableau.com/api" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tableau.com/api http://tableau.com/api/ts-api-2.5.xsd"><error code="400074"><summary>Bad Request</summary><detail>There was a problem querying the image for view 'VIEW_ID'.</detail></error></tsResponse>
```

**Comment by shanky1** [comment]
Did you get this to work? How did you resolve this?
I get the same error.

**Comment by congcharlieqin** [comment]
I basically had my data analyst just refresh the notebook in Tableau and then it just started working.
