### ISSUE TITLE
'module' object has no attribute 'ImageRequestOptions'

### ISSUE THREAD

**Issue by patribo** [tableau/server-client-python#333]
Hi all

I tried the '   download_view_image.py ' sample but I get an error called : 

image_req_option = TSC.ImageRequestOption(imageresolution=TSC.ImageRequestOptions.Resolution.High)

**AttributeError: 'module' object has no attribute 'ImageRequestOptions'**

I already got tagged workbooks downloaded and everything works well. What did I do wrong? Is there anything I have to import or specify?

Thank you! 
Patricia

**Comment by cjculver** [comment]
Do you have the latest version? Did you modify the sample at all? I tested the sample from a new virtual environment after running 'pip install tableauserverclient' and I am able to run the sample from the command-line as-is when passing the arguments.

**Comment by irwando** [comment]
No response in a year.  Please open a new issue if you are still having issues.
