### ISSUE TITLE
Is there any way to download a workbook CSV using Tableau Server Client ?

### ISSUE THREAD

**Issue by MArieAntoinette** [tableau/server-client-python#336]
Hello,
I saw on the samples code that it was pretty easy to download an image of the workbook using TSC. Is there a similar way to download the CSV and if it exists, what should I use instead of TSC.ImageRequestOptions ?

Thanks

**Comment by RussTheAerialist** [comment]
We have a sample that shows you how to do it: https://github.com/tableau/server-client-python/blob/master/samples/export.py

The key method is on the views endpoint, and it's called populate_csv: https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/endpoint/views_endpoint.py#L94,L103

This will allow you to then get the csv property on the view: https://github.com/tableau/server-client-python/blob/master/tableauserverclient/models/view_item.py#L74,L79

**Comment by MArieAntoinette** [comment]
Thanks a lot for your answer.

**Comment by skydascanioa** [comment]
is there any way to download the csv of a specific sheet of a dashboard?

**Comment by mhadi813** [comment]
Yes, it involves Tableau Server API to download datasource, Hyper API and pantab to convert datasource to pandas dataframe. I add my own package [``pyplatform``](https://pypi.org/project/pyplatform-reporting/) to simplify the process

```
#TODO: install package
# pip install pyplatform-reporting

# TODO: set credentials as environment variable or provide login keyword argument to   ``download_hyper_tableau_server`` function
# os.environ['TABLEAU_SERVER_CREDENTIALS'] = 'path_to_json file containing key values for Tableau server login'

from pyplatform.reporting import *
import pandas as pd

datasource_name = 'Sample - Superstore'
hyper_filepath = download_hyper_tableau_server(datasource_name, serverUrl='https://my-tableau-server.domain.com',username='it_s_me',password='password') # see function docstring for credential keyword args:
df = hyper_to_df(hyper_filepath)
df.head()
df.to_csv(f"{datasource_name}.csv")
```
> is there any way to download the csv of a specific sheet of a dashboard? (using python and Tableau API)

**Comment by knguyen1794** [comment]
@mhadi813 this is more like exporting the raw data from the data source (hyper extract).

Typically a dashboard can contain more than 1 sheet, do you know of a way with TSC to download data of a specific sheet on the dashboard (view) ?

**Comment by daniiarabdiev** [comment]
@knguyen1794 Were you able to find solution for your problem? I have similar issue and can not find anything. I can download CSV data of the view, but it downloads only first sheet, out of two.

**Comment by luminous0989** [comment]
> @knguyen1794 Were you able to find solution for your problem? I have similar issue and can not find anything. I can download CSV data of the view, but it downloads only first sheet, out of two.

Have you found a solution to this problem also? Im faced with the same problem, only getting to download the first sheet out of the two.
