### ISSUE TITLE
filter views by field name doesn't work

### ISSUE THREAD

**Issue by maryam-hesham96** [tableau/server-client-python#338]
i'm trying to get a specific view 
this is my code
     req_option.filter.add(TSC.Filter(TSC.RequestOptions.Field.Name,
                                 TSC.RequestOptions.Operator.Equals,
                                 view_name))
        view = server.views.get(req_option)
  
but it returns this error
        400065: Bad Request
                The filter query contains a key which is not recognized for this api version.

**Comment by SurinSpace** [comment]
I get the same error... :(

**Comment by irwando** [comment]
As noted you may need to use a newer version of the API. Please let us know if that doesn't work.
