### ISSUE TITLE
Enable setting tags on publish

### ISSUE THREAD

**Issue by benlower** [tableau/server-client-python#34]
Right now we only support adding tags on update. Would be nice to be able to tag things on upload/publish.

**Comment by Talvalin** [comment]
From reading the REST API reference, there appears to be no way to add tags to a workbook on publish, so a REST API enhancement is required. I mean, technically, we could do it in TSC but we'd have to publish, grab the workbook id and then update the tags under the covers or something like that.

**Comment by v6shah** [comment]
Any update on this? Will this be implemented?

**Comment by jacalata** [comment]
Closing this for age and lack of priority.
