### ISSUE TITLE
publishing mixture of live and extract connections

### ISSUE THREAD

**Issue by ausiddiqui** [tableau/server-client-python#340]
https://github.com/tableau/server-client-python/blob/b7b544e5ef405ca76f9e0c5681b001373811c6b2/samples/publish_workbook.py#L73

I have a workbook with a live connection to an Excel file in the Box cloud, and I have attached it to the workbook via the Box connector. There are 3 other datasources in Teradata embedded as extracts and all of them are on the same database with the same credentials. The Box API makes me click on a "grant permission to application" in my browser when I open the workbook on Tableau Desktop. This setup works seamlessly through the desktop, I can refresh the db extracts and saved changes to the Excel file in Box populate onto the server version of the dashboard as long as I refresh the browser.

I am using the server-client-python package to trigger an extract refresh, and having to make a few other changes and publish the downloaded .twbx file using the following variants with no luck:

**version 1**
```python3
def publishWorkbook(twbWorkbook, tAuth, tServer, filePath):
    with tServer.auth.sign_in(tAuth):
        req_option = TSC.RequestOptions()
        req_option.filter.add(TSC.Filter(TSC.RequestOptions.Field.Name,
                                         TSC.RequestOptions.Operator.Equals,
                                         twbWorkbook))
        matching_workbooks, pagination_item = tServer.workbooks.get(req_option)
        cc = TSC.ConnectionCredentials(td_user, td_pass, embed=True)
        uploadWB = matching_workbooks[0]
        wbItem = TSC.WorkbookItem(project_id=uploadWB.project_id,name=twbWorkbook, show_tabs=True)
        wbItem = tServer.workbooks.publish(wbItem,
                                               file_path=filePath +
                                               twbWorkbook.replace(":", '') +
                                               '.twbx',
                                               mode='Overwrite',
                                               connection_credentials=cc)
```
Result: 400011: Bad Request
There was a problem publishing the file

**version 2**
```python3
        uploadWB = matching_workbooks[0]
        wbItem = TSC.WorkbookItem(project_id=uploadWB.project_id,name=twbWorkbook, show_tabs=True)
        wbItem = tServer.workbooks.publish(wbItem,
                                               file_path=filePath +
                                               twbWorkbook.replace(":", '') +
                                               '.twbx',
                                               mode='Overwrite')
```
Result: 400011: Bad Request
There was a problem publishing the file

**version 3**
```python3
        uploadWB = matching_workbooks[0]
            
        tServer.workbooks.populate_connections(uploadWB)
        conns = uploadWB.connections
            
        wbItem = TSC.WorkbookItem(project_id=uploadWB.project_id,name=twbWorkbook, show_tabs=True)
        wbItem = tServer.workbooks.publish(wbItem,
                                               file_path=filePath +
                                               twbWorkbook.replace(":", '') +
                                               '.twbx',
                                               mode='Overwrite',connections=conns)
```
Result: 400000: Bad Request
Payload is either malformed XML/JSON or incomplete

How can I handle this mixture of live / extract datasources that have different types of credentials using the REST API? 

Tableau Server 10.5
server-client-python 0.7
python 3.5 on Ubuntu and macOS

**Comment by sathiyasarathi-oa** [comment]
Is there a solution for this yet? Can't we publish the reports with live connections yet?
