### ISSUE TITLE
Remove the old docs from the master branch

### ISSUE THREAD

**Issue by mbren** [tableau/server-client-python#346]
The docs have moved to the gh-pages branch. To reduce confusion, consider removing the old docs from the master branch.

**Comment by Talvalin** [comment]
Is the gh-pages branch publicly accessible? If so, could someone provide a link please? I'd like to update the current docs with the changes that I originally made to [sign-in-out.md](https://github.com/tableau/server-client-python/blob/master/docs/docs/sign-in-out.md), as well as adding more information about logging on to a site as per #355

**Comment by irwando** [comment]
@t8y8 Yes.  Just go to the page you want to edit and click edit on the top.
