### ISSUE TITLE
basestring is no longer supported in Python 3

### ISSUE THREAD

**Issue by julien10** [tableau/server-client-python#351]
Hi guys,

Here is an extract of Python 3.0's changelog:
> The builtin basestring abstract type was removed. Use str instead. The str and bytes types don’t have functionality enough in common to warrant a shared base class. The 2to3 tool (see below) replaces every occurrence of basestring with str.

Could you please take care of this issue ?

https://github.com/tableau/server-client-python/blob/b7b544e5ef405ca76f9e0c5681b001373811c6b2/tableauserverclient/server/endpoint/jobs_endpoint.py#L17

**Comment by shinchris** [comment]
Thanks for pointing this out.

Merged into development branch: #362
