### ISSUE TITLE
Getting Deatils about SQL-Server Connections

### ISSUE THREAD

**Issue by Lazloo** [tableau/server-client-python#353]
I would like to identify the the database, schema and table/view/stored procedure that is used for a live connection regarding a workbook. Unfortunately, there is no attribute in the class "connections" that contains these information. I currently get my connection via the following code:

```
with server.auth.sign_in(obj.tableau_auth):
    workbook_example = server.workbooks.get_by_id(all_workbooks[123].id)
    server.workbooks.populate_connections(workbook_example)
    connection_example_list = workbook_example.connections
```

Is there another option or will it be implemented in near future?

**Comment by irwando** [comment]
Check out the Data Catalog and specifically the Metadata API which is part of the 2019.3 beta.  It should provide some of this.  Open question on how we add this to TSC>
