### ISSUE TITLE
Hide Views when Publishing a Workbook

### ISSUE THREAD

**Issue by twozeroseven** [tableau/server-client-python#354]
A workbook with worksheets set to hidden - which is not uncommon for Workbooks with 1 dashboard view and many hidden worksheets.   Upon publishing via workbook.publish() method the sheets show up on Tableau server as visible.

**Comment by sks786** [comment]
Hi Team, 

I also have same concern.
When publishing workbook to the server, hidden sheets are being visible, which we don't want?

Any help on this concern.

Regards,
Subodh kumar

**Comment by sks786** [comment]
Hi twozeroseven,

Did you get any solution?
If yes, please help me out.

Regards,
Subodh Kumar

**Comment by twozeroseven** [comment]
Is there a better way to setup a workbook to not have hidden sheets?

**Comment by irwando** [comment]
This was added to REST API, need to plumb it through:

https://onlinehelp.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooksviews.htm#publish_workbook

**Comment by irwando** [comment]
Duplicate of #315

**Comment by julien10** [comment]
Any update on that matter ?

**Comment by shinchris** [comment]
This has been added by @scuml in #614.
