### ISSUE TITLE
TSC Python Script- List of Publisher users on server- Help please

### ISSUE THREAD

**Issue by mehuldan** [tableau/server-client-python#363]
#To get list of Publishers 2018.1 Tableau server
u = server.users.get()
for usr in u[0]:
    if usr.site_role=='Creator':
           username = (usr.name)
           userrole=usr.site_role
           print(username,userrole) 
            #print(usr.name,usr.site_role)

I can able to establish successful connection to Tableau development server.
I want to get list of Users by Site Role= Creator/Publisher 
In my Code, I am filtering by Creator' and get no output. Expect 34 publisher users in output.
When I filter by SiteAdministratorCreator, I get results. 

If anybody can help testing my script or posting their test script I appreciate.

**Comment by shinchris** [comment]
Do you have more than 100 users on your site?
By default, `u = server.users.get()` will only give you 100 users, so it's likely that the expected users are not part of the returned 100 users.

You can either change the pagination options or use the Pager generator to get all users on site. Docs can be found here: https://tableau.github.io/server-client-python/docs/page-through-results
