### ISSUE TITLE
Not able to Pip install tableau server client 

### ISSUE THREAD

**Issue by mappikonda13** [tableau/server-client-python#365]
When trying to install Tableauserverclient module into my local tableau server cannot able to import 

Tableau Versions : 2018.2
SSL Enabled

 below is the error i'm getting 

C:\Users\Tableau_Admin>pip install ./downloads/tableauserverclient-0.7.tar.gz
Processing c:\users\svc_tableau_admin\downloads\tableauserverclient-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/pytest-runner/: timed out -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: timed out -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SVC_TA~1\AppData\Local\Temp\2\pip-req-build-1cotlzk1\setup.py", line 27, in <module>
        'pytest'
      File "d:\program files (x86)\python\python371\lib\site-packages\setuptools\__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "d:\program files (x86)\python\python371\lib\site-packages\setuptools\__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "d:\program files (x86)\python\python371\lib\site-packages\setuptools\dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "d:\program files (x86)\python\python371\lib\site-packages\pkg_resources\__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "d:\program files (x86)\python\python371\lib\site-packages\pkg_resources\__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "d:\program files (x86)\python\python371\lib\site-packages\pkg_resources\__init__.py", line 1069, in obtain
        return installer(requirement)
      File "d:\program files (x86)\python\python371\lib\site-packages\setuptools\dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "d:\program files (x86)\python\python371\lib\site-packages\setuptools\command\easy_install.py", line 667, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

C:\Users\SVC_Tableau_Admin>pip install ./downloads/tableauserverclient-0.7-py2.py3-none-any.whl
Processing c:\users\svc_tableau_admin\downloads\tableauserverclient-0.7-py2.py3-none-any.whl
Collecting requests<3.0,>=2.11 (from tableauserverclient==0.7)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip
._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000000C6ACE50F60>, 'Connection to pypi.org timed out. (connect timeou
t=15)')': /simple/requests/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip
._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000000C6ACE50B70>, 'Connection to pypi.org timed out. (connect timeou
t=15)')': /simple/requests/

**Comment by reevery** [comment]
I'm wondering as you're not just doing pip install tableauserverclient that you have no internet access? The tableau package doesn't include the dependencies, and it looks like the connection to pypi.python.org is failing. If you can't connect to the repos from that box, you'll need to download all of the packages in requirements.txt

**Comment by mappikonda13** [comment]
Thanks reevery .. Still no luck i couldn't download all the packages that are been referred in the requirements.txt .. not sure whether I'm referring to the correct requirements.txt ..Please help me to get all the packages in a zip file ..

**Comment by reevery** [comment]
Do you have access to another environment where you can run the script? For instance, can you run it on a virtual machine or a docker container? It doesn't have to be installed on the Tableau Server itself, and it might be better to keep it separate.

Alternatively do you have IT guys you can speak to, as they can help you configure the server to the network settings where your server is running. If it's on AWS, it will just be missing an outbound policy in a security group, but this may be by design.

**Comment by anshumanmisri** [comment]
I am also getting the same issue can some one tell me how to install without internet ..

**Comment by paramasivan1** [comment]
I am just starting with TSC. I want to install it on my server machine which doesn't have internet connectivity. Does the PIP install work? Where do I find the documentation for install ?

**Comment by irwando** [comment]
We should document an offline install process.

**Comment by dzucker-tab** [comment]
@paramasivan1 and @reevery 

Thanks for bringing this issue up. So we can understand the scenario more fully, could you both say a little more why you are installing TSC on machines that are not internet connected?

The way python dependencies are configured in the TSC set up package requires either for them to be preinstalled when installing TSC, or for network to be available to retrieve them. We'll work on improving the TSC install package, but offline installation currently requires manual installation of the following python libraries before running `pip install ./downloads/tableauserverclient-0.7.tar.gz`:

- pytest-runner
- pytest
- requests

There is a lot of content on the web about various approaches to installing python libraries and their dependencies manually.

**Comment by dzucker-tab** [comment]
Updated https://tableau.github.io/server-client-python/docs/#install-on-an-offline-machine
