### ISSUE TITLE
move_workbook_sites.py does not respond

### ISSUE THREAD

**Issue by itsAftab** [tableau/server-client-python#367]
Trying to move a workbook from one of the projects in the default site to a secondary site but the script is not responding:

`$py move_workbook_sites.py --server http://my-server.com --username abd123 --workbook-name myFirstWorkbook --destination-site secondary-site` 

I have also tried with site's URL
`$py move_workbook_sites.py --server http://my-server.com --username abd123 --workbook-name myFirstWorkbook --destination-site http://my-server-com/#/site/secondary-site`

I am the Server Administrator

**Comment by reevery** [comment]
What error do you get?

The second definitely won't work, the script is checking for the site content_url. Does that definitely have a dash in it?

**Comment by irwando** [comment]
Closing old issues with no responses.
