### ISSUE TITLE
Expose tags from ViewItem class

### ISSUE THREAD

**Issue by mcoles** [tableau/server-client-python#369]
Currently I can pull a list of tags from the WorkbookItem class, but I cannot do so for the [ViewItem](https://tableau.github.io/server-client-python/docs/api-ref#viewitem-class) class. But both Server and Online support tagging of views, and for my project, I require that functionality. Please consider exposing that property for the ViewItem class as well, as I'd have preferred to use this client rather than making my own REST calls.

thanks!

**Comment by mcoles** [comment]
Actually, it looks like the Server API itself doesn't support pulling tags for views...

**Comment by mcoles** [comment]
Ah, I didn't realize that the docs for the [example responses](https://onlinehelp.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#query_views_for_site) for that call weren't comprehensively listing the return values. Thanks! But yes, it would be great not to have to interact directly with the REST API. :)

**Comment by irwando** [comment]
Doesn't seem we pipe these through.

**Comment by toomyem** [comment]
I have submitted PR #470 for this.

**Comment by mcoles** [comment]
Thanks @toomyem !

**Comment by irwando** [comment]
Merged #470 into development branch
