### ISSUE TITLE
Unable to create a project in a site

### ISSUE THREAD

**Issue by itsAftab** [tableau/server-client-python#370]
The script create_project.py does not create a project in sites other than DEFAULT. Like, if I write the follwing: 
`$ py create_project.py --server http://myTableau/ --username aftab --site http://myTableau/#/site/SANDBOX/projects -p my_password123`
A project is created in DEFAULT site, and when I run the script again I get the following message:

> We have already created this project: Top Level Project

I am trying to create a project in SANDBOX. The URL for SANDBOX is: 

> URL:  http://myTableau/#/site/SANDBOX

**Comment by RussTheAerialist** [comment]
The argument to site needs to just be the site name as present in the URL.  So in your case, you'll want to use `--site SANDBOX` rather than `--site http://mytableau/#site/SANDBOX/projects`

**Comment by itsAftab** [comment]
@RussTheAerialist that still doesn't work. It creates a Top Level Project in DEFAULT

 ```
myMachine+username@a12bcde0123 MINGW64 /c/Tableau/server-client-python/samples (master)
$ py create_project.py --server http://myTableau.domain.com --username aftab --site SANDBOX -p my_password123
```

> Created a new project called: Top Level Project
> Created a new project called: Child Project
> Created a new project called: Grand Child Project
>
