### ISSUE TITLE
Pattern for checking if value is member of enum should be abstracted in a decorator

### ISSUE THREAD

**Issue by LGraber** [tableau/server-client-python#38]
We have the same ~4ish lines of code in a number of places which attempt to make sure that some value being assigning to a class property is a member of some enum. And if not, we construct an error message and throw. This should be hidden in a decorator to make the code a bit more readable and also gaurantee some consistency in our error handling.

**Comment by t8y8** [comment]
@LGraber can you add an example or link to one of them?

**Comment by LGraber** [comment]
@site_role.setter
    @property_not_nullable
    @property_type(UserItem.Roles)
    def site_role(self, value):
        self._site_role = value

would replace:

    @site_role.setter
    def site_role(self, value):
        if not value:
            error = 'Site role must be defined.'
            raise ValueError(error)
        elif not hasattr(UserItem.Roles, value):
            error = 'Invalid site role defined.'
            raise ValueError(error)
        else:
            self._site_role = value

I actually have this coded and the decorators defined if you want to see. I am having one little "python" problem. :)
