### ISSUE TITLE
Cannot update revision history setting for site

### ISSUE THREAD

**Issue by baixin137** [tableau/server-client-python#381]
https://github.com/tableau/server-client-python/blob/b7b544e5ef405ca76f9e0c5681b001373811c6b2/tableauserverclient/server/request_factory.py#L291
I'm pretty sure it should be **if site_item.revision_history_enabled is not None** here, this block tries to change revision history setting but it's checking **site_item.subscribe_others_enabled**
Also i think we don't want to use **if site_item.revision_history_enabled**, because it ignores the case when the value is False, and doesn't write False into the request.

**Comment by shinchris** [comment]
Thanks for pointing this out, as well as the other 2 issues.

**Comment by irwando** [comment]
@shinchris to close when the merge is done.
