### ISSUE TITLE
Cannot rename a datasource

### ISSUE THREAD

**Issue by bfsaid85** [tableau/server-client-python#382]
It is not possible to rename a datasource and the example in API reference didn't work :

-- do some updating 
  datasource.name = 'New Name'

-- call the update method with the data source item
  updated_datasource = server.datasources.update(datasource)

I would like rename a datasource and keep the relation with linked workbooks, how is it possible?

**Comment by shinchris** [comment]
Datasources cannot be renamed. There seems to be a mistake in the API reference. We will fix the example in the API reference.

**Comment by dzucker-tab** [comment]
@bfsaid85 Fix for this is merged, thanks for the find! and thanks to @irwando and @shinchris
