### ISSUE TITLE
Tableau 2018 credentials not updated on published datasource

### ISSUE THREAD

**Issue by bfsaid85** [tableau/server-client-python#387]
Using Tableau 2018, when i publish a datasource with credentials, the values of username and password are taken from the tds file and not from the past parameter.
For example in tds file i have username='user_123'
in my source code i use :
credentials = TSC.ConnectionCredentials(name = 'Test', password = 'Test')
datasource = server.datasources.publish(datasource, file_path, TSC.Server.PublishMode.Overwrite, credentials)
I still have username = 'user_123
![image](https://user-images.githubusercontent.com/8581409/51744216-ff2f8b80-2096-11e9-809e-89a00bb4ed96.png)
'

**Comment by kmamykin** [comment]
I an confirm I am seeing exactly the same problem.
+1

**Comment by sujeeth62** [comment]
I an confirm I am seeing exactly the same problem while publishing workbook.
+1

**Comment by bfsaid85** [comment]
The temporary solution that I adopted after publication :

server.datasources.populate_connections(my_datasource)
connection = my_datasource.connections[0]
connection.username = connection_name
connection.password = connection_password
connection.embed_password = True
server.datasources.update_connection(my_datasource, connection)

**Comment by sujeeth62** [comment]
I have done that using workbooks.update_connection.

Issue is unable to update schema and service for my oracle connection.

**Comment by jacalata** [comment]
I believe this is expected behavior. You could also update the saved credentials in the datasource with the document api before publishing.
