### ISSUE TITLE
Embedded dashboard images not loaded with workbook

### ISSUE THREAD

**Issue by vizyourdata** [tableau/server-client-python#400]
While using server.workbooks.publish(), the images that I have embedded in a dashboard do not load into server. These load fine when I manually load from desktop. I've attempted using images saved from the Tableau default images location and from dropbox and from OneDrive with no success. Its obviously not a critical element of the dashboard but something that the client wants to see. 

Desktop:
![image](https://user-images.githubusercontent.com/18519187/52798136-8e93e300-3034-11e9-8a1c-9b76ac7f08e4.png)

Server:
![image](https://user-images.githubusercontent.com/18519187/52797942-2f35d300-3034-11e9-8880-38627b4c8019.png)

**Comment by shinchris** [comment]
Did you publish a .twb or a .twbx (packaged workbook) file of the workbook?

**Comment by vizyourdata** [comment]
I am publishing with a .twb

**Comment by shinchris** [comment]
In order to get those images loaded into server, you will need to publish a .twbx file of the workbook. Otherwise, a .twb file will not be able to publish those images to server.

**Comment by vizyourdata** [comment]
thanks for the info @shinchris!
