### ISSUE TITLE
Support for 2019.1

### ISSUE THREAD

**Issue by nishantnath** [tableau/server-client-python#402]
As per https://tableau.github.io/server-client-python/docs/versions
Highest Supported Version is 2018.3 while 2019.1 was released Feb 15, 2019

Using a server with 2019.1 and existing TSC python-client, TSC.Pager(server.schedules) throws an error:  `ValueError: Invalid value: Flow. schedule_type must be of type Type`

TSC.Pager(server.workbooks) & TSC.Pager(server.datasources) seems to be working fine.

**Comment by shinchris** [comment]
Thanks for opening an issue for this. This has been fixed in the 'development' branch with #403.

Info on how to use the 'development' branch: https://tableau.github.io/server-client-python/docs/#install-from-the-development-branch

**Comment by mwilton** [comment]
Using that dev branch to solve this problem.  It works, but then the following no longer works:
workbook.show_tabs = True
self.server.workbooks.update(workbook)

error: 
400000: Bad Request     Payload is either malformed or incomplete

**Comment by nachtgold** [comment]
> 
> 
> Using that dev branch to solve this problem. It works, but then the following no longer works:
> workbook.show_tabs = True
> self.server.workbooks.update(workbook)
> 
> error:
> 400000: Bad Request Payload is either malformed or incomplete

I have the same problem with Tableauserverclient 0.8 and Tableau 20183.19.0123.2221

**Comment by AlexandreRodrigues1** [comment]
Also having the same problem with tableau version 2018.3.2
and TSC version 0.8
