### ISSUE TITLE
PIP install tableauserveclient error

### ISSUE THREAD

**Issue by anshumanmisri** [tableau/server-client-python#405]
Hi Team,

Getting  an error while install PIP install tableauserveclient 

D:\TSC\Python\Python37-32>pip install tableauserverclient
Collecting tableauserverclient
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x03189C10>: Failed to establish a new connec
tion: [Errno 11001] getaddrinfo failed')': /simple/tableauserverclient/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x03189AB0>: Failed to establish a new connec
tion: [Errno 11001] getaddrinfo failed')': /simple/tableauserverclient/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x031891B0>: Failed to establish a new connec
tion: [Errno 11001] getaddrinfo failed')': /simple/tableauserverclient/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x031898D0>: Failed to establish a new connec
tion: [Errno 11001] getaddrinfo failed')': /simple/tableauserverclient/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x031A8430>: Failed to establish a new connec
tion: [Errno 11001] getaddrinfo failed')': /simple/tableauserverclient/
  Could not find a version that satisfies the requirement tableauserverclient (f
rom versions: )
No matching distribution found for tableauserverclient

**Comment by shinchris** [comment]
This looks to be an issue connecting to Pypi, possibly because of your firewall. Are you able to `pip install` any other packages?

**Comment by paramasivan1** [comment]
I am getting the same problem as my server machine is air-gapped. No internet connection

**Comment by irwando** [comment]
Hi there,

As per Chris's comments this seems to be a network access issue.  As there has been no further conversation here I'm closing the issue for now.  If you can `pip install` other items but not this then let us know.  Otherwise we believe it is a larger issue outside of our control.

Thanks!

**Comment by vinothdakshin** [comment]
Hi There,

when am trying to install tableau server client am getting the below error: Unable to install any other packages as well, please note  my server is Air-gapped no Internet connection, i have to follow offline installation steps, can someone help here.

C:\Users\tableauuk>pip install C:\Users\tableauuk\AppData\Local\Programs\Python\
TabPy\tableauserverclient-0.9.tar.gz
Processing c:\users\tableauuk\appdata\local\programs\python\tabpy\tableauserverc
lient-0.9.tar.gz
Collecting requests<3.0,>=2.11 (from tableauserverclient==0.9)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, stat
us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
onnection.VerifiedHTTPSConnection object at 0x03E99EE0>: Failed to establish a n
ew connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, stat
us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
onnection.VerifiedHTTPSConnection object at 0x03E99E50>: Failed to establish a n
ew connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, stat
us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
onnection.VerifiedHTTPSConnection object at 0x03E99BF8>: Failed to establish a n
ew connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, stat
us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
onnection.VerifiedHTTPSConnection object at 0x03E997D8>: Failed to establish a n
ew connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, stat
us=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.c
onnection.VerifiedHTTPSConnection object at 0x03E99850>: Failed to establish a n
ew connection: [Errno 11001] getaddrinfo failed')': /simple/requests/
  ERROR: Could not find a version that satisfies the requirement requests<3.0,>=
2.11 (from tableauserverclient==0.9) (from versions: none)
ERROR: No matching distribution found for requests<3.0,>=2.11 (from tableauserve
rclient==0.9)
