### ISSUE TITLE
No error raised from exceptions.py when trying to publish a workbook

### ISSUE THREAD

**Issue by Tiji** [tableau/server-client-python#406]
Hello, 

I'm having trouble figuring out what is my problem on this. 
I used move_workbook_sites.py sample to try to make something different. 
I wanted to take one workbook from a specific site/project and publish a copy of it on a different project. 
So it's different than just changing the project_id like in move_workbook_projects.py sample. 
My source_site is the same as the dest_site but it doesn't matter and I changed the code to add a dest_project. 

The problem I have is a bit weird : when I try to publish the workbook (using **"new_workbook = dest_server.workbooks.publish(new_workbook, workbook_path, mode=TSC.Server.PublishMode.Overwrite)**" ) my code raises an error but the Tableau Server Client library doesn't give me the correct error and just post this final error on exceptions.py : 

 **File "D:\Users\user_1\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tableauserverclient\server\endpoint\exceptions.py", line 18, in from_response
    error_response = cls(parsed_response.find('t:error', namespaces=ns).get('code', ''),
AttributeError: 'NoneType' object has no attribute 'get'**

I've checked on the server, I have the rights to publish using Tableau Desktop with same user and password. 
I've also managed to download the workbook to copy in a temp folder like in move_workbook_sites.py. 

What could be the problem about exceptions.py and also what could cause my code to fail this way on its way to publish the report ? 

Thanks in advance for your help about this issue and have a great day !

Thomas

**Comment by Tiji** [comment]
I have the same problem when I try to use publish_workbook.py with the same workbook and without changing anything about the file. 
Maybe there's something wrong about the way I access my Tableau Server but I could totally do other things : 
- change project_id of a workbook
- download a workbook
- sign in without any issue

Does someone have an idea of what could be wrong ? 
Thanks a lot in advance.

**Comment by irwando** [comment]
May be similar to #358 ?  Can you publish the workbook manually?

Please try the latest version of TSC and let us know how it goes.

**Comment by bcantoni** [comment]
I'll go ahead and close this one due to age, but please reopen (or create a new issue) if needed.
