### ISSUE TITLE
Populate workbooks returns None

### ISSUE THREAD

**Issue by airmonitor** [tableau/server-client-python#409]
Hello.

Public method populate_workbooks is returning none when hidden _get_wbs_for_user is returning correct values.

Tested on Tableau Server Version: 2018.3.2 (20183.18.1214.0808) 64-bit Linux, with latest SDK - tableauserverclient for python 0.7.

To get list of workbooks which users owns or has read permissions and sum of workbooks I've used:

```
all_workbooks, page_n = server.users._get_wbs_for_user(user_item=user)
page_n.total_available
for workbook in all_workbooks:
    print(workbook.name)

```

**Comment by bcantoni** [comment]
Closing due to age.
