### ISSUE TITLE
Doubt - Login with modified tableau server

### ISSUE THREAD

**Issue by rspadim** [tableau/server-client-python#411]
Hi folks, I'm with a modified tableau login server and want to use tableauserverclient api, could be possible modify it? is some work running in this direction?

**Comment by jacalata** [comment]
I'm not sure what you mean by 'modified' - can you add some detail?

**Comment by irwando** [comment]
No response in 3 months.  Please re-open or open a new issues with details of what you are trying to do if this is still a problem.
