### ISSUE TITLE
Remove/hide redundant roles from Roles or correct behavior

### ISSUE THREAD

**Issue by 1oglop1** [tableau/server-client-python#419]
I ran into unexpected behaviour when trying to set role of `ServerAdministrator`.
Server responded with success however it was failure because user role did not change.

Response from customer support
````
The ability to use the REST API to set a user to be a server administrator (ServerAdministrator site role) is not currently built into the product. I will enter an feature request on your behalf for the Product Management team to review for possible inclusion in a future release.
````

@shinchris  (this seems to be similar to #398) 

When I select api version `3.2` library gives me option of all roles.
When I select incorrect role eg.: `ServerAdministrator` - library returns success however the role of the user has not been updated, this behaviour is really confusing.

**Comment by irwando** [comment]
We should return an error in this case since it is not supported, but in the future, may want to allow setting it.

**Comment by jacalata** [comment]
There is no plan for this feature right now.
