### ISSUE TITLE
add_to_schedule issue

### ISSUE THREAD

**Issue by AmeyMankar** [tableau/server-client-python#425]
I am referring to the sample 'set_refresh_schedule.py' to assign a refresh schedule to a published report.  
When the following command runs:  
`server.schedules.add_to_schedule(schedule.id, workbook_or_datasource)`
  
I am getting following error:  

> Traceback (most recent call last):
  File "code.py", line 109, in <module>
    main()
  File "code.py", line 65, in main
    run(args)
  File "code.py", line 102, in run
    if(assign_to_schedule(server, item.id, schedule)):
  File "code.py", line 58, in assign_to_schedule
    server.schedules.add_to_schedule(schedule.id, workbook_or_datasource)
  File "/usr/local/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 115, in wrapper
    self.parent_srv.assert_at_least_version(version)
  File "/usr/local/lib/python3.7/site-packages/tableauserverclient/server/server.py", line 109, in assert_at_least_version
    raise EndpointUnavailableError(error)
tableauserverclient.server.endpoint.exceptions.EndpointUnavailableError: This endpoint is not available in API version 2.6. Requires 2.8

Can someone please help me in overcoming this issue? I am lost here :(   
TIA

**Comment by shinchris** [comment]
The ability to add a datasource or workbook to a schedule was added in version 2.8 of the REST API and version 10.5 of Tableau Server.

If your Tableau Server instance is not at version 10.5 or above, you won't be able to use this sample. If it is 10.5 or above, you can refer to this page (https://tableau.github.io/server-client-python/docs/versions) for information on how to use the latest version of the REST API.
