### ISSUE TITLE
datasources.refresh and workbooks.refresh are undocumented

### ISSUE THREAD

**Issue by dutchgecko** [tableau/server-client-python#436]
Both functions appear in samples/refresh.py but are undocumented (I checked in branches master, development and workbook_doc).

**Comment by user9747** [comment]
I would like to work on it should i just put up a PR.

**Comment by dzucker-tab** [comment]
Sure thing, contributions are always welcome! I've got a bit of a start on this, so I will provide feedback for your request when I see it come through.

**Comment by dzucker-tab** [comment]
Fixed with PR 495
