### ISSUE TITLE
Add support for ServerInfo

### ISSUE THREAD

**Issue by benlower** [tableau/server-client-python#44]

**Comment by t8y8** [comment]
You've got a PR out for this right now, right? :) (Sorry Ben!)

**Comment by RussTheAerialist** [comment]
Yeah I took on getting it done since I wasn't sure Ben would have time

**Comment by LGraber** [comment]
I don't see a PR?

**Comment by RussTheAerialist** [comment]
#84

**Comment by benlower** [comment]
this was closed in the 0.2 release
