### ISSUE TITLE
Google Bigquery authentication

### ISSUE THREAD

**Issue by stocksnut** [tableau/server-client-python#440]
I'm trying to publish a datasource to Tableau Online using the SDK, and the datasource so happens to be Google Bigquery.  One thing that is happening is that when I publish, the datasource publishes fine, but when I view the datasource in the UI, and view the Ask Data, I get "You are not authorized to view.."

But once I go edit the connection and run test connection it authenticates and all is well.  Here's my code:

```
new_datasource = TSC.DatasourceItem(project_id)
new_datasource = server.datasources.publish(datasource_item=new_datasource, file_path=path, mode=mode)
```

So it seems my credentials are not getting passed along in the .tds file.  Any help would be appreciated as to what I should do about authenticating/credentials.

**Comment by marcos-camargo-movile** [comment]
Hello @stocksnut, did you find out how to solve this problem?

**Comment by dbeaudway** [comment]
I'm experiencing this same issue, here is the full error:
```
Forbidden Action
You are not authorized to perform this action. (22)
Could not open the view because access to the data source has been denied or revoked.  To establish your credentials, publish the view's workbook again.
```

**Comment by jacalata** [comment]
Apparently we only partly support the BigQuery connectors through the API. It might be possible to update the document xml manually with the document-api and then publish it through tsc, but I don't know what would be needed.
