### ISSUE TITLE
Is there any plan to implement an api key based method of authentication?

### ISSUE THREAD

**Issue by ryentes** [tableau/server-client-python#441]
I'd like to automate some workflows that interact with the tableau server, but in order to do that using this library I'd have to store my username and password in environment variables. I'm pretty sure that my org authenticates through sso, so that would be my org credentials, which I'm really not happy to write down like that.

I'm no expert on api design, so is there a plan to support a pattern like that? If not, why?

**Comment by nieup** [comment]
Have you seen #437 ? you can create a technical user.

**Comment by razze76** [comment]
Any news on this? The API key is already available in the server

**Comment by illonage** [comment]
Hi everyone - We released a couple of months ago Personal Access Token: https://help.tableau.com/current/server/en-us/security_personal_access_tokens.htm 
Personal access tokens provide Tableau Server users with the ability to create long-lived authentication tokens. The tokens allow users to run automation with Tableau REST APIs without requiring hard-coded credentials or interactive login.

**Comment by kykrueger** [comment]
Is it possible to create one of these keys as a SAML user?
When logged in with my Org, the option to create a token is greyed out.

**Comment by razze76** [comment]
@kykrueger : The UI Is a bit confusing. You need to add the token name before you can create the token
