### ISSUE TITLE
Inactive Users

### ISSUE THREAD

**Issue by timrcase** [tableau/server-client-python#443]
I'm trying to get the list of users that have never logged in to a site and noticed that has proven more difficult than I thought. I've tried the following approach but it returns a `400025: Bad Request` error:

```
request_options = TSC.RequestOptions()
request_options.filter.add(TSC.Filter(TSC.RequestOptions.Field.LastLogin, TSC.RequestOptions.Operator.Equals, None))
```

If I return the complete list of users for the site and check the type for the `lastLogin` field for those users that have never logged in it's of type `None`. I checked one of those users via the REST API and noticed the response does not include a `lastLogin` field.

At this point, I'm wondering if the REST API is even capable of returning a list of users that have never logged in, and if it can't I wouldn't be able to use this library, but wanted to check and make sure I wasn't missing something first.

**Comment by shinchris** [comment]
Filter does not work for `None` values, so you won't be able to query for a filtered list of users that have never logged in. As you've stated, the REST API will not include a `lastLogin` field to the response for users that have never logged in, so you'd just have to check to see if that field is `None` after querying.
