### ISSUE TITLE
Pager does not allow pulling usage information for views.get()

### ISSUE THREAD

**Issue by shinchris** [tableau/server-client-python#444]
The Pager generator takes in RequestOptions, but usage information for views.get() requires another parameter to be passed in. Currently, we cannot use Pager to get all views WITH usage information.

**Comment by t8y8** [comment]
Actually, we do!

Sorta.

Pager accepts any callable, so you can just pass in a partial.

```
from functools import partial
usage_pager = partial(server.views.get, usage=True)
views = TSC.Pager(usage_pager)

for view in views:
    # do something
```

It could probably be a little cleaner but not sure how yet. We could have `Pager` take in *args and just blindly pass them to the callable, which works. Or we can document you should use a partial.

**Comment by t8y8** [comment]
Solved!
