### ISSUE TITLE
Install Documentation

### ISSUE THREAD

**Issue by fpagliar** [tableau/server-client-python#447]
The prerequisites section suggests to install a recent python version to get pip, but then the example uses pip directly:
`$> pip install tableauserverclient`
but if based on python it should be:
`$> python -m pip install tableauserverclient`

**Comment by t8y8** [comment]
Generally, in `venvs` or if using a system python install, `pip` will be on your path as well as `python`. Both are supported/standard ways to install

**Comment by fpagliar** [comment]
That's not the case for windows I think.
It makes sense that it is expected in linux environments.

**Comment by irwando** [comment]
Make a note of it in Windows vs Linux if that's the case.

**Comment by dzucker-tab** [comment]
@fpagliar could you say more about the context you encountered this in? I can't repro on either of my Windows boxes.

**Comment by paramasivan1** [comment]
how to install it on a linux machine

**Comment by bcantoni** [comment]
I think we have this covered with the pip install instructions here:
https://tableau.github.io/server-client-python/docs/#install-tsc

This should work on any system which has Python 3.5+ and pip installed.
