### ISSUE TITLE
Timeout issues 

### ISSUE THREAD

**Issue by stevetjamisonTM** [tableau/server-client-python#452]
We're getting some timeout errors when downloading dashboards from workbooks. Our server is configured to timeout at 30 minutes, but we're failing much faster than that. Is there a default or configurable timeout length in the code that might be contributing to our errors?

504 error
<tableauserverclient.server.endpoint.exception.InternalServerError>

Thanks for any help you can provide.

**Comment by bcantoni** [comment]
@stevetjamisonTM reviewing old issues I'm not sure whether this one was resolved. If you are still having issues, please reopen with some updated notes.
