### ISSUE TITLE
Add tags to View item

### ISSUE THREAD

**Issue by mcoles** [tableau/server-client-python#455]
I need to pull tags from a a specific view from Tableau Online. Right now it does not look as though that is possible with TSC. There was a recent addition to the REST API in the form of a [Get View](https://onlinehelp.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#get_view) endpoint, and it purportedly returns tags for the view requested. Could we add this functionality into TSC, please?

Thanks!

**Comment by toomyem** [comment]
I have submitted PR #466 for this.

**Comment by irwando** [comment]
Merged #470
