### ISSUE TITLE
bad request when publishing workbook with map

### ISSUE THREAD

**Issue by friep** [tableau/server-client-python#457]
I am experimenting with publishing workbooks using this library as my first attempts using the following code failed with a bad request error:
`
      400011: Bad Request
                There was a problem publishing the file 'scenarios.twbx'.
`

This is the code i am using: 

```
tableau_auth = TSC.TableauAuth('xxxx', 'xxxxx')
server = TSC.Server('https://myserver')

with server.auth.sign_in(tableau_auth):
    # i want to publish to the default project
    projects = [p for p in TSC.Pager(server.projects)]
    default_id = [p.id for p in projects if p.name == "Default"][0]
    print(default_id)
    workbook_item =  TSC.WorkbookItem(default_id, name="test", show_tabs=False)
    server.workbooks.publish(workbook_item, "../scenarios.twbx", "Overwrite") 
```
 
After some experiments with the superstore data, I have found:
- publishing a workbook **without maps works**: I removed the map from `scenarios.twbx` and exported it to a new file `scenarios_without_map.twbx`.  `    server.workbooks.publish(workbook_item, "../scenarios_without_map.twbx", "Overwrite")` then worked without problems. 
- publishing a workbook **with maps does not work** -> I get the bad request error. 

I have replicated this behavior with a minimal workbook I created using the superstore data.

Just wanted to bring this to your attention and verify whether someone else can replicate this behavior.

**Comment by RussTheAerialist** [comment]
What version of Tableau server are you running against and what version of
desktop was used to create the twbx?

We are going to try to reproduce this behavior internally to debug the
issue. This feels like it's not an issue with TSC, but with the underlying
publishing functionality or with the twbx.

**Comment by friep** [comment]
Thanks for the quick reply! 

the server is on 2019.1.3 and I am using Tableau Desktop 2019.2 on Mac. 

most probably, yes. I also tried the python code from https://github.com/tableau/rest-api-samples and it showed the same behavior. 
Should I better post the issue over there? Or via tableau support?

**Comment by RussTheAerialist** [comment]
We'll do the investigation/debugging to figure out what is going on and file the necessary defect internally and get it to the appropriate team.  I've already asked my team to take a look and try to repro it and debug what's going on.

**Comment by mikenac** [comment]
We are seeing this as well for workbooks that contain maps.

Server 2019.2, TSC 0.8
