### ISSUE TITLE
Bad Request on filtering projects with parentProjectId

### ISSUE THREAD

**Issue by nachtgold** [tableau/server-client-python#463]
I try to use the filter `parentProjectId`, to select a project within another one. As long as I can guarantee, that the name is unique, I can find it through its name. But tableau allows the same name within different project structures. So I want to improve the search by filtering its parent by id too.

But I get the message: 400065 Bad Request - The filter query contains a key which is not recognized for this api version.

* Tableau server version: 20183.19.0123.2221
* tableauserverclient 0.8
* user_server_version is used
* Last mention I found was in the update of 2018.2, but I seem, that is exists much longer

My code:
```
with server.auth.sign_in(tableau_auth):
    req_option = TSC.RequestOptions()
    req_option.filter.add(TSC.Filter('parentProjectId',
                                     TSC.RequestOptions.Operator.Equals,
                                     '4b09f97f-cb88-4cc1-abfb-258edd3f1196'))
    req_option.filter.add(TSC.Filter(TSC.RequestOptions.Field.ProjectName,
                                     TSC.RequestOptions.Operator.Equals,
                                     'ProjectX'))
    w, pagination_item = server.workbooks.get(req_option)
    print('{}'.format([wb.id for wb in w]))
```

Tableau version response:
```
<?xml version='1.0' encoding='UTF-8'?
    <tsResponse xmlns="http://tableau.com/api" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tableau.com/api http://tableau.com/api/ts-api-2.4.xsd">
    <serverInfo>
        <productVersion build="20183.19.0123.2221">2018.3.3</productVersion>    
        <restApiVersion>3.2</restApiVersion>
    </serverInfo>
</tsResponse>
```

Do you have any idea?

**Comment by RussTheAerialist** [comment]
In the code snippet, it looks like you are getting workbooks, not projects.  Workbooks do not currently support filtering by parent project id.

**Comment by nachtgold** [comment]
Oh wow, you are right, thanks. Getting the projects first is possible with `parentProjectId`.
