### ISSUE TITLE
Payload is either malformed or incomplete

### ISSUE THREAD

**Issue by AmeyMankar** [tableau/server-client-python#486]
I am using TableauServerClient to update the owner of a report on Tableau server. Here is my simple code:
`Try:
                single_workbook = server.workbooks.get_by_id(workbook_id)       #default ownerid of fsg_tableaureporting
                single_workbook.owner_id = ownerid

                if (server.workbooks.update(single_workbook)):
                    print('Workbook owner has been updated successfully')

                else:
                    print('Workbook owner could not be updated. Please try again. Exiting..')

            except Exception as e:
                print('Exceptions occured while changing the owner.')
                print(e)`

I get the exception at the statement server.workbooks.update(single_workbook). Anyone have any suggestions?

Python: 3.7.3
TSC: 0.8.1
Tableau server: 2019.1.3 (20191.19.0417.1429) 64-bit Windows

**Comment by irwando** [comment]
Hi @AmeyMankar 

Do you validate that the call to "get_by_id" successfully returns a valid workbook before continuing?

**Comment by AmeyMankar** [comment]
Thanks for responding. If I am debugging line by line, then I see that the workbook has been fetched successfully.

**Comment by irwando** [comment]
After the get_by_id call can you print out the name?  How are you validating that the workbook was successfully retrieved?

**Comment by AmeyMankar** [comment]
Yes, while debugging line by line, I see that the workbook has been properly retrieved. I have noticed that this is happening sporadically. Sometimes, code just works as it is, sometimes it hangs up on malformed payload error. I don't see a trend in the behavior.

**Comment by AmeyMankar** [comment]
any help anyone :(

**Comment by irwando** [comment]
Sorry, I was away on vacation.

Does the behavior only occur with certain workbooks?  Or does it fail then succeed with the same workbook?

**Comment by samgel** [comment]
Hi AmeyMankar,

Were you ever able to resolve this? I am having an identical issue and can't find a fix :(

**Comment by matsalts** [comment]
Is this still an ongoing issue? Encountered a similar problem. 

I am able to retrieve the name of the workbook just fine, however once I try to update it I receive this error:

`tableauserverclient.server.endpoint.exceptions.ServerResponseError:

        400000: Bad Request
                Payload is either malformed or incomplete`

**Comment by shiv-io** [comment]
Encountering the same issue when calling `server.subscriptions.create()`.

> `tableauserverclient.server.endpoint.exceptions.ServerResponseError:`
> 
> ```
>     400000: Bad Request
>             Payload is either malformed or incomplete`
> ```

I also inspected the XML payload and it did not appear to be malformed or incomplete, so I'm not sure what's causing the error.

My workaround for now is to construct an HTTP call with `requests` instead to create a subscription.
