### ISSUE TITLE
Add support for getting site by name and contenturl

### ISSUE THREAD

**Issue by benlower** [tableau/server-client-python#49]
Query Site (http://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_ref.htm#Query_Site%3FTocPath%3DAPI%2520Reference%7C_____56) has support for getting a site by name and content url:

GET /api/api-version/sites/site-name?key=name
GET /api/api-version/sites/content-url?key=contentUrl

Implement support in TSC for these (e.g. get_by_name(self, site_name))

**Comment by t8y8** [comment]
This is legacy from v1.0 of the API, should we just expose the new Filter/Sort parameters on the get sites call and deprecate this method?

**Comment by LGraber** [comment]
Yes. We already discussed. I meant to update this with exactly what you said. Those methods will be deprecated and we will expose / add Filter / Sort.

**Comment by RussTheAerialist** [comment]
implemented by #153
