### ISSUE TITLE
How to get Root Project Folder only

### ISSUE THREAD

**Issue by Barathwaja** [tableau/server-client-python#491]
Hi All,

I couldn't get only the RootFolder (Projects) present under Sites but its pulling all nested projects.

For example:
https://SERVERURL/#/site/Main/projects/111

Under this there are 5 Projects _(ie) Test1, Test2, Test3. Test4, Test5_

While using Python TSC, it pulls all Main + 5 Projects not only the Main when using the function **server.projects.get()**.

Is there a way to pull only root projects not _sub or nested projects_

**Comment by majordenny2012** [comment]
I also facing similar issue . I am logging to tableau server using TSC and downloading all the workbooks in local and pushing to git .But not able to generate the parent child relations hope it is not able to identify the RootFolder (Projects)   by TSC. Please confirm we can achieve this by TSC.

**Comment by Barathwaja** [comment]
@dzucker-tab any luck??

**Comment by dzucker-tab** [comment]
Yes, I can confirm that the topLevelProject attribute hasn't been exposed in TSC yet. Thanks much for calling this out this gap, as you can see @shinchris just pushed a PR to address this and I'll see if I can get it tested and merged this week.  

If you need a quicker fix, the workaround I can think of is to use the response from a REST request in combination with your TSC script.

**Comment by shinchris** [comment]
This has been fixed with PR #497 in our 'development' branch.

```
req_option = TSC.RequestOptions()
req_option.filter.add(TSC.Filter(TSC.RequestOptions.Field.TopLevelProject, TSC.RequestOptions.Operator.Equals, True))

all_projects, pagination_item = server.projects.get(req_option)
```

**Comment by Barathwaja** [comment]
@dzucker-tab Cool thanks !! 

@shinchris Thanks :) , and any ETA when this will be added to new release?

**Comment by majordenny2012** [comment]
@shinchris  Thanks a lot .Any ETA when this will be added to the new releases ?
