### ISSUE TITLE
Is there a way to authenticate to a Cloud IAP-secured resource?

### ISSUE THREAD

**Issue by leajab** [tableau/server-client-python#499]
I am trying to use this library to authenticate to a Cloud Identity-Aware Proxy (Cloud IAP)-secured resource from a user account. However, I don't see any way to include an IAP token. I saw a previous post saying TSC does not support SAML SSO, but I am using OAuth + OpenID and haven't seen any posts about that.

**Comment by jacalata** [comment]
Closing stale question - I think today this would be handled using Personal Access Tokens.
