### ISSUE TITLE
move_workbook_sites.py Pagination_Item

### ISSUE THREAD

**Issue by mcmillrk** [tableau/server-client-python#502]
Fairly new to the tableauserverclient scripts.

I'm trying to run the sample script, move_workbook_sites.py, and am getting the following error:

`Traceback (most recent call last):
  File "move_workbook_sites.py", line 100 in <module>
    main()
  File "move_workbook_sites.py", line 66, in main
    found_destination_site = any((True for site in all_sites if
TypeError: 'PaginationItem' object is not iterable`

What am I missing here? I haven't changed the sample code and am using Python 3.6.6.

I also succeeded in running the code move_workbook_projects.py using the same workbook.

**Comment by shinchris** [comment]
Thanks for pointing this out. I was able to reproduce the error and provide a fix (#503).
