### ISSUE TITLE
Clarify what TableauAuth site really is

### ISSUE THREAD

**Issue by benlower** [tableau/server-client-python#51]
Tableau Server sites have a site name and site id under site settings.

You can have a site name like "My Cool Site" and the side ID will have spaces removed (i.e. "MyCoolSite").

It's not clear what should be used when signing in with the client library. When I try to use tableau_auth.site = "My Cool Site" I get a 401001 Signin Error. However, when I use "MyCoolSite" things work.

We should clarify this via docs and/or having property names match what's in Tableau Server.

**Comment by RussTheAerialist** [comment]
Fixed by #70
