### ISSUE TITLE
Unable to log in to local user while configured to use OpenID Connect

### ISSUE THREAD

**Issue by rebecca-star** [tableau/server-client-python#511]
I am working with an instance of Tableau Server Version 2019.1 that is configured to use OpenID Connect (OIDC) for authentication with a local identity store. 

Is it possible to log into the REST API while the server is configured to use OIDC? If it's not you can ignore the rest of this issue but I've done a lot of digging and haven't been able to find a clear answer.

I've created an account in the local identity store that is not connected to OpenID Connect (OIDC) in any way but I still get the error code 401001 below when I attempt to post its credentials to the `https://MyTableauServer/api/3.3/auth/signin` endpoint.

```XML
<?xml version='1.0' encoding='UTF-8'?>
<tsResponse xmlns="http://tableau.com/api" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tableau.com/api http://tableau.com/api/ts-api-3.3.xsd">
    <error code="401001">
        <summary>Signin Error</summary>
        <detail>Error signing in to Tableau Server</detail>
    </error>
</tsResponse>
```

I know that the REST API does not support SAML single-sign (SSO) or OIDC. However the REST API reference seems to indicate that it is still possible to log into a "local" account through the REST API "depending on how you have configured Tableau Server" when using SAML SSO which also uses an external identity provider like OIDC. 

This is the note in the REST API reference I'm referring to and it can be found [here](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#sign_in).
> **Note:** The REST API does not use SAML single-sign (SSO) authentication. To sign in, you must specify the name and password of a user who has been created on the server. The user could have a local or Active Directory account, depending on how you have configured Tableau Server. For Tableau Online, you can specify the TableauID credentials of the user. You will have the permissions of the user that you're signed in as. You cannot use a SAML account for sign in when you use the REST API. For information about the requirements for using SAML, see [SAML Requirements](https://help.tableau.com/current/server/en-us/saml_requ.htm).

**Comment by manojmuthuraja** [comment]
Hello,
I have the same issue with Tableau Online with an authentication by tableau it works but with the openID google it's not working.I couldn't find any thread realting to that.You found any solutions to solve this issue?

**Comment by becca-star** [comment]
@manojmuthuraja I have not found any solutions. We have decided to proceed under the assumption that it is not supported since getting this working was a low-priority for us.

**Comment by manojmuthuraja** [comment]
Hello @becca-star ,
Thanks for replying.I posted the same question in the community tableau and here is the response:
Hi Manoj,

What you are experiencing is expected behaviour. If you want to use the Rest API you will need to have a user using Tableau Authentication
Authentication-Tableau Server REST API - Tableau:
https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_auth.htm
David


I let you check the link above for further details

**Comment by bcantoni** [comment]
Manoj comment above is correct; for authentication you would need to use either username/password or personal access tokens. The latter may be the best option when your system auth is using OpenID as you described.
