### ISSUE TITLE
You are trying to throw an error that you never even imported

### ISSUE THREAD

**Issue by dprophet** [tableau/server-client-python#514]
You are trying to throw an error

NonXMLResponseError

https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/endpoint/endpoint.py#L73

That you never imported. This totally breaks the debugging for us Corporate users that are behind all kinds of security systems. Please Fix ASAP.

**Comment by dprophet** [comment]
I totally disagree with this NonXMLResponseError error approach. The errors I am experience have to do with low level proxy, firewalls, certificates of authority, and NonXMLResponseError outright masks the error. These errors happen long before any communication has happened with Tableau Server.

**Comment by t8y8** [comment]
The issue I was trying to solve is that the current error handling code assumes you can parse one of our XML payloads with a specific set of tags and attributes.

ServerResponseError will throw a fairly gross stack trace if we revert this and you get an error from the Metadata API endpoints.

What I can do, is try to parse the XML, fail, and reraise the original exception

**Comment by dprophet** [comment]
First thing is first. Fix the import on

https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/endpoint/endpoint.py#L1

You need to import NonXMLResponseError

**Comment by t8y8** [comment]
Agreed, I pushed a fix in https://github.com/tableau/server-client-python/pull/515, it's in development now (where you can pull from to verify) -- we're discussing a patch release to master shortly as well.

**Comment by bcantoni** [comment]
I'm going to close this based on the end of the discussion where Tyler added the fix to import that error properly.
