### ISSUE TITLE
query string not escaping '+'

### ISSUE THREAD

**Issue by kurtbrose** [tableau/server-client-python#516]
1- create user with name='a+b'

2- fetch user with filter query set to name='a+b'; returns no items

3- fetch user with filter query set to name='a%2b'; returns user

I don't know how or where, but seems pretty clear somewhere it is doing `?name={name}` in a query string, and it should be encoding but isn't

**Comment by t8y8** [comment]
We aren't doing encoding ourselves anywhere, it's handled by the http library we use.

I can take a look when I have time, but I'm not sure what options we have available to us over the lower layer's encoding

**Comment by kurtbrose** [comment]
I fixed this by doing `urlencode()` on values before passing them to the API

**Comment by kurtbrose** [comment]
dude, you are doing string munging to generate query params

https://github.com/tableau/server-client-python/blob/b260ebcafec6e6ebe89597f13e1e18ed9ca55406/tableauserverclient/server/request_options.py#L95-L97

https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/request_options.py#L164

```python
        self._append_view_filters(params)

        return "{0}?{1}".format(url, '&'.join(params))
```

**Comment by kurtbrose** [comment]
that took me less than 5 minutes looking at the code

**Comment by kurtbrose** [comment]
sorry for being a little short, trying to get tableau integration working has been my life for the past week or so

**Comment by t8y8** [comment]
Right, but our http library itself encodes those values when it makes the request (I had a bug in the opposite direction recently, maybe this is actually related to that)

We can look at encoding it at the places you just mentioned, I just want to make sure nothing gets double encoded

**Comment by kurtbrose** [comment]
makes sense -- maybe it is possible to pass the query string to HTTP as a key/value dict instead of doing the string construction yourself?

**Comment by kurtbrose** [comment]
that seems to be the recommended way to use requests: https://requests.kennethreitz.org/en/master/user/quickstart/#passing-parameters-in-urls

**Comment by kurtbrose** [comment]
https://github.com/tableau/server-client-python/blob/b260ebcafec6e6ebe89597f13e1e18ed9ca55406/tableauserverclient/server/endpoint/endpoint.py#L45 looking here it tries to manually smoosh up the URL, but instead it good just say `parameters['params'] = request_object.get_query_params()` or similar

there's no issue -- body data is `data={...}`; so even on a post request you can set `params={...}` and everything works fine

**Comment by jacalata** [comment]
This works today.
