### ISSUE TITLE
Add certificate CA Bundle

### ISSUE THREAD

**Issue by yapnel** [tableau/server-client-python#522]
Hi

My tableau servers all have secure HTTP endpoints and i can't get the TSC connect securely. At the moment, i'm using verify false and this is not ideal. How do i specify the CA Bundle?

i have tried {'verify','path to CA bundle PEM'}  and it didn't work

Thanks

**Comment by RussTheAerialist** [comment]
Can you post your code and the output that is generated?  The verify is passed directly to Requests, so it should work assuming it's a valid CA Bundle Crt file.

There are a couple of other options you could try:

- Define the environment variable REQUESTS_CA_BUNDLE which points to your certificate bundle file. For example: /etc/ssl/certs/ca-certificates.crt. When this variable has been defined, requests will use it as the default for all connections, and so you don't need to modify any of your code.

- Fork package certifi, add your internal root-CA certificate to this, and then install with python setup.py install. When certifi is present, requests will default to using it has the root-CA authority and will do SSL-verification against the certificates found there.
