### ISSUE TITLE
Request R translation of Tableau Server Client Library

### ISSUE THREAD

**Issue by harrismcgehee** [tableau/server-client-python#53]
Since R is the primary statistical language supported by Tableau, many of your users likely have experience with R. I would love it if you translated the Tableau Server Client Library to R next!

**Comment by LGraber** [comment]
Thanks for the feedback. We have a couple of core languages that we know we have to do first (like Java) but we appreciate the input!

**Comment by Barathwaja** [comment]
Is anyone working on with Java or NodeJS? I can contribute if anyone is working on or going to start from scratch.

**Comment by dzucker-tab** [comment]
@Barathwaja - sounds like great contributions! What do you have in mind, samples?

I'll discuss the best approach for how/where to fit them with the crew and get back to you soon.

**Comment by Barathwaja** [comment]
No samples yet but if Java or Nodejs is demanded very high we can start working on it,.

**Comment by dzucker-tab** [comment]
@Barathwaja - very cool! I think the obvious first simple things would be Get Started kind of topics like sign in, create/list/update projects/workbooks/groups/users . . .

**Comment by jacalata** [comment]
Closing this for age and lack of priority.
