### ISSUE TITLE
Update Server versions and REST API versions

### ISSUE THREAD

**Issue by tdoug101** [tableau/server-client-python#537]
https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm

Tableau Server version | REST API version | Schema version

8.3, 9.0 | 2.0 | 2.0
9.0.1 and later versions of 9.0 | 2.0 | 2.0.1
9.1 | 2.0 | 2.0.1
9.2 | 2.1 | 2.1
9.3 | 2.2 | 2.2
10.0 | 2.3 | 2.3
10.1 | 2.4 | 2.4
10.2 | 2.5 | 2.5
10.3 | 2.6 | 2.6
10.4 | 2.7 | 2.7
10.5 | 2.8 | 2.8
2018.1 | 3.0 | 3.0
2018.2 | 3.1 | 3.1
2018.3 | 3.2 | 3.2
2019.1 | 3.3 | 3.3
2019.2 | 3.4 | 3.4
2019.3 | 3.5 | 3.5
2019.4 | 3.6 | 3.6

**Comment by bcantoni** [comment]
The newer versions have recently been added to the list at https://tableau.github.io/server-client-python/docs/versions
