### ISSUE TITLE
Add Description to WorkbookItem class

### ISSUE THREAD

**Issue by Evernite** [tableau/server-client-python#539]
Pulling description from REST API was added with v3.1 but TableauServerClient API documentation does not show the field as available to pull.

Looks like the REST API documentation shows that the field was added to the API response for the endpoint 'workbooks_endpoint'.

Use case would be the ability to call something like 'workbook.description' to pull the Description field from the Tableau workbook published to the server.

**Comment by shinchris** [comment]
This was added into our development branch with #533. 
It will be available in the master branch with the next release.
