### ISSUE TITLE
Add support for prior API versions

### ISSUE THREAD

**Issue by ghost** [tableau/server-client-python#54]
Currently only `2.3` is supported. Would be great to have the ability to specify the API version when setting the server URL.

**Comment by RussTheAerialist** [comment]
Thanks for the issue.  You can do the following to change versions:

```python
# assume you have created a server object but have not signed in yet
server.version = 2.4  # Or whatever
```

This allows you to set the version, but it doesn't do any checking to makes sure it's a valid version, yet.

We are planning to add version checking to all of the methods so if you are trying to use a version where the particular feature isn't supported, we throw an exception.

**Comment by iwderek** [comment]
Perfect. Thanks!

**Comment by LGraber** [comment]
Note, also, that you can change the version in between calls. You can sign in with version 2.3 and call server.workbooks.get on 2.4. I have no idea why you would but we made sure it would work.

**Comment by reevery** [comment]
I'm successfully running some queries with 2.2 as well. I've found a couple which don't work aside from the ones without endpoints.
server.workbooks.publish gives 400011 errors with 2.2.

**Comment by RussTheAerialist** [comment]
I just fixed a bug related to namespaces that also caused problems with older versions of the server.  0.5 will have this fix in it.  Please let me know (once 0.5 releases) if you are still running into this issue.
