### ISSUE TITLE
Setting Priority for a Datasource Refresh

### ISSUE THREAD

**Issue by HCStringer** [tableau/server-client-python#541]
Hi There!

I noticed when I use TSC to perform a Datasource Refresh, it automatically sets priority to 0. I was wondering if there was a way to manually set the priority of each refresh (to 50, for example)? If not, is there any convenient workarounds?

Many Thanks,

Stringer

**Comment by jacalata** [comment]
Jobs that are started manually always have priority 0 - this is something that would have to be modified server-side. I'll make a suggestion to the team that owns priorities, I'm not sure why it's designed like this so they might be open to changing it.

**Comment by jacalata** [comment]
There are no plans to add this capability, for server resource management reasons.
