### ISSUE TITLE
Timeout value connect was Timeout(connect=None, read=None, total=None) is thrown while attempting to connect to Tableau online

### ISSUE THREAD

**Issue by JnaneshPrabhu** [tableau/server-client-python#547]
There seems to be some issue while trying to connect to Tableau Online using Python.
What i need is to get a workbook's PDF downloaded using python .
The code used is:
import tableauserverclient as TSC  
  
tableau_auth = TSC.TableauAuth('<user>', '<pass>','<sitename>')   
server = TSC.Server('https://10az.online.tableau.com')   
server.auth.sign_in(tableau_auth)   

Error thrown:
ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.
This may be due to outdated libraries being used in source code.
I have also updated the other libraries on which this may depend on Ex: urllib3
Please check and revert.

Thanks

**Comment by jthomson3** [comment]
Having the same issue. I can't get it to run

**Comment by jacalata** [comment]
Not sure what was happening here, but I'm going to assume that we have since fixed it.

**Comment by gyurho** [comment]
pip install "urllib3<2.0.0" 

This helped me
