### ISSUE TITLE
List all Users of a site

### ISSUE THREAD

**Issue by Morju** [tableau/server-client-python#558]
Hi,
is there any option to get a list of users from a chosen site?
I've been searching a while now but can't find anything usefull.

**Comment by dzucker-tab** [comment]
Have you looked at:

https://tableau.github.io/server-client-python/docs/api-ref#users

?

**Comment by dzucker-tab** [comment]
Have you looked at `users.get` at: 

https://tableau.github.io/server-client-python/docs/api-ref#users
