### ISSUE TITLE
Login doesn't work with 20201.0.0.0

### ISSUE THREAD

**Issue by iSteal** [tableau/server-client-python#579]
I'm using version 20201.0.0.0 and I can't login using neither the RESTful API or the python tableau client. I get the error message

`b'{"timestamp":,"status":401,"error":"Unauthorized","message":"Please log in at /login in order to proceed.","path":"/api/3.7/auth/signin"}'`

I can't find any reference to the /login endpoint, but I noticed the web interface uses /api/0.5/login. Maybe they changed the API without updating the documentation?

Also, I am using a demo license.

**Comment by RussTheAerialist** [comment]
What URL are you using for the server address?

**Comment by iSteal** [comment]
I am using https://localhost:8850. 

`tableau_auth = TSC.TableauAuth([redacted],[redacted])
server = TSC.Server('https://localhost:8850')
server.add_http_options({'verify': False})
server.version = '3.7'
`

**Comment by RussTheAerialist** [comment]
And what kind of authentication is your server configured for?

**Comment by iSteal** [comment]
I am using local authentication. I verified that the credentials work when copied and pasted in the web interface.

**Comment by RussTheAerialist** [comment]
hrm okay, I'm going to try to repro it locally to see if I can capture some network traces to figure out what is going on.  The API hasn't changed, so you shouldn't be seeing this.  Just for completeness, Windows or Linux?

**Comment by iSteal** [comment]
Windows 10. I did notice 20201.0.0.0 was not included in the versions list:
https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm

**Comment by RussTheAerialist** [comment]
We only report on the release number on that list which is 2020.1, which is at the bottom of the list.  There is no expected changes other than bug fixes in any of the 2020.1.x.x releases past 2020.1.0.0 as those are all bugfix-only releases.

**Comment by iSteal** [comment]
Odd. I wonder if somehow the credentials are wrong. The error message is confusing and not helpful at all. I should also mention I'm using a local account, so I use ".\test" (or ".\\test" when escaped) for the username.

**Comment by RussTheAerialist** [comment]
is that what you use in the UI as well as the API?  I don't know if I've ever tried special characters in the username.  Can you try without the `.\\` or `.\` and see if you get the same error?

**Comment by iSteal** [comment]
Yes, I have to use that in the UI or it fails. I can also use hostname\user, but that doesn't work either.  I get the same error nonetheless.

**Comment by RussTheAerialist** [comment]
Just out of curiosity, if you create a personal access token, can you login with that? Details about PATs can be found here: https://help.tableau.com/current/server/en-us/security_personal_access_tokens.htm and there is a sample in TSC that shows how to login with them.  That's available here: https://github.com/tableau/server-client-python/blob/master/samples/login.py (look in the `else:` clause near the bottom)

**Comment by iSteal** [comment]
I cannot seem to find the tab to create one. In configuration->User Identity & Acesss I have set localhost as a trusted host with a token length of 24. There is no account settings menu. 

![image](https://user-images.githubusercontent.com/45405755/76126273-aa19b500-5fcc-11ea-84b8-03b0da5a1200.png)

**Comment by RussTheAerialist** [comment]
Are you trying to connect to the Server Management service?  That UI does not look like Tableau Server, but the Manager.  TSC is only for use with Tableau Server.

**Comment by iSteal** [comment]
Ah that is my problem. I thought the TSC was the main gateway. Once I used the main gateway as the address and credentials, it worked.
