### ISSUE TITLE
Can I keep a session alive and use an auth token for subsequent requests?

### ISSUE THREAD

**Issue by jdomingu** [tableau/server-client-python#58]
I started toying with creating a portal and I couldn't find a way to keep a session alive. 

As an example: 
I send a request to get a list of my workbooks.
I send a follow-up request with a particular workbook id (on a different web page) to get the list of views for that workbook. 

Do I have to call the auth.sign_in function each time I send a new request? It's not ideal if I have to store the username and password somewhere server-side to do this--I would prefer to store the auth token and just use that with subsequent requests.

**Comment by t8y8** [comment]
You just do it.

```
server = TSC.Server(auth_info)
server.sign_in()
server.workbooks.get()
server.datasources.get()
```

All of the samples use the context manager, which closes it.

**Comment by RussTheAerialist** [comment]
One thing that I had to implement in the currently undisclosed "other version" is the ability to save the auth token and then have an auth token authentication scheme which would skip login and use the auth token as if you already signed in.  I think we should implement something like it here.

**Comment by jdomingu** [comment]
Derp! Thanks @t8y8 That makes sense. 

@RussTheAerialist that would be great functionality to have. I hope that makes it into a future release :)

Closing this issue for now.

**Comment by MetricMike** [comment]
I needed this pattern for a background job, and came up with the following recipe based on internal/undocumented api (so pip upgrade at your own risk if you use this)

```python
import json
import tableauserverclient as TSC


def refresh_auth_token(server):
    tableau_auth = TSC.TableauAuth(
        'USERNAME',
        'PASSWORD',
        site_id='SITE')

    server.auth.sign_in(tableau_auth)

    credentials = {
        'site_id': server._site_id,
        'user_id': server._user_id,
        'auth_token': server._auth_token
    }

    with open('/tmp/tableau_credentials', 'w') as file:
        json.dump(credentials, file)

    return server


def sign_in(server):
    try:
        with open('/tmp/tableau_credentials', 'r') as file:
            credentials = json.load(file)

        server._set_auth(
            credentials['site_id'],
            credentials['user_id'],
            credentials['auth_token'])

        server.sites.get()
    except (FileNotFoundError, TSC.NotSignedInError, TSC.ServerResponseError) as e:
        return refresh_auth_token(server)


def do_something_on_tableau():
    server = TSC.Server(
        'https://commandhub.democrats.org',
        use_server_version=True)
    sign_in(server)

    print(server.sites.get())

```
