### ISSUE TITLE
Add support for the max_age parameter for views.populate_csv

### ISSUE THREAD

**Issue by timothyvermeiren** [tableau/server-client-python#581]
The REST API supports passing a max_age parameter when [querying view data](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#query_view_data) to avoid hitting the cache when requesting the data for a view. Currently, the [method](https://tableau.github.io/server-client-python/docs/api-ref#viewspopulate_csv) `views.populate_csv` or the [CSVRequestOptions class](https://tableau.github.io/server-client-python/docs/api-ref#csvrequestoptions-class) do not.

Is it on the roadmap to add that capability? There is [this workaround](https://github.com/tableau/server-client-python/issues/568#issuecomment-596151576), but native support would be interesting.

**Comment by rookxyz** [comment]
The same should be added to view.populate_pdf.

**Comment by ndolash** [comment]
@timothyvermeiren @rookxyz 

I made a change to the TSC library so maxage (maxAge as in API spec) parameter is used in PDFRequestOptions class, however I still receive the cached PDF, so I am not sure if this is relevant for the caching solution. 

I cannot even try different pagetype.

**Comment by rookxyz** [comment]
To verify cache update I used the following test:
1. Generate PDF
2. update data source, wait maxAge minutes
3. Generate PDF - this should come with the new data (updates cache for around 75% of time for me, which was better than users clicking in the Web UI). Not perfect but acceptable.
