### ISSUE TITLE
PDFRequestOptions - Unspecified

### ISSUE THREAD

**Issue by sfarr15** [tableau/server-client-python#587]
Hi, we are trying to download a number of daily Tableau reports in PDF format. Unfortunately there is no option to define the page_type as 'unspecified' using the PDFRequestOptions function - confining us to first generate an image and then convert this image to PDF (losing quality and adding to file size)
Can this be added as this would help us out greatly! 
Regards,
Steve

**Comment by sfarr15** [comment]
Hi @shinchris,
This request is on behalf of comeon group. We would appreciate if this could be resolved as quickly as possible!

**Comment by Steven-Comeon** [comment]
Any updates on this please? @shinchris

**Comment by shinchris** [comment]
@sfarr15 @Steven-Comeon Which version of Tableau server do you use?

**Comment by VitaliyBb** [comment]
Anyone having any luck finding a working around for this issue?

**Comment by bhlmn** [comment]
This is also something that my team would like! Anyone have any luck with this?

**Comment by sfarr15** [comment]
Hi,

We ended up generating the images using the unspecified format and converting them to pdf. 

This worked out fine although it adds an extra step.

**Comment by bhlmn** [comment]
Thanks so much @sfarr15. We'll give that a shot.

**Comment by jacalata** [comment]
Addressed in https://github.com/tableau/server-client-python/pull/589
