### ISSUE TITLE
Schedule a refresh using Bridge

### ISSUE THREAD

**Issue by hani1814** [tableau/server-client-python#597]
Hi,

I'm new TSC and have been looking at the documentation on how to schedule a datasource. I can't see anything that allows to create a schedule, point to a client machine running bridge and schedule.

I would be grateful if someone can point me in the right direction

Thank you

**Comment by harshit2283** [comment]
Hi,
Was anyone able to figure this out?

**Comment by jacalata** [comment]
Unfortunately you can't manage Bridge clients and schedules through the API. If you are using Bridge with Tableau Online, you can now use the standard Online schedules and the Bridge clients are managed in the background. If you're using Tableau Server, then this still requires the UI. 
https://help.tableau.com/current/online/en-us/to_sync_schedule.htm
