### ISSUE TITLE
Unable to connect to tableau server using TableauServerClient python library

### ISSUE THREAD

**Issue by jamesdrabinsky** [tableau/server-client-python#601]
I am trying to sign into TSC with the following:
```
tableau_auth = TSC.TableauAuth(name, password, site_id=site_id)
server = TSC.Server('http://10az.online.tableau.com', use_server_version=True)
print(server.version)
# Sign in
server.auth.sign_in(tableau_auth);
```
I am getting this error message.  I have never got this message before when trying to sign into the server with TSC
`SSLError: HTTPSConnectionPool(host='10az.online.tableau.com', port=443): Max retries exceeded with url: /api/2.4/serverInfo (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))`

Does anybody have an idea why this is happening?

**Comment by qingfei1994** [comment]
I think you have connected to a Tableau Server enabled SSL. You need to verify and make your client program trust the SSL certificate.
Firstly you need to make sure you use the right url.
Secondly, if you want to skip verification of SSL cert, you can simply use 
`server.add_http_options({'verify': False})`

**Comment by bcantoni** [comment]
I'm going to close this based on age, but if you are still having trouble please reopen with the latest details.
