### ISSUE TITLE
error while connecting to tableau server.

### ISSUE THREAD

**Issue by sheetalgolecha15** [tableau/server-client-python#606]
HI,
I am trying to connect to tableau server using the tableauserverclient, when i do it on anaconda it works fine.

Same script when i run in databricks it doesnt work correctly and gives me the below error.

Script:
tableau_auth = TSC.TableauAuth(x, y,site-name)

server = TSC.Server('https://tableau.tomtomgroup.com/')
options = TSC.RequestOptions(pagesize=1000)

server.auth.sign_in(tableau_auth)

Error:
arseError: not well-formed (invalid token): line 180, column 115
Traceback (most recent call last):

  File "/databricks/python/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<command-323620733056009>", line 6, in <module>
    server.auth.sign_in(tableau_auth)

  File "/databricks/python/lib/python3.7/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 127, in wrapper
    return func(self, *args, **kwargs)

  File "/databricks/python/lib/python3.7/site-packages/tableauserverclient/server/endpoint/auth_endpoint.py", line 33, in sign_in
    parsed_response = ET.fromstring(server_response.content)

  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: not well-formed (invalid token): line 180, column 115

the version of python on databricks is 3.7 and the version of my tableau serverclient is 0.10 ( i have tried with 0.9 and 0.8 both gives me same error)

**Comment by bcantoni** [comment]
@sheetalgolecha15 cleaning up old issues -- is this working correctly now or you still need help?

**Comment by FULAN494** [comment]
Hi

Tableau server =2020.2
Rest API version =2.3 but i hard coded it as 3.8 

I am trying to connect to tableau server using the tableauserverclient, but it is throwing error 
even i fetched the site_id ,site_name ,site_rul ,state ,the same i am passing in code (site_id='Anthem')
Below is code which i am using 


#setup Authentication
tableau_auth = TSC.PersonalAccessTokenAuth('token_name', 'token_value', site_id='Anthem')

#tableau_auth = TSC.TableauAuth('fulnagar@in.ibm.com', 'pw', site_id='Anthem')
server = TSC.Server('https://aisolutions.anthem.com', use_server_version=True)
#server.auth.sign_in(tableau_auth)
with server.auth.sign_in(tableau_auth):
    all_datasources, pagination_item = server.datasources.get()
    print("\nThere are {} datasources on site: ".format(pagination_item.total_available))
    print([datasource.name for datasource in all_datasources])
    all_workbooks, pagination_item = server.workbooks.get()
    print("\nThere are {} workbooks on site: ".format(pagination_item.total_available))
    print([workbook.name for workbook in all_workbooks])
    print(server.version)
    all_sites, pagination_item = server.sites.get()

  # print all the site names and ids
    for site in all_sites:
       print(site.id, site.name, site.content_url, site.state)

request_options = TSC.RequestOptions(pagesize=1000)
print("\n request_options :".format(pagination_item.total_available))
request_options.filter.add(TSC.Filter(TSC.RequestOptions.Field.UpdatedAt,TSC.RequestOptions.Operator.GreaterThanOrEqual,'2021-07-09T00:00:00Z'))

all_workbooks, pagination_item = server.workbooks.get(request_options)

for wb in all_workbooks:

    print(wb.name)

------------------------------------------------------------------
 request_options :
Traceback (most recent call last):
  File "tabeau_cancel_job.py", line 65, in <module>
    all_workbooks, pagination_item = server.workbooks.get(request_options)
  File "/apps/anaconda3/lib/python3.6/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 138, in wrapper
    return func(self, *args, **kwargs)
  File "/apps/anaconda3/lib/python3.6/site-packages/tableauserverclient/server/endpoint/workbooks_endpoint.py", line 38, in get
    url = self.baseurl
  File "/apps/anaconda3/lib/python3.6/site-packages/tableauserverclient/server/endpoint/workbooks_endpoint.py", line 32, in baseurl
    return "{0}/sites/{1}/workbooks".format(self.parent_srv.baseurl, self.parent_srv.site_id)
  File "/apps/anaconda3/lib/python3.6/site-packages/tableauserverclient/server/server.py", line 139, in site_id
    raise NotSignedInError(error)
tableauserverclient.server.exceptions.NotSignedInError: Missing site ID. You must sign in first.


Please help me out

**Comment by bcantoni** [comment]
I'm going to close this one out.

@FULAN494 your issue seems different from the original report here. If you're still having that issue would you please open a new issue with all the details?
