### ISSUE TITLE
Pass in parameters to the workbook

### ISSUE THREAD

**Issue by qiubill** [tableau/server-client-python#616]
We are using the Tableau Server Client python API, works really well, we are able to export the workbook to pdf. 

One question though, some of our workbooks do take the parameter, we can hit them from browser and pass in the parameter, but I did not find a way to pass workbook parameter from python API. 

Can you please help?

**Comment by qiubill** [comment]
I feel this is a very basic requirement to pass the parameter to workbook and populate the pdf, unfortunately it does not support?

**Comment by kevinwpeters-thd** [comment]
You should be able to pass a parameter just like you would any other filter.

pdf_req_option = TSC.PDFRequestOptions(page_type=TSC.PDFRequestOptions.PageType.Letter,
                                              orientation=TSC.PDFRequestOptions.Orientation.Landscape)
pdf_req_option.vf(nameOfParameter,parameterValue)

I have this currently working in my use case.

**Comment by lucical** [comment]
When I do that, I am getting empty PDFs (no data, just column names and the parameter name does no change from the default one). This piece of code works for filters but not parameter views. 

`pdf_req_option = TSC.PDFRequestOptions(
                page_type=TSC.PDFRequestOptions.PageType.A4,
                orientation=TSC.PDFRequestOptions.Orientation.Landscape)
            pdf_req_option.vf("Country", "DE")
            print(pdf_req_option)

            server.views.populate_pdf(view, pdf_req_option)`

**Comment by kevinwpeters-thd** [comment]
@lucical I can't speak to your use case, but I can confirm I'm able to pass values into a parameter with my above code.

In my use case I have a parameter called "Vendor Selection", a calculated field called "Vendor Filter", and a dimension called "Vendor". The "Vendor Filter" calculated field assesses whether or not the "Vendor" dimension matches the "Vendor Selection" parameter, and I have this calculated field as a filter on my worksheet, keeping only the TRUE results.

My request options filter code looks like: 
`pdf_req_option.vf('VendorSelection',vendorList[i])`
where I am iterating through a list of vendors.

I also ensured I do not have a dimension/measure with the same name as my parameter, as I'm not sure how the API would parse that.

**Comment by lucical** [comment]
@kevinwpeters-thd  
_I also ensured I do not have a dimension/measure with the same name as my parameter, as I'm not sure how the API would parse that._

This is something that helped me solve the issue! The parameter name and the parameter title were different hence I was getting empty PDFs.

Thanks!

**Comment by illonage** [comment]
Feel free to reopen the issue if you think that the issue is not solved

**Comment by flicknewb** [comment]
I am having this same issue where I am passing, in my case, into the filter ('SiteP', site[i]) where I am iterating over the site. 

However I am only ever able to see one view, I get the last site loaded onto the tableau server, and applying the filter changes nothing in the output files. How can I force setting this as a parameter?
