### ISSUE TITLE
Workbook update does too much if all I did was change the tag set

### ISSUE THREAD

**Issue by LGraber** [tableau/server-client-python#62]
I like our model of simplifying the model so that tags are just a set on the workbook and you can modify the set and then simply call "update". However, we are not tracking whether anything else changed on the workbook and so are calling "update" on the general workbook properties always which makes changing the tags unnecessarily expensive. We need to have some _dirty boolean that is set to false after parsing the results and flipped when any property is set. Then we can avoid unnecessary calls when nothing has changed.

**Comment by t8y8** [comment]
I agree that our 'Update' pattern is a little weird, and it makes some of our setter code more complicated than it needs to be.

**Comment by jacalata** [comment]
If this is done it will be in the course of other work.
