### ISSUE TITLE
filter view with ID

### ISSUE THREAD

**Issue by rferraton** [tableau/server-client-python#620]
In the doc Api reference,  the req_option parameter in the view section mention that it is possible to filter views get using id. 
May i am wrong but it seams not possible to filter using the ID of a view.

**Parameters**

Name | Description  
:--- | :---  
`req_option`  |  (Optional) You can pass the method a request object that contains additional parameters to filter the request. For example, if you were searching for a specific view, you could specify the name of the view or **its ID**.
`usage` | (Optional) If true (`usage=True`) returns the usage statistics for the views. The default is `usage=False`.

**Comment by jacalata** [comment]
Not wrong at all - https://github.com/tableau/server-client-python/pull/680

**Comment by shinchris** [comment]
You can use views.get_by_id() instead - [see documentation](https://tableau.github.io/server-client-python/docs/api-ref#viewsget_by_id).

**Comment by adbumi** [comment]
The endpoint **views.get_by_id()** only exists in the documentation but not in the source code :-(
