### ISSUE TITLE
ViewItem Tag Bug

### ISSUE THREAD

**Issue by erich-trabus** [tableau/server-client-python#622]
https://github.com/tableau/server-client-python/blob/188be71e0fbe9d87ac36628af21d2f63af32d020/tableauserverclient/models/view_item.py#L161

should be:

``` python
import copy
...
view_item._initial_tags = copy.copy(tags)
```
otherwise tags won't update/delete properly. Is this bug worth a pull request?

**Comment by bcantoni** [comment]
@erich-trabus thanks for reporting this; it's been fixed in the pull request mentioned above.
