### ISSUE TITLE
Can we update tableau connection string via tableauserverclient api?

### ISSUE THREAD

**Issue by rgandhi2712** [tableau/server-client-python#624]
Hello All,
My use-case requires me to update the connections of all those workbooks/datasources that are connected to certain Redshift databases on tableau server.

I tested a script leveraging tableauserverclient API to update the credentials of published workbooks/datasources connections pointing to those Redshift databases and was able to update it successfully.

After the credentials update, workbooks published using following connection methods:

1. Standard user-password connection:  These workbooks worked fine after the script update.

2. ODBC Connection or Redshift connection with custom driver parameters: Although the script updated their username and password details, they failed to connect to the data source.

Our objective is to avoid access to Redshift using individual credentials and enable via IAM profile and Redshift SSO feature based on user's permissions in the architecture.

Since Tableau doesn't support SSO connectivity to Redshift, we devised a strategy to allow users to create workbooks using method #2 and then update the connection details as soon as their workbooks are published on server with method #1 where credentials used in #1 won't be shared with anyone except the admin team.

In order to find out why option #1 works but #2 fails miserably, I compared their connection entries in "public.data_connections" table of the Tableau Server database and observed difference in "Keychain" column of the mentioned table. The custom driver parameters embedded in publishing the workbook (using #2) are stored in keychain column as value of the "odbc-connect-string-extras" field whereas same field is empty for option #1:

Keychain column for option #1:
{odbc-connect-string-extras: '';
server: server1.redshift.amazonaws.com, dbname: test_database,
  port: 5439, class: redshift, username: tableau_user}

**Keychain column for option #2:**
{odbc-connect-string-extras: DbUser=tableauuser; DbGroups=tableaugroup; Iam=1; AutoCreate=true;Profile=default;
server: server1.redshift.amazonaws.com, dbname: test_database,
  port: 5439, class: redshift, username: tableau_user} 

Since we do not want to provide access to Redshift using individual credentials, please let us know if there is an alternate approach for achieving this?
OR;
Is there any method or workaround for updating connection to use user-password (after being published on server) instead of using values from "odbc-connect-string-extras" field in keychain column?

 
Versions used in testing:
Tableau Server version: 2019.2
Tableau desktop version: 2019.2.3

 
Password update script reference:
[API Reference](https://tableau.github.io/server-client-python/docs/api-ref#workbooksupdate_connection)

**Comment by rgandhi2712** [comment]
Has anyone else faced this issue before..?

**Comment by jacalata** [comment]
This is pretty old, but this should be do-able using the Document API (https://github.com/tableau/document-api-python).
