### ISSUE TITLE
In views.populate_csv,  consider support for the max_age parameter.

### ISSUE THREAD

**Issue by ashwinpn** [tableau/server-client-python#628]
When querying view data the REST API supports passing a max age parameter to avoid hitting the cache when requesting the data for a view. The views.populate csv method, or the CSVRequestOptions class, is not currently used.

Are there any current plans to implement something along these lines?

**Comment by razze76** [comment]
I would need this as well. Any plans for implementing anytime soon.

**Comment by shinchris** [comment]
Implemented with #635 and #639 in the `development` branch.
