### ISSUE TITLE
Not able to filter the workbook if it has special characters in the name

### ISSUE THREAD

**Issue by KarthikINV** [tableau/server-client-python#632]
tableau_auth = TSC.TableauAuth(user_name, password,sitename)
    req_option = TSC.RequestOptions()
    req_option.filter.add(TSC.Filter(TSC.RequestOptions.Field.Name,
                                         TSC.RequestOptions.Operator.Equals, US Rating & TER Monitor))
    all_workbooks, pagination_item = server.workbooks.get(req_option)

I'm getting the Empty Workbook item list while executing above .

**Comment by shinchris** [comment]
Ampersands (and commas) are not supported as filter values by the Rest API, even if URL encoded. Filter requests are sent as URL query parameters, in which ampersands and commas are reserved as delimiters.

**Comment by abshomali** [comment]
Dealing with commas worked for me by adding a `\` before the commas in the string. Example:
`image_req_options.vf('Industry', 'Footwear\, Clothing')` instead of  `image_req_options.vf('Industry', 'Footwear, Clothing')`. Could work for ampersands too.

**Comment by illonage** [comment]
Feel free to reopen the issue if you think that the issue is not solved

**Comment by lalalennox** [comment]
Big thanks to @abshomali - this worked for me where everything else I tried had not. 

> Dealing with commas worked for me by adding a `\` before the commas in the string. Example: `image_req_options.vf('Industry', 'Footwear\, Clothing')` instead of `image_req_options.vf('Industry', 'Footwear, Clothing')`. Could work for ampersands too.
