### ISSUE TITLE
Get list of all workbook from Tableau server

### ISSUE THREAD

**Issue by tripathirishabh8** [tableau/server-client-python#633]
Hi,

I am a server admin and my objective is to get list of all workbooks present on Tableau server.
But If I am specifying site_id then only the content of that particular site is coming and if I am not specifiying the site_id then, the content of only default site is coming.

How to get the list of all workbook irrespective of sites?
Thanks
Rishabh

**Comment by alexisnotonffire** [comment]
I'm not aware of anything in the API that would allow you to do this and don't expect there to be as I don't believe you're able to explore combined site content in the web UI either.

I think you'll want to loop over a collection of TableauAuth credentials providing a login to each site and run your workbook get function against each site. For example, you'd use something like the following: 
```python
import tableauserverclient as tsc

# server admin creds
host="tableaudomain.com"
user="username"
pwrd="password"

tableau = tsc.Server(host, use_server_version=True)
auth = tsc.TableauAuth(user,pwrd)

site_auths = []
with tableau.auth.sign_in(auth):
    site_auths.extend(
        tsc.TableauAuth(user, pwrd, site.id) 
        for site in tsc.Pager(tableau.sites))

workbooks=[]
for site_auth in site_auths:
    with tableau.auth.sign_in(site_auth):
        workbooks.extend(tsc.Pager(tableau.workbooks))

print(workbooks)```

If you're open to not using this API - and have access to it - you could just dump it out from the [workgroup database](https://help.tableau.com/current/server/en-us/data_dictionary.htm).

**Comment by jorwoods** [comment]
Starting with #655 you can use a baked in site switch rather than creating separate auth objects.

**Comment by jacalata** [comment]
This isn't on the roadmap.
