### ISSUE TITLE
Publishing a datasource to Tableau Online using Python

### ISSUE THREAD

**Issue by samyak53** [tableau/server-client-python#634]
Hi,
I am trying to publish an extracted datasource with the name sample.hyper using the server.datasources.publish command. Even though the command executes and the datasource is published, I am not able to pass any connection related information with the datasource.

I am creating an object of the class ConnectionItem which has the server address, username, password attributes and trying to link it to the datasource before publishing so that I have access to manipulate the connection on the Tableau Online UI.

Can someone please help me understand how I can pass the Connection details while publishing the extracted datasource with the API.

Connection Item created as follows: conn_item = TSC.ConnectionItem()
Attempt to link to the datasource object as follows:

ds_item = TSC.DatasourceItem(Project_id, name='sample')
ds_item._connections = conn_item
 ds_item = server.datasources.publish(ds_item,  local_path_to_extract, mode = 'CreateNew',
                            connection_credentials = conn_item.connection_credentials)

**Comment by felipe-costa-compado** [comment]
Hey, @samyak53,
Maybe you can try something like this:

```
import tableauserverclient as TSC

tableau_auth = TSC.TableauAuth(
        username=conn.login,
        password=conn.password,
        site_id='',
    )
    
    server = TSC.Server(SERVER_ADDRESS, use_server_version=True)
    
    with server.auth.sign_in(tableau_auth):
        ...
        ## rest of the code
        ...
```
