### ISSUE TITLE
user got added to the site , but fails to loop through the list of user 400003:Bad Request

### ISSUE THREAD

**Issue by mohitbhandari37** [tableau/server-client-python#636]
Hi Team,
I have list of user like [a_publisher,b_interactor] i am looping through the list and adding the user but the code got erred with below message :- 

```
tableauserverclient.server.endpoint.exceptions.ServerResponseError: 
    user1 = TSC.UserItem('temp1', 'Viewer')
     
      #add new user
    with server.auth.sign_in(tableau_auth):
    user_to_add='test'
    new_user = TSC.UserItem(name=user_to_add, site_role='Interactor')
    new_user = server.users.add(new_user)

        400003: Bad Request
                Payload is either malformed or incomplete
```

Stuck from last 2 hrs

Note :- a_publisher got added to site but it throws exception.

**Comment by bcantoni** [comment]
@mohitbhandari37 reviewing older issues, can you comment on whether this has been solved yet? If it's still a problem, could you include the version number of Tableau Server and TSC library as well?

**Comment by bcantoni** [comment]
I'll go ahead and close. Please reopen with details requested if you still need help on this.

**Comment by mbabatunde** [comment]
@bcantoni I am currently the same issue. Using 0.15 as the API version and 3.9 for the server version
