### ISSUE TITLE
Issue with "TSC.RequestOptions.Operator.In" operator

### ISSUE THREAD

**Issue by alinacornea** [tableau/server-client-python#637]
Hello, 

I'm trying to use the IN operator by searching for multiple views
```
views_name = ['view_name1', 'view_name2']

options = TSC.RequestOptions()
options.filter.add(TSC.Filter(TSC.RequestOptions.Field.Name, TSC.RequestOptions.Operator.In, views_name))

views = server.views.get(req_options=options)
print(views)
```
However it results in an empty list
`([], <tableauserverclient.models.pagination_item.PaginationItem object at 0x11b07bc50>)`

It does work when using a single view name and the "Equals" Operator. Is this a known issue or a bug? Thank you

**Comment by bcantoni** [comment]
@alinacornea catching up on some old bug reports, I took a closer look at this one. Testing with the current library version this seems to be working correctly.

If you're still having problems, can you try again with the current version of the TSC library?
