### ISSUE TITLE
Issue while publishing workbook

### ISSUE THREAD

**Issue by mohitbhandari37** [tableau/server-client-python#641]
Hi ,

We have a workbook that has live connection of datasource, i am trying to publish to same via the tableau server client api but it throws error with 

        403007: Forbidden
      workbook failed to establish a connection to your datasource.

The connection string in both datasource and workbook are same, the script fails at (server.workbooks.publish) ,while debugging i found it shows error as connection needs to be populated for the WorkbookItem Class but as the workbook gets published first time we don't have Id to populate the connection using server.workbooks.populate_connection(), also the connection parameter in workbookItem seems to be not set ? how to set it for new workbook .

There is already a similar issue posted on the forum but it seems that also has not taken care.. please consider for review

**Comment by MarounMaroun** [comment]
Any updates on this one?

**Comment by anant-matelabs** [comment]
Still no update?

**Comment by jacalata** [comment]
I'm not quite sure I follow this, but to publish a workbook that is failing the connection check, you can now use the "skip_connection_check" parameter in server.workbooks.publish.
