### ISSUE TITLE
how can use  credential saved in local site 

### ISSUE THREAD

**Issue by westcliffe** [tableau/server-client-python#649]
how can not write credential  use id and password on script?   

import tableauserverclient as TSC

tableau_auth = TSC.TableauAuth('Abc123', 'ppword', 'site123')

**Comment by illonage** [comment]
Hi @westcliffe,

You can use a [Personal Access Token to](https://help.tableau.com/current/server/en-us/security_personal_access_tokens.htm) sign in. It is not documented yet, but you can find a sample code here: https://github.com/tableau/server-client-python/blob/master/samples/login.py

**Comment by westcliffe** [comment]
@illonage thanks for your suggestions.   i tried different methods and decided to  use keyring to store credential info. It is easy way to do it.
