### ISSUE TITLE
How can we Query Workbook for a given filter

### ISSUE THREAD

**Issue by sid88in** [tableau/server-client-python#65]
Hello,

Is there a way to download all the views (as png or pdf) for a given workbook, filtered by a given dimension value?

For instance: If the workbook has a filter on dimension device type (values = smartphone, desktop and tablet), then query this workbook for a given dimension (say smartphone) and download the png. ?

Thanks
Sid

**Comment by RussTheAerialist** [comment]
I'm not 100% sure what you are trying to do here.  This API does not do anything related to displaying the viz, so you may want to take a look at the [JSAPI](https://community.tableau.com/community/developers/javascript-api) or How to pass in filter conditions on the url in the [tableau docs](http://kb.tableau.com/articles/knowledgebase/view-filters-url)

If you are looking to find all workbooks that meet a specific condition, we do support filtering the results of the workbook query.   Specific details on what can be used to filter the results is available in the [REST documentation](https://onlinehelp.tableau.com/current/api/rest_api/en-us/help.htm#REST/rest_api_concepts_filtering_and_sorting.htm%3FTocPath%3DConcepts%7C_____7) and to see an example of how to do that with this library, take a look at the [move workbook](https://github.com/tableau/server-client-python/blob/master/samples/move_workbook_projects.py#L35-L38) samples.

**Comment by RussTheAerialist** [comment]
Hi @sid88in,

The rest api does not currently support what you are trying to do.  The preview Image is pregenerated and stored as part of the twb file.

The best way you could go about this, with the current toolset, would be to use the JSAPI along with a headless browser to login, apply the filter (or automatically apply the filter using the view fields url), and then download the image from the headless browser.

This library and underlying rest api do not currently have the ability to render views.

-Russell

**Comment by t8y8** [comment]
@RussTheAerialist is correct.

The best bet right now is the JSAPI, or the more old school method of using a GET on the viz url itself.

`http://server.com/views/workbookname/view.png`

**Comment by sid88in** [comment]
Great! thanks a lot guys! I will play with JSAPI api's and update this thread. 👍

**Comment by sid88in** [comment]
@RussTheAerialist @t8y8 I was able to use JSAPI to control the webpage and apply filters async. But when I try to apply params on the workbook I get this error:

vqlcore.debug.js:5431 $BaseSessionCommandHandler: tabdoc:set-parameter-value: Error in parameters for command 'set-parameter-value'
bad value: field-caption

I am referring to https://community.tableau.com/message/242971 

Have you seen this error before? Any help?

thanks
Sid

**Comment by RussTheAerialist** [comment]
Hey Sid,

I really don't know enough about the JSAPI to help out here.  From the error, I'm guessing there might be a version mismatch between the version of the JSAPI you are using and the version of the server being used, but that's entirely a guess based on the error message where field-caption is missing.

The best thing to do would be to head over to https://community.tableau.com/community/developers/javascript-api/overview and post the question there.  Usually that's the place to go for JSAPI-specific questions.

**Comment by sid88in** [comment]
Hey Russ!

It works. I used changeParameterValueAsync to change the values !!
Thanks for the help :)

Sid

**Comment by t8y8** [comment]
👍
