### ISSUE TITLE
Server-side enhancement: Subscription - don't send if view is empty

### ISSUE THREAD

**Issue by jorwoods** [tableau/server-client-python#657]
Via the REST API, I would like to be able to create subscriptions, but not have them send if they are empty. This is an option if creating a subscription via the Server front end, but appears to not be present in the server side REST API. https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#create_subscription

**Comment by shinchris** [comment]
Added with #794, available in v0.15.0. Documentation update will be merged soon - #795.
