### ISSUE TITLE
Groups endpoint missing Create method

### ISSUE THREAD

**Issue by tableauembeddingteam** [tableau/server-client-python#66]
Doesn't appear to be any way to create a new Group.

**Comment by RussTheAerialist** [comment]
Looks like it's a feature we missed on the initial implementation.

**Comment by RussTheAerialist** [comment]
The full implementation which includes importing from AD will not be in the 0.2 release due to time.

**Comment by irwando** [comment]
Group creation was added some time ago, not sure why this is still open. Closing.
