### ISSUE TITLE
Login to Tableau Online server fails

### ISSUE THREAD

**Issue by abhikchakraborty92** [tableau/server-client-python#662]
Hi, I have been trying to log in to the tableau online server I created through https://online.tableau.com.
The server address I got from the URL was https://us-west-2b.online.tableau.com/

However, when I try to login using the API, I get 401001 error all the time. I tried the possible solution on #325 but it doesn't help at all. I checked the username and password and I can successfully login using the same from my browser

**Here a sample of my code:**

```
import tableauserverclient as TSC

tableau_auth = TSC.TableauAuth('myuser', 'mypassword')


server = TSC.Server('https://us-west-2b.online.tableau.com', use_server_version=True)

server.auth.sign_in(tableau_auth)
```

**Following is the error I get:**

```
Traceback (most recent call last):
  File "c:/Users/abchakraborty/Documents/Github/Tableau-Express-Plumber/testing_code.py", line 13, in <module>
    server.auth.sign_in(tableau_auth)
  File "C:\Python\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 127, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\lib\site-packages\tableauserverclient\server\endpoint\auth_endpoint.py", line 32, in sign_in
    self._check_status(server_response)
  File "C:\Python\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 70, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
tableauserverclient.server.endpoint.exceptions.ServerResponseError:

        401001: Signin Error
                Error signing in to Tableau Server
```

**If I change the server to https://online.tableau.com I get the following error:**
```

  File "C:\Python\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 70, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
tableauserverclient.server.endpoint.exceptions.ServerResponseError:

        405000: Method Not Allowed
                The HTTP method 'GET' is not supported for the given resource
```

Weird thing is the same code works for my corporate On-Prem server very well. 
Can someone help with a solution? Thanks!

**Comment by avijit3660** [comment]
I think you need to mention the site id for Tableau online as below.
tableau_auth = TSC.TableauAuth(username, password, site_id=’’)

Regards
Avijit

**Comment by shinchris** [comment]
As @avijit3660 mentioned, you need to pass in the site_id when signing in to any Tableau online site. The site_id can be found in the URL when you sign in through your browser. 

On-prem servers have a default site, where the site_id is an empty string value. For Tableau online, there is no default site, so the site_id value is required.

**Comment by abhikchakraborty92** [comment]
Thanks! I used site-name variable to solve it. We can mark this issue as closed.
