### ISSUE TITLE
Why do I need to populate a Group with Users to add a new user?

### ISSUE THREAD

**Issue by tableauembeddingteam** [tableau/server-client-python#67]
After about an hour of work, I am finally able to successfully add a new user and then add them to an existing group. However, I was perplexed by receiving an error about the Group not being populated:

My initial code:

with server.auth.sign_in(auth):
    user = TSC.UserItem('stone_cold', 'Publisher')
    new_user = server.users.add(user)
    gs, pi = server.groups.get()
    for g in gs:
        if g.name == 'Ballers':
            server.groups.add_user(g, new_user.id) 

Working code:
with server.auth.sign_in(auth):
    user = TSC.UserItem('stone_cold', 'Publisher')
    new_user = server.users.add(user)
    gs, pi = server.groups.get()
    for g in gs:
        if g.name == 'Ballers':
            server.groups.populate_users(g)
            server.groups.add_user(g, new_user.id)

Why do I need to use the populate_users() method on the Group just to add a user to it? As a second issue, why is populate_users() a Groups endpoint method and not a method of the GroupItem itself, where it could be called automatically prior to the attempt to add?

**Comment by RussTheAerialist** [comment]
I'll have to investigate why we need the populate_users call (not familiar with this code)
but I can answer the part about why we do not do it automatically prior to attempting to add.

This is a conscious design choice.  We do not want to make calls that you do not specifically ask for.  Yes it means there is a little bit of extra code, but we feel like it's better to be specific about why we are making calls to the api.

**Comment by RussTheAerialist** [comment]
Okay quickly looking over the code, this is a side-effect of trying to keep the user list accurate, so it made an assumption that the user list was already populated.  This is a bug.
