### ISSUE TITLE
How to create a New DataSource (with new connections) using TSC/API?

### ISSUE THREAD

**Issue by suryapsm** [tableau/server-client-python#671]
I didn't that find we can create data source in Tableau thru API.Is it possible thru TSC or Rest API?
I want to update a datasource which I migrated from Teradata to Snowflake. Can it be done thru TSC?

**Comment by shinchris** [comment]
You can publish datasource files (.tds, .tdsx, .hyper, and .tde files) using the [Rest API](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_datasources.htm#publish_data_source)/[TSC](https://tableau.github.io/server-client-python/docs/api-ref#data-sources), but you cannot create new datasources with new connections.
For updating, you can update some of the [datasource's metadata](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_datasources.htm#update_data_source) or the [datasource's connection](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_datasources.htm#update_data_source_connection) using the Rest API (both of which can be done through TSC).
