### ISSUE TITLE
deleting duplicate datasources using tableau sever client

### ISSUE THREAD

**Issue by Segexy** [tableau/server-client-python#678]
i am trying to delete some duplicate data sources available on the server using tableau server client. the script i have will only delete all data sources, but i do have specific data source names i want to delete from the server

**Comment by bcantoni** [comment]
I think you should be able to do this with the available [Datasources](https://tableau.github.io/server-client-python/docs/api-ref#data-sources) support:

First, call `datasources.get()` to get the full list of data sources. For each one this will include the name and the id.

Then, call `datasrouces.delete()` on the ones you want to delete. You'll need to reference these by the id number found above. (I.e. there is no "delete by name".)
