### ISSUE TITLE
Filter is not working correctly for server 2020.2.5

### ISSUE THREAD

**Issue by zeninpalm** [tableau/server-client-python#695]
Hi everyone, we're facing weird issues after upgrading to 2020.2.5.

If we execute a code like this with tableserverclient 0.13:

```python
import tableauserverclient as TSC
tableau_auth = TSC.TableauAuth('user', 'password', '')
server = TSC.Server('http://test-tableau/')
server.version = "3.9"
server.auth.sign_in(tableau_auth)
server_objects = server.workbooks
req_option = TSC.RequestOptions()
req_option.filter.add(TSC.Filter(TSC.RequestOptions.Field.Name, TSC.RequestOptions.Operator.In, ['Some & workspace name']))
list(TSC.Pager(server_objects, req_option))
```
We got an error like this:
```
tableauserverclient.server.endpoint.exceptions.ServerResponseError:

        400065: Bad Request
                The filter query is missing a value for key 'name'.
```

Obviously, Tableau server thinks the '&' in the workspace name is a special character in URL. But, it worked correctly in previous version.

Are these issues new bugs caused by new server versions? I appreciate any insights or advice, thank you!

**Comment by shinchris** [comment]
Hi @zeninpalm, ampersands are used as delimiters in the underlying API when parsing the URL, and cannot be used in filters.
Were you on version 2020.2.4 and TSC v0.13 before the upgrade when the ampersand was working in filters? I am unable to verify the regression on my side using previous versions.

**Comment by illonage** [comment]
Feel free to reopen the issue if you think that the issue is not solved
