### ISSUE TITLE
Support Running Tableau Server Published Flows

### ISSUE THREAD

**Issue by sollymay** [tableau/server-client-python#696]
It would be great that this functionality would come to TSC, as a lot of people do ETL outside of Tableau using Python but also have a lot of data in Tableau Server. I rely on flows to update the data on my datasources.

If I can trigger a flow to run using TSC after my ETL step is done (which is written in Python), then I can have the latest data faster compared to running schedules.

I understand that this is already possible with the API, however TSC is way much more user friendly, so it would be great if you can bring this to TSC

**Comment by shinchris** [comment]
Hi @sollymay, we have the [flow refresh function](https://github.com/tableau/server-client-python/blob/master/tableauserverclient/server/endpoint/flows_endpoint.py#L136) in TSC which triggers a flow to run. It maps to the REST API endpoint for [Run Flow Now](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_flow.htm#run_flow_now).

Is this the one that you are referring to?

**Comment by sollymay** [comment]
Oh awesome! Was this added recently? Maybe I don’t have the latest version of TSC and need to update it 😄

**Comment by bcantoni** [comment]
@sollymay I'll go ahead and close this one. I believe those Flow functions came with TSC 0.9.
