### ISSUE TITLE
Missing HasExtract Attribute in Datasource

### ISSUE THREAD

**Issue by rav-bzz** [tableau/server-client-python#698]
The "[Query Data Source](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_datasources.htm#query_data_source)" method has a "hasExtracts" attribute in the response body.

But this attribute is not available in the response body of datasources.get().

Can we please expose this attribute? Otherwise we will have to manually "tag" each data source to achieve the desired goal of "filtering to extract only data sources".

**Comment by rav-bzz** [comment]
When using "filtering" on "tags", it also runs into an error:
![image](https://user-images.githubusercontent.com/48706809/94339632-74fbaf80-004f-11eb-9779-adbf02ea151a.png)

**Comment by bcantoni** [comment]
This is part of a general problem that impacts several APIs: by default the REST API on the backend is not always returning all available fields (https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_fields.htm).

The solution will be to implement that in the TSC library so that all of the fields are accessible.

**Comment by bcantoni** [comment]
@rav-bzz regarding the problem you noted with filtering, you could try forcing your script to use the latest REST API version as supported by your server. You can set the `use_server_version` parameter as described on the [Versions page](https://tableau.github.io/server-client-python/docs/versions#use-the-rest-api-version-supported-by-the-server). This might fix your problem with filtering.

**Comment by shinchris** [comment]
@rav-bzz which version of Tableau Server are you using?
We recently made a change to the underlying API to return the 'hasExtracts' field by default for both Query Data Source and Query Data Sources, set to be released in the next version. We can backport the fix into the version you use.

**Comment by rav-bzz** [comment]
@shinchris we are using 2020.2. So will the 'hasExtracts' field be exposed in TSC for 2020.4?

**Comment by rav-bzz** [comment]
> @rav-bzz regarding the problem you noted with filtering, you could try forcing your script to use the latest REST API version as supported by your server. You can set the `use_server_version` parameter as described on the [Versions page](https://tableau.github.io/server-client-python/docs/versions#use-the-rest-api-version-supported-by-the-server). This might fix your problem with filtering.

This did the trick, thank you very much.

**Comment by shinchris** [comment]
Yes, it is planned to be released in 2020.4. Since you are using 2020.2, we can backport the change there to have it available for you with a 2020.2 maintenance release.
