### ISSUE TITLE
How can we query workbooks from a non-default project?

### ISSUE THREAD

**Issue by DelightedD0D** [tableau/server-client-python#71]
server.workbooks.get() will get me all 121 workbooks in our default project. How can we specify to return all of the workbooks from a non-default project? I see that we can filter the returned results with TSC.RequestOptions() but I dont see how that could be used to specify the project to pull from.

**Comment by RussTheAerialist** [comment]
The REST endpoint that server.workbooks.get() is using should return all workbooks for a given site.  It's not limited to the default project, but it will only return the workbooks you (or whatever user you authenticated as) has permission to view if you are not the administrator.  If this isn't the case, can you include a small snippet of your code where you are making the calls so I can reproduce it locally?

Currently tableau's REST api does not support filtering based on the project.

The current workaround would be to get all of the workbooks and then do the following to filter out the views not in the project you are interested in:

```python
# Build your list of all workbooks working through the pagination objects
workbooks = ...
workbooks_for_project = [wb for wb in workbooks where wb.project_id='[your project id]']
```

I've also added a request to our backlog to add the ability to get the workbooks for a project to our backlog.

**Comment by DelightedD0D** [comment]
I am signing in as the main server user with full permissions. I can see the workbooks on the actual Tableau server and can get the project with `project = next((project for project in all_projects if project.name == 'Call Center Reporting'), None)` but the workbooks it contains are not returned with 
`server.workbooks.get()`

**The default project**

![screenshot_23](https://cloud.githubusercontent.com/assets/8271955/19580558/9d385730-96ec-11e6-94dc-eb6412122578.png)

**The target project:**

![image](https://cloud.githubusercontent.com/assets/8271955/19580566/b51f642e-96ec-11e6-817a-7ac33e9dfb25.png)


**Here is my code**

`tableau_auth = TSC.TableauAuth(TABLEAU_CONFIG['user'], TABLEAU_CONFIG['password'])
server = TSC.Server('http://172.16.2.201/')

with server.auth.sign_in(tableau_auth): 
    
    all_projects, pagination_item = server.projects.get()
    project = next((project for project in all_projects if project.name == 'Call Center Reporting'), None)

    if project is not None:
        print project
        all_workbooks, pagination_item = server.workbooks.get()
        print("\nThere are {} workbooks on site: ".format(pagination_item.total_available))
        print([workbook.name for workbook in all_workbooks])`

**Which outputs:** 

```
C:\Python27\python.exe C:/python-playground/maestro/files.py
<tableauserverclient.models.project_item.ProjectItem object at 0x02DAEAD0>

There are 121 workbooks on site: 
['From Cache Queue Processor', ......  ]

Process finished with exit code 0
```

**Comment by RussTheAerialist** [comment]
Thanks for the quick response.

By default .get() only returns the first 100 things that it finds.  If you do `len(all_workbooks)`, you'll probably find that it only has 100, which is (I would guess), why you aren't finding the ones you are interested in.

The quick and easy way to fix this would be to create a `RequestOptions(page_size=200)` for the get request, that way you are getting all of the workbooks on your server.

I'll try to write up a sample that shows how to use the `pagination_item` part of the return value to loop over all of your workbooks.

**Comment by DelightedD0D** [comment]
@RussTheAerialist Indeed, that's exactly what it was!  Setting `page_size` to 200 as shown below gets the workbook in the results. Thank you very much for you help. If you have time, an example of using `pagination_item` to loop over the workbook results would be great. Thanks again.

```

req_option = TSC.RequestOptions().page_size(200)
all_workbooks, pagination_item = server.workbooks.get(req_option)
```

**Comment by RussTheAerialist** [comment]
In case you want to follow the in-progress PR for the pagination sample, it's in #72
