### ISSUE TITLE
Version releases according to semantic versioning

### ISSUE THREAD

**Issue by matthieucan** [tableau/server-client-python#710]
Hello,
The release version numbers of `tableauserverclient` follow `<major.minor>`. Would it be possible to use `<major.minor.patch>`, as advised by semantic versioning (https://semver.org/)?
Following your current releases, it should be easy to simply use 0 as the patch number, and keep the rest unchanged.
Thank you!

**Comment by bcantoni** [comment]
@matthieucan thanks for the suggestion. Is there a specific reason for changing? Or to put it another way, is the current versioning scheme causing a problem somehow?

**Comment by matthieucan** [comment]
@bcantoni Thanks for replying so fast. It doesn't cause any problem per se, more of an inconvenience: we use the compatible release operator `~=` (https://www.python.org/dev/peps/pep-0440/#compatible-release) to manage our dependencies; when they follow semantic versioning it gives us the insurance to get the most recent compatible release. We sadly can't do it with `tableauserverclient` and have to noqa it for the linter checking how dependencies are pinned.
Hope that helps!

**Comment by shinchris** [comment]
Thanks @matthieucan, we started doing this with v0.14.0 which was just released.

**Comment by matthieucan** [comment]
Great news! Thank you so much for taking this into account!
