### ISSUE TITLE
No projects or datasources for specific sites

### ISSUE THREAD

**Issue by raksingh** [tableau/server-client-python#712]
Hi,

I have a list of sites which I iterate through in order to get a list of projects and datasources.
Information is return for all but 2 of the sites in my list.
I checked the case of the site and tried variants.
Is there anything else I can try?

Thank you.

**Comment by shinchris** [comment]
Hi @raksingh, do you have more than 100 sites on your server? If that's the case, you will need to [paginate](https://tableau.github.io/server-client-python/docs/page-through-results) your response to get all the sites on your server.

**Comment by raksingh** [comment]
> Hi @raksingh, do you have more than 100 sites on your server? If that's the case, you will need to [paginate](https://tableau.github.io/server-client-python/docs/page-through-results) your response to get all the sites on your server.

Hi @shinchris. 
Thank you for the response. Sorry, I didn't mention it. I have 10 sites. I changed my code to connect to a single site instead of iterating a list, and I still don't get any result from the server for those 2 sites.
I can definitely see the projects if I login via the web front-end. 
Thanks again.

**Comment by bcantoni** [comment]
I'm going to close this due to age, but if you're still having this problem please reopen with comments about the current status.
