### ISSUE TITLE
Problem using server.schedules.add_to_schedule

### ISSUE THREAD

**Issue by wesmott** [tableau/server-client-python#726]
Hello,

I am trying to implement the refresh_schedule.py sample.  Everything works well until I get to server.schedules.add_to_schedule.

When I do a print I see the schedule_id and the item_id which is a datasource.  But I get an error saying it can't find the resource.  And oddly, it says it can't find the workbook.  However, I am trying to publish a datasource and it when through the get_datasource_by_name def.

Any help would be appreciated.  See attachement.

[refresh_schedule_issue.docx](https://github.com/tableau/server-client-python/files/5505323/refresh_schedule_issue.docx)

**Comment by bcantoni** [comment]
@wesmott it looks like this is one of the areas missing documentation; I wrote up #755 so we can fix that.

In the meantime you can check this sample which might help with the usage of `add_to_schedule`:
https://github.com/tableau/server-client-python/blob/development/samples/set_refresh_schedule.py
