### ISSUE TITLE
Datasource connection update

### ISSUE THREAD

**Issue by madhutableau81** [tableau/server-client-python#728]
Hi, 

I am using the python script using TSC to update datasource connection string.
can anyone help me with it?

<img width="764" alt="connection update" src="https://user-images.githubusercontent.com/74326993/98865846-01183980-243a-11eb-8bc3-9b2d2e1e5114.PNG">

Thanks 
Madhu K

**Comment by DaniilBalabanov33N** [comment]
It looks like you can't even sign in to the server. It has nothing to do with updating datasources.
 Check you're passing the correct URL to ```server = TSC.Server(server_url)```

**Comment by bcantoni** [comment]
@madhutableau81 are you still having this issue? If so could you provide a code snippet of what you're trying to do? (Omit any sensitive data fields.) As mentioned, it seemed like the basic step of logging in isn't working.

**Comment by bcantoni** [comment]
I'll close but please reopen with details requested if you're still having trouble.
