### ISSUE TITLE
Group Item; add ability to poulated domain_name

### ISSUE THREAD

**Issue by graham-marcus** [tableau/server-client-python#730]
In order to create active directory group the domain_name is not an input field available when creating the group item to add.
In group_item.py the option is not available  can  this be added as optional
def __init__(self, name=None):
        self._domain_name = None

**Comment by graham-marcus** [comment]
Take this through to use
newgroupitem = server.groups.create_AD_group(newgroupitem)
where the newgroupitem object has the group name, import, domain, minimum site role options available to populate

**Comment by bcantoni** [comment]
Thanks for reporting/suggesting this -- I'll tag as a feature enhancement.

**Comment by shinchris** [comment]
Fix (#770) released with v0.15.0.
