### ISSUE TITLE
Get / Set Project Owner

### ISSUE THREAD

**Issue by Eddie7mail** [tableau/server-client-python#746]
Hi all.
The TSC should be able to get and set the Project Owner. Any plans to have it implemented?

**Comment by bcantoni** [comment]
@Eddie7mail I saw your comment in the existing enhancement request for this (#269), so let's keep that as the issue to track this request. I'll also ping some people to find out what the latest status is there.

**Comment by Eddie7mail** [comment]
Great thanks!
