### ISSUE TITLE
Error connecting to Tableau server

### ISSUE THREAD

**Issue by iamabhishekchakraborty** [tableau/server-client-python#762]
Hello Team,
**Problem statement:** the implementation to connect and authenticate to Tableau server (2020.3) is failing starting today and this is the error message that I am receiving - 

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): tableauqa.companyname.com:443
Error on line 66 ConnectionError HTTPSConnectionPool(host='tableauqa.companyname.com', port=443): Max retries exceeded with url: /api/3.6/auth/signin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9306f6d080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

This is the first time that the code is failing with this issue, as it was working well. Code snippet - 

```
import tableauserverclient as tsc    ## tableauserverclient 0.14.1
tableau_auth = tsc.PersonalAccessTokenAuth(token_name=token_name, personal_access_token=token_value, site_id=sitename)

server = tsc.Server(url)  ## https://tableauqa.companyname.com
server.version = '3.6'

with server.auth.sign_in_with_personal_access_token(tableau_auth):   ##this is line 66
        print('Logged in successfully')
```

**Comment by iamabhishekchakraborty** [comment]
@bcantoni Thank you for pointing out some obvious reasons that could have triggered the issue. The QA server got upgraded recently which might have triggered something from network perspective (ip address changes - which we are still trying to figure out) and for this reason the ping to hostname is not working anymore though ping to ip-address works - this is the reason why the program is not working anymore.

**Comment by bcantoni** [comment]
@iamabhishekchakraborty ahh, thanks for the update. As a short-term workaround you may be able to use the IP address in your scripts, until hostname resolution is working again.

**Comment by iamabhishekchakraborty** [comment]
@bcantoni That's what we are currently doing, strangely though when we pass the server like https://xx.x.xx.xxx it fails with certificate error (Caused by SSLError(CertificateError("hostname 'xx.x.xx.xxx' doesn't match either of '*.companyname.com', 'companyname.com'",),)). All is good when we do just http://xx.x.xx.xxx
