### ISSUE TITLE
unable to add user to the group

### ISSUE THREAD

**Issue by yashwathreddy** [tableau/server-client-python#765]
```
with server.auth.sign_in(tableau_auth):
      server.groups.add_user(group_name, userid)
```

getting the following error:
```
packages\tableauserverclient\server\endpoint\groups_endpoint.py", line 110, in add_user
    if not group_item.id:
AttributeError: 'str' object has no attribute 'id'
```

**Comment by bcantoni** [comment]
From the error message there and your variable name it looks like the `group_name` you are passing in is actually a string, but it needs to be a group object retrieved from the server.

Take a look at the documentation which shows an example of fetching the groups first before calling `groups.add_user`:
https://tableau.github.io/server-client-python/docs/api-ref#groupsadd_user
