### ISSUE TITLE
Delete User/Group from permissions list on a project and other levels

### ISSUE THREAD

**Issue by ElenaSemMD** [tableau/server-client-python#769]
Hi Team!

I can't find
  a) a way of deleting a user or a group from the list of permissions;
  b) change project owner and remove a Project Leader.

If I miss that, please point it out. Example of deleting a Project Leader with a specific user name is much appreciated!
If there is no permission (rule/grantee) delete method, please include it into development roadmap.

Thanks a lot!

Elena

**Comment by shinchris** [comment]
Hi @ElenaSemMD, there is a [sample](https://github.com/tableau/server-client-python/blob/master/samples/add_default_permission.py) that does a similar permission deletion. It's specific to deleting workbook default permissions, but the syntax should be similar to what you are looking for. (Non-default permission deletion can also take a list of rules to delete, see #783)

As for the project owner, it is currently not possible via APIs. We have #269 tracking this for now.

**Comment by ElenaSemMD** [comment]
Hi Chris!

I tried modifying this sample.UnsuccessfulI :( I  have a multitenant TS
environment and each site has its own default project with default
permissions. I need to set up unified permissions for a project that is
common to all sites. 'All Users' should have 'None' rights set up on all
levels. Not denied, just none.

Thank you for your help!

Elena

**Comment by jacalata** [comment]
Hi @ElenaSemMD 
I know this is a long delayed response, but if you'd still like help with this, could you let us know where you're at and what happened when you modified the sample?
