### ISSUE TITLE
Subscription Method: Update

### ISSUE THREAD

**Issue by brycelarsen-shc** [tableau/server-client-python#775]
Please note this is an Enhancement Request rather than an Issue.

We currently have the ability to create/delete subscriptions. However, the REST API allows the option to update. Our use case is the desire to append a prefix to all of our subscriptions in order to encrypt the email.

Currently we might search for new subscriptions missing this, duplicate and add the prefix, and then delete the previous one, but it would be beneficial to simply update. Thank you!

**Comment by shinchris** [comment]
Enhancement checked in with #794. Available in v0.15.0.
