### ISSUE TITLE
Server side enhancement: Project owners in create/update

### ISSUE THREAD

**Issue by jorwoods** [tableau/server-client-python#781]
I have a need to be able to manage the owners of projects via the REST API. The owner ID is missing from the query/create/update endpoints on the Server side.

**Comment by shinchris** [comment]
Which Tableau Server version are you using? I believe owner ID is returned for all 3 of the endpoints. Though, I just noticed that it is not documented and also not in TSC yet.

**Comment by jorwoods** [comment]
Hey @shinchris, I am using 2020.3. It does look like it is returned in the response on GET and during create, but not during update.

Additionally, when I add owner as a sub element, similar to how it is returned when it is returned in a GET call, it does not seem to actually make that user the owner. Instead, it makes me the owner.

![image](https://user-images.githubusercontent.com/13803242/105557193-36aa9000-5cd1-11eb-8041-be6e39c8826c.png)

**Comment by shinchris** [comment]
Ah yes, you are correct that update call doesn't return the owner ID. Updating project owner is also currently not possible using the REST API. We have #269 tracking that for now.

I'm curious how the update made you the owner instead, though. Was it owned by you in the first place?

**Comment by jorwoods** [comment]
Ah. It was a new project that I created then tried updating via the REST API. The create was what I was referring to as making me the owner despite being provided the owner id.

Should I close this, or do you consider returning the owner ID on update a separate issue?

**Comment by shinchris** [comment]
Gotcha, that makes sense.
I'll go ahead and close - I would consider returning the owner ID on update as the same issue (i'll mention it also in the internal work item).
