### ISSUE TITLE
Unable to list the datasources pointing to Amazon Athena on TSC using Python3

### ISSUE THREAD

**Issue by quenchua** [tableau/server-client-python#788]
Hi,

Currently, all our Tableau datasources are pointing to a Presto instance hosted on Qubole. This is working as expected.
Now, we are planning to migrate away from Qubole to AWS. Hence, we would like all our Tableau DS to point to Amazon Athena.

We are able to connect Tableau to Athena(installed the Athena drivers), create a datasource, create views on top of this datasource and publish them to the server. Further, I am able to view this datasource and Views on the Server and even refresh it successfully from the Server.

I have a Python script that makes use of TableauServerClient to automate datasource/dashboard refreshes.

Problem is that, when I list all the datasources on the server (in order to get the datasource ID so that I can submit it for extract refresh), these datasources that are pointing to Athena do not turn up here at all. All the Datasources (new and old) that are pointing to Qubole Presto still turn up.

Here's the code I am using to list the datasources:

```
tableau_auth = TSC.TableauAuth(USERNAME, PASSWORD, SITENAME)
server = TSC.Server(SERVER_URL, use_server_version=True)

with server.auth.sign_in(tableau_auth):
    all_datasources, pagination_item = server.datasources.get()

for ds in all_datasources:
  print(ds.id)
```
I can confirm that it is not a pagination issue either since we have not exceeded the page size yet.

Hope this is clear enough, would really appreciate your help.

Thanks

**Comment by bcantoni** [comment]
@quenchua to help with the investigation here, could you add 1) your version of Tableau Server and 2) which version of the TSC library you are using?

Also, you mention "Python 3" which might imply something worked in Python 2.x, but I don't think that's the case here is it? (We only support Python 3.5+ anyways at this point.)

**Comment by quenchua** [comment]
Hello @bcantoni, sorry about the late reply.
1) Tableau Server Version: 2020.2.3
2)  Version of the TSC library: 3.8
Yeah, I'm on Python 3.7.

Also, I found that the workbooks pointing to Amazon Athena are still visible via TSC. So as a workaround, I will be refreshing the workbook instead of the datasource.
Also, I checked using Tableau's REST APIs as well, same result.

**Comment by quenchua** [comment]
@bcantoni This was an error from my end.
I was not published the datasource from Tableau Desktop to the Server, I was publishing only the workbook.
When I published the datasource as well, the IDs started appearing via TSC and I am able to refresh them.

Thanks!
