### ISSUE TITLE
Update Group

### ISSUE THREAD

**Issue by mbabatunde** [tableau/server-client-python#805]
Hi,

I was looking through the API documentation and noticed there's no way to update group's name. Is there anyway to go about updating a group's name through `RequestOptions` or something else?

**Comment by shinchris** [comment]
Hi @mbabatunde, this was recently added with v0.15.0, where you can update local group names (can't change name for active directory groups). We are working on getting the documentation update published, but you can see pull request #797 for the time being.

**Comment by mbabatunde** [comment]
Hi @shinchris, thanks so much for the response and that did the trick! Appreciate it!

If the team needs help with documenting, I'd be more than happy to help out in anyway that I can

**Comment by shinchris** [comment]
Thanks @mbabatunde, we would very much appreciate any contributions! 🙂 

There are a handful of issues labelled with `docs`, which are all documentation work that we haven't gotten around to yet. Documentation updates for those issues or other discrepancies/missing items you find would help out a ton.

**Comment by bcantoni** [comment]
I'll go ahead and close this now that the referenced PR with Groups docs has been merged.
