### ISSUE TITLE
Allow to select to include image or pdf or both in subscriptions

### ISSUE THREAD

**Issue by siyingwang-shc** [tableau/server-client-python#807]
This is an enhancement request. When creating a new subscription, can we specify if we want to include image only, or include pdf, or include both image and pdf in the email? Current method only includes image in the email. Thanks!

**Comment by shinchris** [comment]
Hi @siyingwang-shc, this was just added with v0.15.0. We are working on getting documentation updates published, but you can check out #795 for the time being for the proposed documentation changes.

**Comment by siyingwang-shc** [comment]
@shinchris thank you! I updated the library, and it worked!
