### ISSUE TITLE
Update group license_mode

### ISSUE THREAD

**Issue by idanml** [tableau/server-client-python#809]
Hi,

updating from 'onSync ' to 'onLogin' works but from 'onLogin' to 'onSync' didn't work (no error, everything looks fine but no change on the field)

**Comment by bcantoni** [comment]
@idanml could you please include:
* Tableau Server version
* TSC library version (I assume you're on the latest 0.15)
* Are you also changing the minimum site role along with this, or just the license mode?

**Comment by bcantoni** [comment]
Also could you clarify, what is your expected use case for changing the license_mode? Do you expect to me moving it back and forth with updates, or you were just testing whether it worked?

I suspect whatever we find here will most likely be the same behavior as from the backend REST API.

**Comment by bcantoni** [comment]
I'm going to close this one - please reopen with answers to the questions above if this is still an active problem.
