### ISSUE TITLE
Python API and selecting marks

### ISSUE THREAD

**Issue by sajozsattila** [tableau/server-client-python#812]
Hello,

Is this possible in the Python API to selecting marks the same way as in the javascript? See: https://help.tableau.com/current/api/js_api/en-us/JavaScriptAPI/js_api_concepts_selecting_marks.htm

I had a look in the documentation but I  haven't seen it.

Kind regards,

**Comment by jacalata** [comment]
No, this Python client covers totally separate functionality to that client, sorry.
