### ISSUE TITLE
Getting a User By Email

### ISSUE THREAD

**Issue by mbabatunde** [tableau/server-client-python#819]
Hi,

I've been looking through the documentation and checking examples in the sample. 

I'm trying to figure out how to **get a user by their email**. 
I'm doing something like this once I'm authenticated:
```python
server.use_server_version()
options = TSC.RequestOptions()
options.filter.add(TSC.Filter(TSC.RequestOptions.Field.OwnerEmail, 
                              TSC.RequestOptions.Operator.Equals, 
                              "hi@example.com")
server.users.get(req_options=options)
```

This is returning a `400065: Bad Request where the key is not recognized for this api version`. I've tried with `RequestOptions.Field.Name`, but that returns a set with an empty list and pagination object.

`([], <tableauserverclient.models.pagination_item.PaginationItem object>)`

Is there anyway to get a user through their email?

**Comment by bcantoni** [comment]
@mbabatunde could you include here your Tableau Server version and also the version of the TSC library you're using?

**Comment by bcantoni** [comment]
I'll closed based on the comment that this is working now.
