### ISSUE TITLE
Cannot create multiple users at once

### ISSUE THREAD

**Issue by mbabatunde** [tableau/server-client-python#820]
**Describe the bug**
I'm trying to add users to a site by parsing their information from a CSV. 
When I go to create a user using `TSC.UserItem('user', 'Viewer')`, I get this error:
```
400003: Bad Request 
Payload is either malformed or incomplete
```

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online) - **3.9**
 - Python version - **3.8**
 - TSC library version - **0.15**

**To Reproduce**
Steps to reproduce the behavior. Please include a code snippet where possible.
Creating multiple users from a CSV as input

**Results**
What are the results or error messages received?
```
400003: Bad Request 
Payload is either malformed or incomplete
```
**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by bcantoni** [comment]
@mbabatunde thanks for the report. Under Tableau Server version you've listed the REST API version as 3.9. What is the actual version of the Tableau software itself (e.g. 2020.3 or similar)?

**Comment by dixit06** [comment]
@bcantoni - Hello,  I see this issue is closed. Do you know the fix for this.
I'm getting exact same issue while adding users from csv file.

TSC - 0.15
Tableau Server Version: 2021.2.1 (20212.21.0712.0907) 64-bit Linux

**Comment by bcantoni** [comment]
@dixit06 in this case we closed it due to lack of response from the original report.

I would suggest trying the steps listed here in the troubleshooting guide:
https://tableau.github.io/server-client-python/docs/troubleshooting#400000-bad-request

If you're still having the problem, please open a new issue with all the details.
