### ISSUE TITLE
Feature to download view-data via TSC, with same result as manual "Crosstab" download

### ISSUE THREAD

**Issue by RasmusFH** [tableau/server-client-python#822]
I would like to get the same result/output from TSC as when I manually download the view-data from a Tableau view as "Crosstab". Currently, when I download view-data with TSC, it seems like I get a similar result to when selecting the download "Data" function in the workbook, which is limited or summary data.

Hence, the central question is, how do I perform the "Crosstab" download with TSC? And optimally, directly download into a Pandas data frame. 
I have already tried the "populate CSV" function in the TSC library, which gives the same result as a normal view-data download.

As a side note, I can mention that the workbook is connected to a live data source, if that makes a difference.

Thanks a lot in advance for all support!

I have also posted on [Tableau community](https://community.tableau.com/s/question/0D74T000001cvQT/detail?s1oid=00D4T000000Dj8G&s1nid=0DB4T000000GnPK&emkind=chatterCommentNotification&emvtk=qqxd67r4XMQ44uHo0QHOTPrYEE47lrxwCrZW9_8qKFw%3D&s1uid=0054T000001xH2J&emtm=1616098776790&fromEmail=1&s1ext=0) where I was encouraged to create a new issue here on GitHub.

**Comment by thesketh** [comment]
I don't know if there's a way to get the crosstab download using the API, but you could pivot the table in pandas itself. 

Does something like this work? I'm assuming you've already got the right `ViewItem` from the workbook first.

```python
# Assume `server` is the authenticated Tableau server, `view` is a ViewItem.

import tempfile
import pandas as pd

server.views.populate_csv(view)

# Use a temporary file to save memory. Could use io.BytesIO for small downloads.
with tempfile.TemporaryFile() as file:
    for chunk in view.csv:
        file.write(chunk)
    file.seek(0)
    df = pd.read_csv(file)

# Create a list of the dataframe's columns.
columns = list(df.columns)
# Remove the columns we intend to pivot on.
columns.remove("Measure Values")
columns.remove("Measure Names")

# Pivot and reset to a numerical index.
df = df.pivot(columns, "Measure Names", "Measure Values")
df.reset_index(inplace=True)
```

**Comment by RasmusFH** [comment]
> I don't know if there's a way to get the crosstab download using the API, but you could pivot the table in pandas itself.
> 
> Does something like this work? I'm assuming you've already got the right `ViewItem` from the workbook first.
> 
> ```python
> # Assume `server` is the authenticated Tableau server, `view` is a ViewItem.
> 
> import tempfile
> import pandas as pd
> 
> server.views.populate_csv(view)
> 
> # Use a temporary file to save memory. Could use io.BytesIO for small downloads.
> with tempfile.TemporaryFile() as file:
>     for chunk in view.csv:
>         file.write(chunk)
>     file.seek(0)
>     df = pd.read_csv(file)
> 
> # Create a list of the dataframe's columns.
> columns = list(df.columns)
> # Remove the columns we intend to pivot on.
> columns.remove("Measure Values")
> columns.remove("Measure Names")
> 
> # Pivot and reset to a numerical index.
> df = df.pivot(columns, "Measure Names", "Measure Values")
> df.reset_index(inplace=True)
> ```

Hi Travis,

I found the reason why I am getting the wrong data:
I have more than one worksheet within my dashboard. Resultingly when querying data with the API, by default data from the first sheet (alphabetically by worksheet name) is downloaded. This I was not aware about.

Anyway thanks for your support.

Best regards Rasmus
