### ISSUE TITLE
Publish Data Source - Connection reset by peer error.

### ISSUE THREAD

**Issue by sporaans** [tableau/server-client-python#823]
I'm using TSC to publish multiple Hyper files as data sources to Tableau server and I keep running into `Connection reset by peer 104` error. 

This error is inconsistent - it could be different data source each day and same data source one day could be failing and other day not. 

Attached full error from log file.  [hyper_upload_err.log](https://github.com/tableau/server-client-python/files/6182820/hyper_upload_err.log)

Using: 
 - Tableau Server 2019.4
 - Python 3.6.8
 - TSC 0.9

Data sources are published using code:
```
ds = TSC.DatasourceItem(project_id, name=datasource_name)
result = server.datasources.publish(ds, filename, upload_type, as_job=True)
```
Error message:
`ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by jacalata** [comment]
This error is a network issue caused by either bad traffic from the client or issues on the server. It's not being caused by the datasource itself, and I don't think the tsc code would be the issue either.
