### ISSUE TITLE
TSC.Pager(server.workbooks) unable to print all workbooks from tableau server

### ISSUE THREAD

**Issue by Bipin007** [tableau/server-client-python#827]
**Versions**
 - Tableau Server version (or note if using Tableau Online) - tableau server 2020.2.7
 - Python version - 3.7 
 - TSC library version 

**To Reproduce**

**Results**
Below code is not printing all the workbooks on my tableau server 2020.2.7, one of the example is below - We have workbooks named like 2018-****-**** but it doesn't prints them. I even tried with TSC.RequestOptions(pagesize=1000). How can i iterate through all the workbook names (there are more than 3000+ workbooks) 

        for wb in TSC.Pager(server.workbooks):
            if wb.name.startswith('2018'):
                print("I am here:",wb.name)

**Comment by bcantoni** [comment]
@Bipin007 could you clarify - when you say that not all workbooks are being printed, do you mean specifically that not all workbooks whose name starts with 2018 are printed? I'm trying to determine whether the code is having a problem seeing all workbooks or if there is something special about `.startswith`.

As an alternative you could try this simple loop which _should_ print out all workbooks that this specific user can see:

    for wb in TSC.Pager(server.workbooks):
        print(wb.name, wb.id)

As another confirmation check: if you login to your Tableau Server web UI using the same user, are you able to see all the expected workbooks?

**Comment by Bipin007** [comment]
I had already checked and it didn't worked expectedly as a workaround i iterate this function at site level. 

Thanks,

**Comment by barscm** [comment]
If you mean that you had to iterate over the different sites that the user had access to, then this is working as expected. From the documentation, you specify the site you're logging in to when you authenticate:

https://tableau.github.io/server-client-python/docs/sign-in-out

Note: SITENAME

```
import tableauserverclient as TSC

tableau_auth = TSC.PersonalAccessTokenAuth('TOKEN_NAME', 'TOKEN_VALUE', 'SITENAME')
server = TSC.Server('https://SERVER_URL', use_server_version=True)
server.auth.sign_in(tableau_auth)

# Do awesome things here!

server.auth.sign_out()
```
