### ISSUE TITLE
What happened to Server.tasks

### ISSUE THREAD

**Issue by craigk-from-vanguard** [tableau/server-client-python#828]
`tasks` used to be availble for a Server object. Calling methods from `Server.tasks` such as `Server.tasks.run` still works. I can't find this on the API documentation. Does anyone know if `tasks` has been deprecated or replaced?

Edit: I found the Tasks class in the source. Where is the documentation for the Tasks class?

**Comment by bcantoni** [comment]
@craigk-from-vanguard thanks for raising this - it looks like we do have a pending PR #525 to add documentation around Tasks. I'll work on getting that finished out.

**Comment by bcantoni** [comment]
@craigk-from-vanguard I've finished up that PR with the docs, so the Tasks docs are now live:
https://tableau.github.io/server-client-python/docs/api-ref#tasks

**Comment by craigk-from-vanguard** [comment]
@bcantoni Thank you so much!
