### ISSUE TITLE
How to manipulate the data after connect Tableau server?

### ISSUE THREAD

**Issue by zhengyinande** [tableau/server-client-python#834]
I have connect the tableau server, and check the data already. But how to manipulate the data from some certain datasource(like any hyper or tde) by sql?
I mean that is there any way like others, like when someone connect oracle by python or SAS, then he could write some sql queries to extract explicit data from database?
Thank you very much.

**Comment by jacalata** [comment]
This isn't currently possible - you would need to connect directly to the datasource to manipulate it that way.
