### ISSUE TITLE
Issue with dates format in request options

### ISSUE THREAD

**Issue by ItachiEren** [tableau/server-client-python#845]
Hello, 
Sorry if I am in the wrong place I am new here.
I have an issue when I use the csv_req_option with dates. The date filter isn't applied when I pass it in argument whereas it works for all kinds of string.

Imagine the next dashboard : 
Col A = Date 
Col B = Event 

if I use 
csv_req_option = TSC.CSVRequestOptions()
csv_req_option.vf('any Event')
so far everything works

now 
csv_req_option = TSC.CSVRequestOptions()
csv_req_option.vf('01/01/2021')
it doesn't work the filter isn't applied

I have tried different date formats but it didn't work...

Thanks for your help.

Best

**Comment by kykrueger** [comment]
Hello,

I just had the same issue myself. Passing in a datetime object worked to set the correct filter. 
You probably need to specify the key for the name of your date filter though.

For example:
```
csv_req_option = TSC.CSVRequestOptions()
date = datetime.datetime.now()
csv_req_option.vf('datefilter-name', date)
``` 

I hope that helps!

**Comment by bcantoni** [comment]
kykrueger's suggestion looks correct here. I'm going to close but if you're still having trouble, please reopen with updated notes.
