### ISSUE TITLE
Filter Operator.In - Cannot find groups/projects with spaces in their name

### ISSUE THREAD

**Issue by jesusenlanet** [tableau/server-client-python#846]
**Description**
Calling `groups.get` endpoint I'm unable to filter using the `Operator.In` operator.

**Versions**
 - Tableau Server version: 2021.1.0 (20211.21.0430.0040) 64-bit Linux
 - Python version: Python 3.7.7
 - TSC library version: tableauserverclient==0.15.0

**To Reproduce**
```python
req_options = RequestOptions()
req_options.filter.add(Filter(RequestOptions.Field.Name, RequestOptions.Operator.In, ["Group A", "Group B"]))
groups, pagination = server.groups.get(req_options=req_options)
for group in groups:
    logger.info(group)
```

**Results**
```bash
<tableauserverclient.models.group_item.GroupItem object at 0x42>
```

**Expected Results**
```bash
<tableauserverclient.models.group_item.GroupItem object at 0x42>
<tableauserverclient.models.group_item.GroupItem object at 0x43>
```

**Comment by ovinis** [comment]
Thank you! We are tracking this internally. Will get back to you as soon as we have an update. 

ID: 1278983

**Comment by jorwoods** [comment]
@jesusenlanet In your example, you use `RequestOptions.Operator.Equals` did you mean to use `RequestOptions.Operator.In`? Using In with groups works as expected for me.

**Comment by jesusenlanet** [comment]
Hey @jorwoods 

Oh, sorry for the `Equals`, I mean `In`, I think I make some error writing the comment, here the script I'm using:

``` python
req_options = TSC.RequestOptions()
req_options.filter.add(TSC.Filter(TSC.RequestOptions.Field.Name, TSC.RequestOptions.Operator.In, ["Group A", "Group B"]))
groups, pagination_item = server.groups.get(req_options)
for group in groups:
    print(group.__dict__)
```

What I'm obtaining is confusing, it looks that if a group is using a `View` template on the privileges, it doesn't appear on the list.
![Captura de pantalla 2021-09-01 a las 11 10 27](https://user-images.githubusercontent.com/10682451/131644845-c295b4c6-a020-484a-8942-b0e7c3999468.png)

Groups like that are not appearing on the results.

**Comment by jorwoods** [comment]
Do these groups also appear in the groups section of the site? Are you a site/server admin?

**Comment by jesusenlanet** [comment]
> Do these groups also appear in the groups section of the site? Are you a site/server admin?

Yes, I am an admin and those groups appear on the project permission list.

I tried to retrieve groups for another projects and I'm unable to obtain some of the groups using the `Publish` template. I can't identify a pattern at this moment.

**Comment by jorwoods** [comment]
Not within the permissions list, but within the actual "Groups" section of the overall site.

**Comment by jesusenlanet** [comment]
> Not within the permissions list, but within the actual "Groups" section of the overall site.

Yes, they appear in the main groups list, some of them appear on the response, some other no.
Also all of them have the same `local` domain.

**Comment by jacalata** [comment]
In theory this was fixed a long while ago, but it's not working now. Same problem with searching In for projects. I suspect fixes we made for other encoding issues broke this one again.

**Comment by bryceglarsen** [comment]
I think the same issue affects workbooks. Working on a sample with Superstore and World Indicators and not returning anything with In. 😢

**Comment by bab014** [comment]
I have the exact same issue when querying for data sources. I have one that has a space in the name and it just removes the space and does **not** url encode it at all. So I don't get a match.

**Comment by LarsBreddemann** [comment]
I face the same issue: when searching for projects, spaces in the search term are removed by this line 14
in `tableauserverclient/server/filter.py`

```
   def __str__(self):
        value_string = str(self._value)
        if isinstance(self._value, list):
            value_string = value_string.replace(" ", "").replace("'", "")         <---
        return "{0}:{1}:{2}".format(self.field, self.operator, value_string)
```

This really should be parsed into URL encoding instead of just removing spaces and single quotes
`urllib.parse.quote (value_string)` should do the trick here. 
Or, simpler, `value_string.replace (" ", "%20").replace("'", "")`

The [last change](https://github.com/tableau/server-client-python/commit/39560e55cab644fe8867db9cc0fc2bc03f884322#diff-6113a411dfdf38380b37cce3983a96c81cc5fd3558a82e0daa363a6f9ce4d1a0) to this line did not change this behavior.

I do not see how enabling search terms with spaces requires a server side enhancement. When searching from the UI both Tableau Server and Cloud encode the space in the search term with `%20` and return the correct result.

**Comment by LarsBreddemann** [comment]
I've committed PR #1259 to fix this issue.
