### ISSUE TITLE
Disabling Extract through Tableau Python API

### ISSUE THREAD

**Issue by wesmott** [tableau/server-client-python#848]
Hello,

Has anybody had any luck disabling an extract through the Tableau Python API?  Any tip would be appreciated.  Thanks.

**Comment by jacalata** [comment]
I'm not quite sure what you mean, there's a couple of options that aren't properly documented.
- if you want to stop the refresh from running regularly in the future, you can use the [tasks](https://github.com/tableau/server-client-python/blob/fefd6f18d8a6617829c6323879d2c3ed77a4cda6/tableauserverclient/server/endpoint/tasks_endpoint.py#L70) endpoint to delete the task
- if you just want to cancel the currently running extract refresh, you can use the [jobs](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_jobs_tasks_and_schedules.htm) endpoints: these aren't properly documented here, but you would use the [cancel ](https://github.com/tableau/server-client-python/blob/fefd6f18d8a6617829c6323879d2c3ed77a4cda6/tableauserverclient/server/endpoint/jobs_endpoint.py#L39)operation

If that didn't answer your question and you are still interested, let me know.
