### ISSUE TITLE
Implement Pager per #72 feedback

### ISSUE THREAD

**Issue by RussTheAerialist** [tableau/server-client-python#85]
The pager should be part of the library.  Refer to #72 for detailed feedback on what needs to be changed to support this.

**Comment by t8y8** [comment]
This is closed by #90 

@RussTheAerialist will this make 0.3 or should I move the milestone (Not sure how far up you plan on merging)

**Comment by RussTheAerialist** [comment]
I'm planning to take it into 0.3.  If I have time today, I'm releasing 0.3, but we'll see if I have time before the day runs away from me since I'm prepping for my talk.

**Comment by t8y8** [comment]
SHIPPEDDDD.

Closed by #90
