### ISSUE TITLE
JavaScript Library Version?

### ISSUE THREAD

**Issue by mbabatunde** [tableau/server-client-python#854]
**Describe the bug**

Hi,

I was wondering if there was a native JavaScript/TypeScript library equivalent to this one? I noticed there's one for visualization, but not for managing Tableau?

Is that available/will that be worked on anytime soon?

Thanks!

**Comment by bcantoni** [comment]
Hi @mbabatunde no, this is the only official client library for the REST API. There at times have been discussions around creating client libraries for other languages such as Java and JavaScript, but nothing concrete yet.
