### ISSUE TITLE
Does TSC support downloading all underlaying data in csv format?

### ISSUE THREAD

**Issue by ssz2016** [tableau/server-client-python#858]
**Describe the bug**
when use CSVRequestOptions class to populate csv data from view, it only provides the summary data, can it support download all underlaying data?

**Comment by jacalata** [comment]
This is correct - tsc is built on top of the REST API, which specifies that getting View data as CSV will only return summary data. https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#query_view_data
