### ISSUE TITLE
tableauserverclient Download Workbook from a Project

### ISSUE THREAD

**Issue by pavankumartableau** [tableau/server-client-python#869]
Hi All,

by default server.workbooks.download() downloads by sorting them in ASC or DESC.
But, I have multiple workbooks with same name in different projects.
So, I have a requirement where i have to download Workbook from particular project.
Find the below code i am working.
i don't know where i am going wrong.
"Migration" is the name of Workbook i need to download.

with server.auth.sign_in(auth):
    all_projects, pagination_items = server.projects.get()
    all_workbooks, pagination_items = server.workbooks.get()
    src_prj_id = [proj for proj in all_projects if proj.name == 'Source']
    src_wb_id = [wb for wb in all_workbooks if wb.name == 'Migration' ]
    workbooktodownload = tableauserverclient.WorkbookItem(name=src_wb_id,project_id = src_prj_id[0].id)
    #print(workbooktodownload.name)
    workbook_path = server.workbooks.download(workbooktodownload[0].id)

**Comment by ovinis** [comment]
Hello! Thanks for logging the issue. Could you try the code below:

```
with server.auth.sign_in(tableau_auth):
        # queries the server and returns info about the workbooks in the site
        all_workbooks, pagination_items = server.workbooks.get()
        for wb in all_workbooks:
            if wb.project_name == "Source" and wb.name == 'Migration':
                server.workbooks.download(wb.id)
                print("Successfully downloaded workbook with workbook id: " + wb.id)
```

**Comment by pavankumartableau** [comment]
@ovinis Thanks for the help, it is working

**Comment by Surya04021987** [comment]
Is there any way to download workbooks and Dashboards which are older than 90 days?

**Comment by jacalata** [comment]
There is no 90 day limit on downloading. This may be a setting or rule that your server administrators have created, you should talk to them.

**Comment by Surya04021987** [comment]
Hi Jacalata,
I really appreciate your response. 
I am Tableau Server Admin.
My requirement is related unused content, I don't want to download all dashboards, I want to download all workbooks which not used more than 90 days, after download wants delete workbooks from the Tableau Server by using script.
Please let me know if you have idea on this.
