### ISSUE TITLE
Problem querying the data for the view csv

### ISSUE THREAD

**Issue by adityamujumdar** [tableau/server-client-python#870]
I am trying to populate a csv from a view online and download that using python. This is my code:

```
import tableauserverclient as tsc
from getpass import getpass

username = '<username>'
password = getpass('Type in password: ')
tableau_auth = tsc.TableauAuth(username, password)
server = tsc.Server('https://tableau.<server_name>.com/')
server.use_server_version()

with server.auth.sign_in(tableau_auth):
    for resource in tsc.Pager(server.views):
      print(resource.name, resource.id)
      # get resource id to populate csv table
      views = filter(lambda x: x.id == resource.id, tsc.Pager(server.views.get))
      views = list(views)
      view = views.pop()
      # pprint(vars(view))
      options = None
      filename = resource.name+'.csv'
      print(filename)
      server.views.populate_csv(view, options)
      with open(filename, 'wb') as f:
        f.writelines(getattr(view, 'csv'))
```

I can download csv's for other views in my server. I have permissions to download data from the views as well. But a specific view is giving me this error:
```
ServerResponseError: 

	400081: Bad Request
		There was a problem querying the data for view '<view_resource_id>'.
```

How do I fix this? I have not found a solution for this anywhere online.

**Comment by jacalata** [comment]
In case this is still a problem: as I'm sure you've guessed, this is a catch-all error. I would troubleshoot it by trying to simply fetch the view through the Get View call to check if you can reach it that way, and try exporting the data from the view through the UI to confirm that operation works. If they both work, try logging the full URL of the requests sent by populate_csv, although I can't see why that would be wrong just for one view.

Sorry for the late reply - I hope you figured this out already, but let us know if it is still an issue!

**Comment by jacalata** [comment]
Feel free to re-open if you have follow-up questions.
