### ISSUE TITLE
How to access a workbook on tableau public?

### ISSUE THREAD

**Issue by iamleeg** [tableau/server-client-python#874]
**Describe the bug**
There is a [public workbook](https://public.tableau.com/app/profile/mspbs/viz/COVID19PY-Registros/Descargardatos) I need to access programmatically, so I'm trying the server client API. Despite the data being publicly shared on tableau public, it seems impossible to access via the API. Currently, I'm trying to replicate the [write your first program](https://tableau.github.io/server-client-python/docs/#write-your-first-program) example from the API documentation, but using the public server.

If I don't authenticate at all, then I get this:

    tableauserverclient.server.exceptions.NotSignedInError: Missing site ID. You must sign in first.

If I authenticate using an account I created on tableau public, then I get a 403 error when I try `server.datasources.get()`.

**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online): I'm using tableau public
 - Python version: 3.9.6 (on macOS)
 - TSC library version: 0.16.0

**To Reproduce**
Using an account on tableau public, and the server `public.tableau.com`, [run the getting started sample](https://tableau.github.io/server-client-python/docs/#write-your-first-program).

**Results**
As described above. If I do use my account credentials for public.tableau.com, then I get the following 403 error:

```
Traceback (most recent call last):
  File "/private/tmp/env/lib/python3.9/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 86, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
  File "/private/tmp/env/lib/python3.9/site-packages/tableauserverclient/server/endpoint/exceptions.py", line 17, in from_response
    parsed_response = ET.fromstring(resp)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 6, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/env/lib/python3.9/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 163, in wrapper
    return func(self, *args, **kwargs)
  File "/private/tmp/env/lib/python3.9/site-packages/tableauserverclient/server/endpoint/auth_endpoint.py", line 31, in sign_in
    self._check_status(server_response)
  File "/private/tmp/env/lib/python3.9/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 92, in _check_status
    raise NonXMLResponseError(server_response.content)
tableauserverclient.server.endpoint.exceptions.NonXMLResponseError: b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
```

**Comment by bcantoni** [comment]
I believe that is expected because the Tableau Server REST API (which TSC uses) is not enabled for Tableau Public. I'll get some confirmation on that.

**Comment by iamleeg** [comment]
sad face, but thank you.

**Comment by bcantoni** [comment]
Okay I've confirmed internally that Tableau Public does not have the Tableau Server REST API enabled. Public has a completely different user authentication system (and the published content is all publicly visible), so the constructs of the server REST API don't apply.
