### ISSUE TITLE
'Views' object has no attribute 'get_by_id'.

### ISSUE THREAD

**Issue by mauropasi** [tableau/server-client-python#877]
**Describe the bug**
SERVER.views.get_by_id('some_id')
returns 'Views' object has no attribute 'get_by_id'.

It works with other endpoints, like workbooks for example.

On a separate note. It is missing an 's' in the example code in the docs:
https://tableau.github.io/server-client-python/docs/api-ref#views
view = server.view.get_by_id

**Versions**
Details of your environment, including:
 - Tableau Server version: 2020.4
 - Python version: 3.7
 - TSC library version: 3.10
 - Package: tableauserverclient 0.15.0

**To Reproduce**
SERVER.views.get_by_id('some_id')

**Results**
'Views' object has no attribute 'get_by_id'.

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by bcantoni** [comment]
Thanks @mauropasi for the confirmation. Looking back at the history, it seems we added that via #750 which first appeared in release 0.15.
