### ISSUE TITLE
Consider moving docs from gh-pages branch back to ./docs folder

### ISSUE THREAD

**Issue by bcantoni** [tableau/server-client-python#902]
Investigate whether we should move the docs tree from the `gh-pages` branch back to the main branches under `./docs`.

Benefits to doing this:
* Simplify changes by including both code and doc changes in the same PR (rather than two separate ones).
* Simplify releases because when the code changes are merged from `development` to `main`, the doc changes will come along as well. In the past we had some doc PRs which specifically we had to hold merging until the release had happened.

I'm not aware of any reasons to not do this (i.e. no downside). @vogelsgesang volunteered to help with this if we decide to do it.

@jacalata @t8y8 @dzucker-tab can you weigh in here with any notes from the past? I see some older changes where we moved from `./docs` to `gh-pages` and I'm not sure the reasoning. Perhaps at the time, GitHub Pages required the separate branch.

**Comment by t8y8** [comment]
I think it allowed us to rev docs independently of releases or something like that? I don't remember the exact reason why we did it. Maybe there were merge conflicts?

I don't have a strong opinion -- either format works for me as long as the docs build pipeline is happy.

**Comment by bcantoni** [comment]
Ahh that's a great point. I was focusing just on the Code+Docs combo pull requests.

If we do make this change, the steps for a Docs-only change would be slightly more work:
1. PR + review based on `development` branch
2. Merge (probably cherry-pick) from `development` to `main` to make the changes live

Looking at recent history on `gh-pages` (https://github.com/tableau/server-client-python/commits/gh-pages) it's definitely a mix of Docs-only and Docs to match code changes. The former are usually pretty lightweight so doing the cherry-pick wouldn't be too hard.

**Comment by jacalata** [comment]
will keep the newer item open to track this.
