### ISSUE TITLE
switch datasource connection from username / password to Snowflake oAuth through okta

### ISSUE THREAD

**Issue by bibhushankar** [tableau/server-client-python#913]
**Describe the bug**
We have tableau data source connecting to Snowflake using username/password. Would like to change the user to oAuth 

**Versions**
Details of your environment, including:
 - 2020.1.1
 - 3.7
 - 1.10

**To Reproduce**
import tableauserverclient as TSC

### Publish a data source
new_datasource = TSC.DatasourceItem(project_id=proj_id)
new_datasource.description = "testing publish data source {}".format(
	datasource_name
)
if tags:
	new_datasource.tags = tags

# Create a connection_credentials item if connection details are provided
new_conn_creds = TSC.ConnectionCredentials(
	sf_user, sf_password, embed=True, oauth=True
)

# Define publish mode - Overwrite, Append, or CreateNew
publish_mode = TSC.Server.PublishMode.Overwrite
# Normal publishing, returns a datasource_item
new_datasource = server.datasources.publish(
	new_datasource,
	file_path,
	publish_mode,
	connection_credentials=new_conn_creds,
)

### Also tried with update connection

import tableauserverclient as TSC
endpoint = {
	"workbook": server.workbooks,
	"datasource": server.datasources,
}.get("datasource")
update_function = endpoint.update_connection

resource = endpoint.get_by_id(datasource.id)
endpoint.populate_connections(resource)
connections = list(
	filter(
		lambda x: x.id == _connection.id,
		resource.connections,
	)
)
if len(connections) > 0:
	for connection in connections:
		if connection.connection_type == "snowflake":
			### Update connection User Id and Password
			connection.username = new_sf_user
			connection.password = new_sf_password
			connection.embed_password = True
			connection.okta = True

**Results**
It is not returning any error . But the datasource connection is still UserName/password. 
but expected output is the connection should change to OAuth 
And the authentication should be the snowflake User saved in Tableau Server saved credential.

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
This is the same problem as !822, closing.
