### ISSUE TITLE
Workbook search with filtering failure on older Tableau server versions

### ISSUE THREAD

**Issue by chaami** [tableau/server-client-python#917]
Testing a migration from Tableau Server Version: 2020.2.4 (20202.20.0721.1350) 64-bit Windows to newer versions 2021.2.2 (20212.21.0818.1843) 64-bit Linux & 2021.3.1 (20213.21.0917.1006) 64-bit Linux showed a strange behavior:

When querying the API searching for notebooks through their names on the older version, the requests fail with the 0.16.0 version of `tableauserverclient`.
What is strange, is that searching for the containing project's workbooks, I could still see that one of the, does matches (python `==` string comparison) the target string.
The query works fin on the newer versions of the server.
Querying the older server with the 0.10 version of `tableauserverclient` works...

**Versions**
New environment:
 - failing Tableau Server version 2020.2.4 (20202.20.0721.1350) 64-bit Windows
 - Python 3.9
 - TSC 0.16
 
it works for:
- 2021.2.2 (20212.21.0818.1843) 64-bit Linux) & 2021.3.1 (20213.21.0917.1006) 64-bit Linux
- Python 3.9
 - TSC 0.16

And also works for:
- Tableau Server version 2020.2.4 (20202.20.0721.1350) 64-bit Windows
- Python 3.7
- TSC 0.10

**To Reproduce**
```
request_options = RequestOptions()
request_options.filter.add(Filter(RequestOptions.Field.ProjectName, RequestOptions.Operator.Equals, project_name))
request_options.filter.add(Filter(RequestOptions.Field.Name, RequestOptions.Operator.Equals, workbook_name))
matching_workbooks, pagination_info = self._tableau.workbooks.get(request_options)
if (pagination_info.total_available != 1):
            self._logger.error(f"Search failed ({pagination_info.total_available} matches)")
```

You can use the following snippet to see that the workbook is actually there (one of the lines will have a `True`):
```
request_options = RequestOptions()
request_options.filter.add(Filter(RequestOptions.Field.ProjectName, RequestOptions.Operator.Equals, project_name))
matching_workbooks, pagination_info = self._tableau.workbooks.get(request_options)
self._logger.warning(f"Failed to correctly identify {workbook_name} in project {project_name} containing:")
for w in matching_workbooks:
    self._logger.warning(f"{w.name} ({w.name == workbook_name})")
```

**Results**
On the older version I fail to get the workbook I am searching for.

**Comment by jacalata** [comment]
Very odd, I'll have to look into this.

**Comment by jacalata** [comment]
I don't think it's worth investigating this more closely, so it can just join the list of reasons our handling of server version could be better/
