### ISSUE TITLE
Unable to fetch all workbooks for users.populate_workbooks(user)

### ISSUE THREAD

**Issue by kdutta-c** [tableau/server-client-python#930]
Unable to fetch all workbooks for a given user.

**Versions**
Details of your environment, including:
 - Tableau Online
 - Python 3.7+
 - tableauserverclient<=0.14.1

**To Reproduce**
`
import tableauserverclient as tsc
from tableauserverclient.server.endpoint.exceptions import ServerResponseError

        def get_workbooks_users(self) -> list: #tableau credentials are passed through Self

        list_workbooks_n_users = []
        try:
            with self.server.auth.sign_in(self.tableau_auth):
                for user in tsc.Pager(self.server.users):
                    if 'tol.admin.api.broker.service.usera@tableau.com' not in user.name:
                        self.server.users.populate_workbooks(user)
                        for wkb in user.workbooks:
                            print(wkb.name, user.name)
                            list_workbooks_n_users.append({
                                'user_id': user.id,
                                'user_name': user.name,
                                'wb_id': wkb.id,
                                'wb_name': wkb.name,
                                'project_id': wkb.project_id,
                                'project_name': wkb.project_name,
                                "site_id": self.site_id
                            })
        except ValueError:
            print("some thing")
        finally:
            print("some other thing")
        return list_workbooks_n_users

`

**Results**
I only get the first one hundred results for my user. I know the user has access to all tableau assets.

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by bcantoni** [comment]
Okay thanks for the confirmation. The fact that it used to work and then stopped working (presumably with a Tableau Online update) is a good clue.

**Comment by adrianrlaus** [comment]
I'm having the same issue. I'm getting a "project_id must be defined" error if I page through too many results. I'm only able to get around 140 if I play around with the page size and page number. 

I'm using the Pager generator for my function.

**Comment by jacalata** [comment]
@kdutta-c  are you also getting an error for your calls, or just not seeing all the workbooks you expect?
@adrianrlaus  - are you using Collections or Personal Spaces? Is it possible that this error is returned when you first iterate over a workbook that is *in* a collection or personal space?

**Comment by kdutta-c** [comment]
I don't see an error message when I put in the exact number of tableau workbooks into the parameters. Otherwise, I get an error
`ValueError: project_id must be defined.`
However, I don't think project_id was an input value before September 2021. It worked perfectly fine without it. 🤷

**Comment by adrianrlaus** [comment]
@jacalata I'm not using Collections or Personal Spaces

**Comment by adrianrlaus** [comment]
Any update on this?

**Comment by kdutta-c** [comment]
Hi, Any updates / hints on how to overcome this issue?

**Comment by adrianrlaus** [comment]
Hi everyone! Updating to the latest version solved it for me

**Comment by kdutta-c** [comment]
Are you sure?

I see that `class Workbook` still needs `project_id` to run.
Reference: https://github.com/tableau/server-client-python/blob/b3ca20e6765c7cff2d5b095e880dc2b2a811d825/tableauserverclient/models/workbook_item.py#L16

I am trying to list all workbook names per user to know what users have access to what workbooks. 

I am trying to do this:
`
       def get_workbooks_users(self)-> list:
        with self.server.auth.sign_in(self.tableau_auth):
            request_options = tsc.RequestOptions(pagesize=1000)
            all_users, pg = self.server.users.get(request_options)
            print(len(all_users))
            print(all_users)
            for user in all_users:
                tmp_user = user
                # self.server.users.populate_workbooks(tmp_user.id)
                print(tmp_user.id)
                self.server.users.populate_workbooks(tmp_user)
                for wkb in tmp_user.workbooks:
                    print(tmp_user.name, tmp_user.id)
            return something

`

**Comment by jorwoods** [comment]
@kdutta-c FYI, populating workbooks on a user will tell you all workbooks that that user _owns_, not all workbooks that they have access to. For owners, you can also use the metadata API, with a query like this:

```graphql
query wbowners {
  workbooks{
    owner{
      luid
      username
    }
    luid
    name
    projectName
    site{
      luid
      name
    }
  }
}
```

Getting all content that a user has _access_ to is a much more complicated affair, requiring checking the permissions of every item on the server. the group membership of each user, and so on.... OR taking the equally complicated route of signing in to the site as each user and trying to query all workbooks on the server.

**Comment by jacalata** [comment]
This should have been fixed in the linked update to tsc in mid-2022.
