### ISSUE TITLE
Documentation not updated to reflect newer user-->role based quota's in SiteItem.

### ISSUE THREAD

**Issue by mikenac** [tableau/server-client-python#951]
**Describe the bug**
API Documentation not updated to reflect newer user-->role based quota's in SiteItem. Newer API's now support quotas by role (and the code does as well).

https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_new_site_roles.htm

**Versions**
Details of your environment, including:
 - Tableau Server version REST API 3.0+
 - Python version Any
 - TSC library version 17

**To Reproduce**
Check API documentation.

**Results**
Documentation is missing user role quotas.

**Comment by jacalata** [comment]
@dzucker-tab will you have a chance to check this out?
