### ISSUE TITLE
Not able to login to "Default" Site name

### ISSUE THREAD

**Issue by pavankumartableau** [tableau/server-client-python#954]
Hi Team,
 I have simple code to show a list of Projects from a Site.

import tableauserverclient as TSC
server = TSC.Server("https://tableauserver.com/")
tableau_auth = TSC.TableauAuth('user name', 'password','Default')
with server.auth.sign_in(tableau_auth):
    all_projects, pagination_items = server.projects.get()
    projects = [projects.name for projects in all_projects]
    print(projects)

From the above code, Default is a Default site, I am not able to log in using the Default site.
We have multiple sites, so if I give any other site name, it is working.
If I leave it as a blank, I see a list of Projects from all sites as we have multiple sites.
I have a requirement where I need to show a list of Projects from the Default site.

This is the error i see.
![image](https://user-images.githubusercontent.com/19184644/140876334-9ea7f590-2da5-461e-84db-ed7c6fdb23a0.png)

Thanks
Pavan Kumar

**Comment by jacalata** [comment]
Leaving it blank is the way to say you want the default site. I'm not sure how you could end up showing projects from all sites, the API call needs a specific site to look for. Are you sure that's what's happening, and it's not just that the default site contains projects that look like other sites?

**Comment by pavankumartableau** [comment]
My bad, i was looking in a different way. Thanks for the responce
