### ISSUE TITLE
get Project Permissions Capabilities does not return all capabilities

### ISSUE THREAD

**Issue by mauropasi** [tableau/server-client-python#963]
**Describe the bug**
Only a subset of capabilities ('Read', 'Write', 'InheritedProjectLeader') of a project permissions are returned when populating permissions.

Those sound like project capabilities only. Maybe to get workbook or datasource capabilities there is something else to include that is not specified in the docs.

**Versions**
TSC version: 0.17.0
Tableau Server :  2021.3.1

**To Reproduce**
    for project in TSC.Pager(SERVER.projects):
        SERVER.projects.populate_permissions(project)
        for permission in project.permissions:
            print(permission.capabilities)

**Results**
What are the results or error messages received?

**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by bcantoni** [comment]
@mauropasi I believe there are separate calls for retrieving the permissions on projects, workbooks, etc. Take a look at the `query_permissions.py` sample to see if that helps: <https://github.com/tableau/server-client-python/blob/master/samples/query_permissions.py>

Also, the docs for permissions are behind - #736

**Comment by mauropasi** [comment]
Hi @bcantoni. 

I apologise. I see now that what I want is achieved by using dedicated methods.
projects.populate_workbook_default_permissions
projects.populate_datasource_default_permissions
projects.populate_flow_default_permissions

I will test those out.

**Comment by mauropasi** [comment]
Hope this helps somebody:

       ```
 for project in TSC.Pager(SERVER.projects):
    print(project.content_permissions)
    SERVER.projects.populate_permissions(project)
    for permission in project.permissions:
        print(permission.capabilities)
    SERVER.projects.populate_workbook_default_permissions(project)
    for wpermission in project.default_workbook_permissions:
        print(wpermission.capabilities)
    SERVER.projects.populate_datasource_default_permissions(project)
    for dpermission in project.default_datasource_permissions:
        print(dpermission.capabilities)
```
