### ISSUE TITLE
Not able to publish Workbook with Published data source

### ISSUE THREAD

**Issue by pavankumartableau** [tableau/server-client-python#965]
Tableau Server version is 2020.4.5
tableauserverclient version is 0.15.0
I have two questions
Question 1)
I am able to publish a workbook with a Live connection, but not able to publish a workbook with the published data source.
The main issue is I have two connections one is a live connection and the second is a published data source.
I tried to publish workbooks with a single connection, live is working but not a published data source.

Question 2)
Is there a way to convert the data source (connected to the workbook) from Dev to Prod while publishing the workbook?
analytics.d-datalake.com is like Dev DB server address
analytics.p-datalake.com is like Prod DB server address
User name and password remain the same.
I tried to convert it to Prod, even the workbook with a live connection is not working.

Find the code I am using.

import tableauserverclient as TSC
from tableauserverclient import ConnectionCredentials, ConnectionItem

server = TSC.Server("https://tableau.com/")
tableau_auth = TSC.TableauAuth('username', 'password', 'sitename')
with server.auth.sign_in(tableau_auth):
    all_projects, pagination_items = server.projects.get()
    default_project = next((project for project in all_projects if project.is_default()), None)
    all_connections = []
    connection = ConnectionItem()
    connection.server_address = 'analytics.d-datalake.com'
    connection.connection_credentials = ConnectionCredentials('dbuser', "dbpassword", True)
    all_connections.append(connection)
    all_connections
    new_workbook = TSC.WorkbookItem(default_project.id)
    server.workbooks.publish(new_workbook, 'Security.twbx',
                                                 TSC.Server.PublishMode.Overwrite
                                                 , connections=all_connections)
Thanks in advance

**Comment by amartincolville** [comment]
Hi @pavankumartableau 
I am not sure as I did not try this on my end, but I have a couple of remarks that maybe help you out:
1. I can see that you are publishing to the default project, maybe it is worth creating a new one so you can do your tests there. This will also give you the freedom to configure the `content_permissions` parameter. Maybe something like the code below is useful to always use the same project or create a new one:

```
def get_or_create_project(server, project_name):
    # Get project
    for project in TSC.Pager(server.projects):
        if project.name == project_name:
            return project.id

    # Create project
    new_project = server.projects.create(
        TSC.ProjectItem(
            name=project_name,
            content_permissions="LockedToProject",
            description="Project created for testing",
        )
    )

    return new_project.id
```

2. When publishing your workbook, you are only sending out the `WorkbookItem` and the `file_path`. I believe that you should also need to populate the connections via the `connections` attribute in the WorkbookItem. There you should include the list of data connections for the data sources used by the workbook. In your use case, you should use include de `ConnectionItem` for your already-published `Datasource`.

3. This is new to me, but if you wish to change the datasource for a workbook, the same would apply as previous, as the `ConnectionItem` list should be updated to the ones needed for that workbook.

I hope it helps!

**Comment by jacalata** [comment]
Hi @pavankumartableau , did you solve your problem here?
