### ISSUE TITLE
Publish Workbook with published data source to another site

### ISSUE THREAD

**Issue by pavankumartableau** [tableau/server-client-python#966]
Tableau Server version is 2020.4.5
tableauserverclient version is 0.17.0
Python version 3.9

Hi,
I have two sites, assume their names as Sandbox1 and Sandbox2.
So, initially, I have created a Workbook, then published that data source to the "Sandbox1" site.
I can move that workbook among projects in the "Sandbox1" site using python code.
Now, I want to move the same workbook to the "Sandbox2" site using python code,
I have already moved the published data source to "Sandbox2", then I have been trying to publish the workbook to "Sandbox2" , which is not working for me.

Find the code,

`
import tableauserverclient as TSC
from tableauserverclient import ConnectionCredentials, ConnectionItem

server = TSC.Server("https://tableaudev.co/")
tableau_auth = TSC.TableauAuth('username', 'password', 'Sandbox2')
with server.auth.sign_in(tableau_auth):
    all_projects, pagination_items = server.projects.get()
    default_project = next((project for project in all_projects if project.is_default()), None)
    new_workbook = TSC.WorkbookItem(default_project.id)
    server.workbooks.publish(new_workbook, 'C:/Users/Pavan/Security Published Datasource.twbx',
                                                 TSC.Server.PublishMode.Overwrite
                                                 )
I am able to publish the workbooks which have Excel or Extracts as a data source.
Note: i have Migrated published data source to "Sandbox2".

Error Message: 
![image](https://user-images.githubusercontent.com/19184644/144823290-e37519ad-7286-4530-b6a7-cbebf0fc3561.png)

**Comment by jorwoods** [comment]
It looks like the workbook XML contains references to the published datasource, and this may not be able to be completed successfully without modifying that.

**Comment by jacalata** [comment]
I think this would require the document api (https://github.com/tableau/document-api-python) to update the datasource references in the workbook. This isn't currently supported within the python library.
