### ISSUE TITLE
ValueError: project_id must be defined

### ISSUE THREAD

**Issue by hanishche** [tableau/server-client-python#974]
Hi,

I am running into error:  ValueError: project_id must be defined.

Below is the code:

```
tsConn = TableauServerConnection('server_url','Token_name','token','site')
server = TSC.Server(tsConn.server_url, use_server_version=True)
tableau_auth = TSC.PersonalAccessTokenAuth(token_name=tsConn.token_name
                                           ,personal_access_token=tsConn.token_secret
                                           ,site_id=tsConn.site)
with server.auth.sign_in_with_personal_access_token(tableau_auth):
    print('[Logged in successfully to {}]'.format(tsConn.server_url))
    print('[Loading workbooks...]')        
    all_workbooks, pagination_item = server.workbooks.get()
    tableauWB = []
    for workbook in TSC.Pager(server.workbooks.get):
        tableauWB.append(
        (workbook.id
         ,workbook.name
         ,workbook.owner_id
         ,workbook.content_url
          ,'None' if len(workbook.project_id) ==0 else workbook.project_id
         ,workbook.project_name
         ,workbook.size
         ,'None' if len(workbook.tags) ==0 else workbook.tags
         ,pd.to_datetime(str(workbook.created_at)) 
         ,pd.to_datetime(str(workbook.updated_at)) 
         ,workbook.webpage_url       ))

print('[Tableau {} workbooks loaded]'.format(len(tableauWB)))

```

![image](https://user-images.githubusercontent.com/32518059/149996230-440e3b29-eccf-47e2-bc27-56bae861ca92.png)

**Comment by bcantoni** [comment]
May be similar to #930

**Comment by jpsued** [comment]
Hi together,
I'm getting this error after we upgraded from Tableau Server version 2020.2.4 to 2021.3.6.
All data sources / workbooks I'm getting the error for are located in the new introduced 'Personal Space' 
Maybe this helps to track down/handle the issue.

**Comment by Planswalker** [comment]
Hi everyone,

I'm also running into this exact issue when trying to query all workbooks. I can also confirm that this is related to the "Personal Space" feature, which would make sense since if I'm understanding the wording in https://help.tableau.com/current/pro/desktop/en-us/personal_space.htm correctly, Workbooks created in a Personal Space aren't associated with a project by design. 

Is there a reason that the project_id field is required for creating a workbook? Or can we make that an optional parameter without issue?

**Comment by bcmyguest1** [comment]
Left a PR to remove the requirement for project_id to not be `None`. The requirement for it to be non-null was added in 2016, long before the personal space feature. The workbook object returned in XML does not contain a project_id, so the facade (TSC) should not require it.
