### ISSUE TITLE
Adding tableau local group to project is not working

### ISSUE THREAD

**Issue by dixit06** [tableau/server-client-python#985]
**Describe the bug**

Adding tableau local group to project is not working using TSC
**Versions**
Details of your environment, including:
 - Tableau Server version (or note if using Tableau Online)0.15.0
 - Python version 3.6
 - TSC library version

**To Reproduce**
Steps to reproduce the behavior. Please include a code snippet where possible.
My code looks like this - 
perm_capability = {TSC. Permission.Capability.Read: TSC.permission.Mode.Allow}
perm_rule = TSC.PermissionRule(grantee=group_item,capabilities= perm_capability)
server.projects.update_permissions(project_item, perm_rule)

**Results**
What are the results or error messages received?
TypeError: permissionsRule object is not iterable
**NOTE:** Be careful not to post user names, passwords, auth tokens or any other private or sensitive information.

**Comment by jacalata** [comment]
It's expecting the perm_rule item to be a list (that's what "x is not iterable always means).
You can make it a list just by wrapping brackets around it, have a look at the a[dd_default_permission sample code:](https://github.com/tableau/server-client-python/blob/master/samples/add_default_permission.py)

```
            new_rules = [TSC.PermissionsRule(
                grantee=default_permissions.grantee,
                capabilities=new_capabilities
            )]
```

**Comment by dixit06** [comment]
Thanks! This fixed the issue
