### ISSUE TITLE
Permissions: Add Default Data roles, Lenses & Metrics

### ISSUE THREAD

**Issue by dolphinowl** [tableau/server-client-python#997]
There are default permission capabilities resources available in the REST API, but unavailable in Tableau Server Client (TSC).

For each of Data roles, Lenses & Metrics add similar functionality to that of workbook default permissions (ie `projects.populate_workbook_default_permissions`, `projects.update_workbook_default_permissions` and `projects.delete_workbook_default_permissions`)

**Comment by t8y8** [comment]
I no longer have access to test this easily -- but it should be pretty much copy/paste and rename classes + endpoints. I'm happy to review a PR for anyone who can make one!

**Comment by jacalata** [comment]
this has been added
